import type { CityEvent } from "./types";

export const cityEvents: CityEvent[] = [
  {
    slug: "durga-puja",
    name: "Durga Puja",
    bengali: "দুর্গা পূজা",
    monthIndex: 9,
    when: "Late September or October",
    duration: "Five main days, three weeks of build-up",
    where: "The entire city",
    kind: "festival",
    summary:
      "The largest public art event in the world, and the only reason to visit Kolkata if you can only visit once. Several thousand pandals, each a temporary commissioned structure, go up across the city and come down a week later. UNESCO listed it in 2021.",
    tip: "Go on Panchami or Shashthi, before the crowds peak. Ashtami evening is the busiest night of the year and moving between pandals takes hours.",
  },
  {
    slug: "kolkata-book-fair",
    name: "Kolkata Book Fair",
    bengali: "বইমেলা",
    monthIndex: 0,
    when: "Late January into February",
    duration: "12 days",
    where: "Central Park ground, Salt Lake",
    kind: "fair",
    summary:
      "The largest non-trade book fair in the world by footfall, at over two million visitors. A thousand stalls, a guest country each year, and a Little Magazine Pavilion at the back where the real literary culture is.",
    tip: "Weekday afternoons are survivable. Weekends are not. Carry cash; many small publishers still prefer it.",
  },
  {
    slug: "kali-puja",
    name: "Kali Puja & Diwali",
    bengali: "কালী পূজা",
    monthIndex: 10,
    when: "October or November, on the new moon",
    duration: "One main night",
    where: "Kalighat, Dakshineswar, and street pandals everywhere",
    kind: "festival",
    summary:
      "Bengal's answer to Diwali, held on the same night but for Kali rather than Lakshmi. Night-long worship, enormous crowds at Kalighat and Dakshineswar, and a lighting culture entirely distinct from the rest of India.",
    tip: "Chandannagar, two hours north, does the lighting better than anywhere in the country. Worth the trip.",
  },
  {
    slug: "poila-boishakh",
    name: "Poila Boishakh",
    bengali: "পয়লা বৈশাখ",
    monthIndex: 3,
    when: "14 or 15 April",
    duration: "One day",
    where: "Homes, shops, and Prabhat Pheri processions",
    kind: "festival",
    summary:
      "Bengali New Year. Shops open new account books in a ceremony called haal khata, customers are given sweets and a calendar, and everyone eats an enormous lunch. The most domestic of the city's major days.",
    tip: "Go to a sweet shop in the morning. You will be handed something whether or not you buy anything.",
  },
  {
    slug: "christmas-on-park-street",
    name: "Christmas on Park Street",
    monthIndex: 11,
    when: "Mid-December to 1 January",
    duration: "Two weeks",
    where: "Park Street, Bow Barracks, Allen Park",
    kind: "seasonal",
    summary:
      "The street is arched with lights end to end, closed to traffic in stretches, and packed nightly. Allen Park hosts a carnival and live music. Bow Barracks nearby holds the older Anglo-Indian celebration, with homemade wine on the pavement.",
    tip: "The 24th and 25th are impassable. The 20th is the same lights with a fifth of the people.",
  },
  {
    slug: "kiff",
    name: "Kolkata International Film Festival",
    monthIndex: 11,
    when: "Early December",
    duration: "8 days",
    where: "Nandan, Rabindra Sadan, and screens across the city",
    kind: "arts",
    summary:
      "Running since 1995, with the Nandan complex at its centre. Strong retrospective programming, a serious Bengali and world cinema selection, and queues that form at seven in the morning for delegate passes.",
    tip: "Register for a delegate pass in advance online. Nandan 1 is the only screen with genuinely good projection.",
  },
  {
    slug: "saraswati-puja",
    name: "Saraswati Puja",
    bengali: "সরস্বতী পূজা",
    monthIndex: 1,
    when: "Late January or February",
    duration: "One day",
    where: "Schools, colleges, and every household with a student in it",
    kind: "festival",
    summary:
      "The goddess of learning, worshipped at every educational institution in the state. Students wear yellow, books are placed at the idol's feet and not read for a day, and it functions as the city's unofficial Valentine's Day.",
    tip: "Any school or college compound will let you in. The Presidency and Jadavpur pujas are the ones people talk about.",
  },
  {
    slug: "ramadan-on-zakaria-street",
    name: "Ramadan & Eid on Zakaria Street",
    monthIndex: 2,
    when: "Shifts eleven days earlier each year",
    duration: "One month, then Eid",
    where: "Zakaria Street, below Nakhoda Masjid",
    kind: "festival",
    summary:
      "For a month the lane below the mosque runs on charcoal from late afternoon into the night: haleem, suta kebab, phirni in clay bowls, sheermal and bakarkhani. On Eid morning the street is full and impassable.",
    tip: "Go after 6pm, eat at iftar whether or not you kept the fast, and start with the haleem.",
  },
  {
    slug: "rath-yatra",
    name: "Rath Yatra at Mahesh",
    bengali: "রথযাত্রা",
    monthIndex: 6,
    when: "June or July",
    duration: "One day, with the return nine days later",
    where: "Mahesh in Serampore, and ISKCON in Kolkata",
    kind: "festival",
    summary:
      "The Mahesh Rath Yatra at Serampore has run since 1396 and is the second oldest in India after Puri. It is also, traditionally, the day the first bamboo goes up for a Durga Puja pandal, three months out.",
    tip: "Serampore is an hour by local train from Howrah. Go for the older festival rather than the city one.",
  },
  {
    slug: "kolkata-derby",
    name: "The Kolkata Derby",
    monthIndex: 8,
    when: "Usually twice a season",
    duration: "90 minutes, and a week either side",
    where: "Salt Lake Stadium",
    kind: "sport",
    summary:
      "Mohun Bagan against East Bengal, first played in 1921. It carries Partition inside it: Mohun Bagan is historically the club of West Bengal families, East Bengal of those who came from the east. The fish markets sell prawn and hilsa as proxies on match day.",
    tip: "Buy through the club rather than at the gate. Salt Lake's capacity means the atmosphere is enormous even two-thirds full.",
  },
  {
    slug: "jagaddhatri-puja",
    name: "Jagaddhatri Puja at Chandannagar",
    monthIndex: 10,
    when: "November, a month after Durga Puja",
    duration: "5 days",
    where: "Chandannagar, ninety minutes north",
    kind: "festival",
    summary:
      "A former French colony holds the best light installations in India: enormous animated tableaux built from thousands of individually sequenced bulbs, a craft held by a few families in the town.",
    tip: "Go for the immersion procession, which runs all night and is lit entirely by the installations being carried along it.",
  },
  {
    slug: "gangasagar-mela",
    name: "Gangasagar Mela",
    monthIndex: 0,
    when: "Around 14 January, at Makar Sankranti",
    duration: "3 days",
    where: "Sagar Island, where the Hooghly meets the Bay of Bengal",
    kind: "fair",
    summary:
      "After the Kumbh, the largest gathering of people in India. Several million pilgrims travel to the mouth of the river to bathe at the confluence, on an island reachable only by ferry.",
    tip: "This is a serious logistical undertaking rather than a day trip. Go with an organised group or not at all.",
  },
];

export const months = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];
