import type { FamousStrand } from "./types";

export const famousFor: FamousStrand[] = [
  {
    slug: "food",
    icon: "🥘",
    title: "Food",
    line: "Mustard oil, freshwater fish, fresh curd cheese, and a relationship with sugar other cuisines find excessive.",
    items: [
      { name: "Rosogolla", note: "Chhena boiled in thin syrup. Nobin Chandra Das, Bagbazar, 1868.", href: "/food/rosogolla" },
      { name: "Mishti doi", note: "Yoghurt set with caramelised sugar in an unglazed clay pot.", href: "/food/mishti-doi" },
      { name: "Sandesh", note: "Chhena and sugar, and about forty named variations." },
      { name: "Kathi roll", note: "Kebab off the skewer in an egg paratha. Nizam's, 1932.", href: "/food/kathi-roll" },
      { name: "Kolkata biryani", note: "Lighter, perfumed, and containing a whole potato.", href: "/food/kolkata-biryani" },
      { name: "Telebhaja", note: "Things fried in besan. The smell of the monsoon.", href: "/food/telebhaja" },
      { name: "Phuchka", note: "Sour, not sweet. Never call it pani puri here.", href: "/food/phuchka" },
      { name: "Jhalmuri", note: "Puffed rice shaken in a tin, in ninety seconds.", href: "/food/jhalmuri" },
      { name: "Ghugni", note: "Yellow peas with coconut and chilli, sold from a handcart." },
      { name: "Luchi", note: "Maida puris that puff into spheres. Never atta.", href: "/food/luchi-alur-dom" },
      { name: "Alur dom", note: "Baby potatoes, sweet-sour, finished with ghee." },
      { name: "Kosha mangsho", note: "Mutton cooked down until the gravy becomes a coating.", href: "/food/kosha-mangsho" },
      { name: "Fish", note: "Bhetki, pabda, parshe, koi, chitol, and hilsa in the monsoon." },
      { name: "Chingri malai curry", note: "Prawns in coconut milk. The name has nothing to do with Malay." },
    ],
  },
  {
    slug: "books",
    icon: "📚",
    title: "Books",
    line: "A city that will still buy poetry at scale, which almost no other market anywhere does.",
    items: [
      { name: "College Street", note: "A mile and a half of secondhand stalls.", href: "/neighbourhoods/college-street" },
      { name: "Boi Para", note: "The book neighbourhood. Publishers, printers and binderies behind the stalls." },
      { name: "Presidency University", note: "Founded 1817 as Hindu College, and the engine of the Bengal Renaissance." },
      { name: "University of Calcutta", note: "1857. The first multidisciplinary Western-style university in Asia." },
      { name: "Indian Coffee House", note: "Worker-owned since 1958. The room where the century was argued out." },
      { name: "Kolkata Book Fair", note: "Two million visitors over twelve days. The largest non-trade fair anywhere." },
      { name: "Little magazines", note: "Hundreds of them, hand-stapled, and where the actual literary culture is." },
    ],
  },
  {
    slug: "football",
    icon: "⚽",
    title: "Football",
    line: "In 1911 a barefoot Indian team beat a British regiment in a final, and the city has not stopped talking about it.",
    items: [
      { name: "Mohun Bagan", note: "Founded 1889. Beat East Yorkshire Regiment 2–1 barefoot in the 1911 IFA Shield." },
      { name: "East Bengal", note: "Founded 1920. After Partition, the club of those who came from the east." },
      { name: "Mohammedan Sporting", note: "Founded 1891. Won five consecutive Calcutta League titles in the 1930s." },
      { name: "The Maidan", note: "All three clubs' tents, within a few hundred metres of each other.", href: "/neighbourhoods/esplanade" },
      { name: "The derby", note: "Salt Lake Stadium, over a hundred thousand, and prawn against hilsa in the fish market." },
      { name: "Salt Lake Stadium", note: "Once above 100,000 capacity, and still among the largest anywhere." },
    ],
  },
  {
    slug: "cinema",
    icon: "🎬",
    title: "Cinema",
    line: "Three filmmakers, within ten miles of each other, made three completely different arguments about what a film could be.",
    items: [
      { name: "Satyajit Ray", note: "Pather Panchali, 1955, shot on weekends over two and a half years.", href: "/people/satyajit-ray" },
      { name: "Ritwik Ghatak", note: "Eight features, mostly about Partition, mostly commercial failures.", href: "/people/ritwik-ghatak" },
      { name: "Mrinal Sen", note: "Broke the fourth wall in Interview and Calcutta 71, and never apologised." },
      { name: "Uttam Kumar & Suchitra Sen", note: "Thirty films, and the shared memory of a generation.", href: "/people/suchitra-sen" },
      { name: "Tollywood", note: "Named for Tollygunge, where New Theatres established the industry in the 1930s.", href: "/neighbourhoods/tollygunge" },
      { name: "Nandan", note: "The state film centre, designed with Ray's involvement, and the festival's home." },
    ],
  },
  {
    slug: "theatre",
    icon: "🎭",
    title: "Theatre",
    line: "A professional stage since the 1870s, a group theatre movement since the 1940s, and jatra companies still cast on Chitpur Road.",
    items: [
      { name: "Bengali theatre", note: "Girish Chandra Ghosh built the professional stage: paid companies, six nights a week." },
      { name: "Group theatre", note: "From the 1940s: Bohurupee, Nandikar, Theatre Workshop. Political, and unsubsidised." },
      { name: "Jatra", note: "Folk theatre in the round, played to village audiences of thousands.", href: "/neighbourhoods/chitpur" },
      { name: "Star Theatre", note: "1883, built on Binodini Dasi's earnings and named without her." },
      { name: "Utpal Dutt", note: "Wrote for the proscenium and the jatra stage with equal seriousness." },
      { name: "Sombhu Mitra", note: "Founded Bohurupee, and staged Rabindranath as living theatre rather than heritage." },
    ],
  },
  {
    slug: "art",
    icon: "🎨",
    title: "Art",
    line: "The Bengal School turned Indian painting away from Victorian realism, and the pandals turned a festival into the largest public art programme on earth.",
    items: [
      { name: "Bengal School", note: "Abanindranath Tagore and Nandalal Bose, from 1905. Wash technique, Asian idiom." },
      { name: "Government College of Art", note: "1864. Where Abanindranath taught and the school was formed." },
      { name: "Kalighat pat", note: "Fast, flat, satirical brush paintings sold to pilgrims from the 1830s.", href: "/neighbourhoods/kalighat" },
      { name: "Jamini Roy", note: "Took the Kalighat idiom and made a modern practice out of it." },
      { name: "Pandal art", note: "Thousands of commissioned installations, built and destroyed inside a fortnight.", href: "/durga-puja" },
      { name: "Contemporary galleries", note: "Experimenter, Emami Art, the Kolkata Centre for Creativity, Akar Prakar." },
    ],
  },
  {
    slug: "music",
    icon: "🎵",
    title: "Music",
    line: "Two thousand songs by one man, and a city that still keeps a harmonium in the front room.",
    items: [
      { name: "Rabindra Sangeet", note: "Around 2,230 songs, set by Tagore himself, and the default emotional vocabulary." },
      { name: "Nazrul Geeti", note: "Kazi Nazrul Islam's songs: ghazal, kirtan, and a great deal of political fury." },
      { name: "Baul", note: "Wandering mystic singers of rural Bengal, on the UNESCO list since 2005." },
      { name: "Bengali bands", note: "Mohiner Ghoraguli in the 1970s, then Cactus, Chandrabindoo, Fossils." },
      { name: "Classical music", note: "The Dover Lane Music Conference each January, running all night for four nights." },
      { name: "Park Street jazz", note: "Trincas, Blue Fox and Moulin Rouge, and a circuit that produced Usha Uthup.", href: "/neighbourhoods/park-street" },
    ],
  },
  {
    slug: "festivals",
    icon: "🪔",
    title: "Festivals",
    line: "The calendar is the city's real infrastructure, and almost all of it lands between September and February.",
    items: [
      { name: "Durga Puja", note: "UNESCO listed in 2021. Several thousand pandals, built and gone in a fortnight.", href: "/durga-puja" },
      { name: "Kali Puja", note: "Bengal's answer to Diwali, on the same new moon but for Kali." },
      { name: "Poila Boishakh", note: "Bengali New Year. Shops open new account books and hand out sweets." },
      { name: "Saraswati Puja", note: "Every school and college. Yellow, and the city's unofficial Valentine's Day." },
      { name: "Jagaddhatri Puja", note: "At Chandannagar, with the best light installations in India." },
      { name: "Christmas", note: "Park Street arched with lights, and Bow Barracks with homemade wine." },
      { name: "Eid", note: "Zakaria Street below Nakhoda Masjid, on charcoal, for a month." },
    ],
  },
];

export function getFamousStrand(slug: string) {
  return famousFor.find((f) => f.slug === slug);
}
