import type { HeritageSite } from "./types";

/** The second half of the heritage list, added to `heritageSites`. */
export const heritageExtra: HeritageSite[] = [
  {
    slug: "st-johns-church",
    name: "St. John's Church",
    built: "1787",
    builtYear: 1787,
    architect: "James Agg",
    style: "Georgian, after St Martin-in-the-Fields",
    neighbourhood: "BBD Bagh",
    coords: { lat: 22.5698, lng: 88.3468 },
    era: "company",
    summary:
      "The city's third-oldest church, built on a graveyard, with Job Charnock's mausoleum in the yard and the Last Supper painted with Calcutta merchants as the apostles.",
    body: [
      "It was the cathedral of Calcutta until St. Paul's took over in 1847. James Agg modelled it on St Martin-in-the-Fields, and Warren Hastings laid the foundation stone in 1784. The stone came from the ruins of Gaur, the medieval capital of Bengal, which the Company quarried without much ceremony.",
      "The churchyard is the reason to come. Job Charnock's octagonal mausoleum stands in it, built by his son-in-law around 1695, and the dark stone it is made of was unfamiliar enough to geologists that they named it charnockite after him. It is still the standard term for that class of rock.",
      "Inside is Johann Zoffany's Last Supper, painted in 1787, in which the apostles are portraits of Calcutta residents. The auctioneer William Tulloh is St. Peter, and Judas is a local solicitor Zoffany apparently disliked, which caused a certain amount of trouble at the time.",
      "The Black Hole memorial, moved here from the GPO site in 1940, stands in the grounds, as does the mausoleum of Admiral Watson and a monument to the Rohilla War.",
    ],
    detail: [
      { label: "Consecrated", value: "1787" },
      { label: "Stone", value: "Quarried from the ruins of Gaur" },
      { label: "Zoffany's Last Supper", value: "1787, with local sitters" },
      { label: "Charnock's mausoleum", value: "c. 1695, in the churchyard" },
    ],
    overlooked:
      "The type of rock Charnock's mausoleum is cut from is called charnockite worldwide because of this building. A Calcutta grave named a global rock classification.",
    scene: "rooftops",
  },
  {
    slug: "general-post-office",
    name: "General Post Office",
    alsoKnownAs: "The GPO",
    built: "1868",
    builtYear: 1868,
    architect: "Walter Granville",
    style: "Corinthian, with a lead-covered dome",
    neighbourhood: "BBD Bagh",
    coords: { lat: 22.5751, lng: 88.3465 },
    era: "raj",
    summary:
      "A colonnaded dome on the footprint of the original Fort William, with brass markers in the pavement showing where the Black Hole stood.",
    body: [
      "The site matters more than the building. This is where the first Fort William stood, the one Siraj-ud-Daulah took in June 1756, and the guardroom that became known as the Black Hole was somewhere under the present steps.",
      "Walter Granville, who also designed the Indian Museum and the High Court, put up the GPO in 1868 with a tall Corinthian colonnade and a dome faced in lead. The rotunda inside is one of the better interior spaces in the city and is still a working post office.",
      "Brass strips set into the pavement on the north-east side mark the outline of the Black Hole cell as it was surveyed in the nineteenth century. Most people walk over them without noticing.",
      "The Postal Museum upstairs holds early Indian stamps, including the Scinde Dawk of 1852, the first adhesive postage stamp used in Asia. It keeps irregular hours.",
    ],
    detail: [
      { label: "Built", value: "1868" },
      { label: "Site", value: "The original Fort William, taken in 1756" },
      { label: "Dome", value: "Lead-covered, on a Corinthian drum" },
      { label: "Museum", value: "Philatelic collection upstairs" },
    ],
    overlooked:
      "The brass lines in the pavement. They mark the Black Hole outline, and there is no sign explaining them.",
    scene: "rooftops",
  },
  {
    slug: "calcutta-high-court",
    name: "Calcutta High Court",
    built: "1872",
    builtYear: 1872,
    architect: "Walter Granville",
    style: "Gothic Revival, after the Cloth Hall at Ypres",
    neighbourhood: "Esplanade Row",
    coords: { lat: 22.5687, lng: 88.3435 },
    era: "raj",
    summary:
      "The oldest high court in India, in a red-brick Gothic pile copied from a medieval cloth hall in Flanders.",
    body: [
      "Established in 1862 as the High Court of Judicature at Fort William, it is the oldest of India's high courts, predating Bombay and Madras by a few months. Its jurisdiction once ran from Assam to Burma.",
      "Granville modelled the building on the Lakenhal, the thirteenth-century Cloth Hall at Ypres, which is an unusual choice for a courthouse and produces an unusually good one: a long arcaded facade, a central tower, and a great deal of red brick and pale dressing.",
      "The Ypres original was destroyed by shellfire in the First World War and later rebuilt, which means that for a period the Calcutta copy was the better surviving example of the design.",
      "It is a working court, and the corridors are full of black-gowned advocates, typists at portable tables and enormous bundles of paper tied with red tape, which is where the phrase comes from.",
    ],
    detail: [
      { label: "Established", value: "1862" },
      { label: "Building", value: "1872, Walter Granville" },
      { label: "Modelled on", value: "The Cloth Hall at Ypres" },
      { label: "Access", value: "Public galleries; security at the gate" },
    ],
    overlooked:
      "The typists. Rows of them at folding tables outside, still producing affidavits on manual machines, because the court's forms have never stopped requiring them.",
    scene: "rooftops",
  },
  {
    slug: "raj-bhavan",
    name: "Raj Bhavan",
    alsoKnownAs: "Government House",
    built: "1803",
    builtYear: 1803,
    architect: "Charles Wyatt",
    style: "Neoclassical, after Kedleston Hall",
    neighbourhood: "Esplanade",
    coords: { lat: 22.5657, lng: 88.3487 },
    era: "company",
    summary:
      "Built by Wellesley on the plan of a Derbyshire country house, and the seat of the Governor-General until the capital moved to Delhi.",
    body: [
      "Richard Wellesley arrived as Governor-General in 1798 and decided the Company's representative should be housed like a sovereign. He commissioned Charles Wyatt, an engineer, to build a palace on the plan of Kedleston Hall in Derbyshire: a central block with four curved corridors leading to four wings.",
      "It cost about thirteen lakh rupees against a sanctioned two, and the Company recalled Wellesley partly over it. He is said to have remarked that India should be governed from a palace, not a counting house.",
      "It was the residence of the Governor-General of India until 1912 and then of the Governor of Bengal, and it is now the Governor of West Bengal's residence. Six of the seven Viceroys before the move to Delhi lived here.",
      "The grounds hold Tipu Sultan's captured cannon and a set of Chinese cannon from the Opium Wars. The building is closed to the public and visible from the Maidan and Esplanade Row.",
    ],
    detail: [
      { label: "Built", value: "1799–1803" },
      { label: "Modelled on", value: "Kedleston Hall, Derbyshire" },
      { label: "Cost", value: "About ₹13 lakh, against ₹2 lakh sanctioned" },
      { label: "Access", value: "Closed. Exterior only." },
    ],
    overlooked:
      "The lions on the north gate hold globes rather than the usual orbs, which was Wellesley's idea of subtlety about what the building was for.",
    scene: "victoria",
  },
  {
    slug: "town-hall",
    name: "Town Hall",
    built: "1813",
    builtYear: 1813,
    architect: "Colonel John Garstin",
    style: "Roman Doric",
    neighbourhood: "Esplanade Row West",
    coords: { lat: 22.5709, lng: 88.3446 },
    era: "company",
    summary:
      "Paid for by public lottery, and the room where Jagadish Chandra Bose sent a radio wave through three walls in 1895.",
    body: [
      "The Town Hall was funded by a public lottery, which was how a surprising amount of early nineteenth-century Calcutta was built, and completed in 1813 to Colonel Garstin's Roman Doric design. It was meant as a meeting place for the European community and became the city's principal public room.",
      "In November 1895, in the main hall, Jagadish Chandra Bose transmitted a millimetre-wave radio signal through two walls and the body of the Lieutenant-Governor to ring a bell and detonate a small charge in another room. This was a year before Marconi's public demonstration on Salisbury Plain, and Bose declined to patent any of it.",
      "The building fell into serious disrepair and was restored in the 1990s. It now houses a Kolkata history museum with dioramas, a collection of statuary rescued from other sites, and an archive.",
      "It sits directly opposite the Maidan and next to the High Court, which makes the trio of Town Hall, High Court and Raj Bhavan the densest few hundred metres of Company-era public building anywhere.",
    ],
    detail: [
      { label: "Built", value: "1813" },
      { label: "Funded by", value: "Public lottery" },
      { label: "Bose's demonstration", value: "November 1895, in the main hall" },
      { label: "Now", value: "Kolkata history museum" },
    ],
    overlooked:
      "The basement holds statues removed from public sites after independence, including several viceroys nobody wanted on a plinth any more.",
    scene: "victoria",
  },
  {
    slug: "metcalfe-hall",
    name: "Metcalfe Hall",
    built: "1844",
    builtYear: 1844,
    architect: "C. K. Robinson",
    style: "Greek Revival, after the Tower of the Winds",
    neighbourhood: "Strand Road",
    coords: { lat: 22.5766, lng: 88.3448 },
    era: "company",
    summary:
      "Thirty Corinthian columns copied from Athens, built for a public library, and named for the Governor-General who abolished press censorship.",
    body: [
      "Charles Metcalfe was acting Governor-General for a year in 1835 and used it to abolish the restrictions on the press, which made him popular with the Calcutta public and unpopular with the Company. The hall was raised by public subscription in his honour.",
      "Robinson gave it thirty Corinthian columns, twelve metres high, taken from the Temple of the Winds in Athens and the Tower of the Winds. The result is severe, Greek and completely unlike the stuccoed Palladian city around it.",
      "It housed the Calcutta Public Library, which merged into the Imperial Library in 1903 and became the National Library after independence. The building then held the Agri-Horticultural Society and a good deal of neglect.",
      "The Archaeological Survey restored it in the 2010s and it now holds an exhibition on the city, though its opening hours are unreliable.",
    ],
    detail: [
      { label: "Built", value: "1840–1844" },
      { label: "Columns", value: "30, twelve metres, Corinthian" },
      { label: "Named for", value: "Sir Charles Metcalfe, who freed the press in 1835" },
      { label: "Now", value: "ASI exhibition space" },
    ],
    overlooked:
      "The building faces the river, not the road, because it was designed to be arrived at by boat.",
    scene: "howrah",
  },
  {
    slug: "fort-william",
    name: "Fort William",
    built: "1781",
    builtYear: 1781,
    architect: "Captain John Brohier and others",
    style: "Vauban-style octagonal star fort",
    neighbourhood: "Maidan",
    coords: { lat: 22.5548, lng: 88.3363 },
    era: "company",
    summary:
      "An octagonal star fort so expensive and so well designed that nobody ever attacked it, and the reason the Maidan exists.",
    body: [
      "The first Fort William, near what is now the GPO, fell to Siraj-ud-Daulah in June 1756. After Plassey the Company built a second one, further south, on a scale that assumed it would have to hold against a European army.",
      "It is an irregular octagon on the Vauban system, with five landward bastions and three facing the river, a wet ditch, and glacis on every side. Construction ran from 1758 to 1781 and cost around two million pounds, which was an enormous sum and remains the most expensive thing the Company built in India.",
      "To give the guns a clear field of fire the Company cleared the jungle and the village of Gobindapur around it. That clearing was never built on, and it is the Maidan: roughly a thousand acres of open ground in the middle of the city, which exists entirely as a side effect of artillery ranges.",
      "It was never attacked. It is now the headquarters of the Indian Army's Eastern Command and closed to the public. The star plan is legible from the air and from nowhere on the ground.",
    ],
    detail: [
      { label: "Built", value: "1758–1781" },
      { label: "Cost", value: "About £2 million" },
      { label: "Plan", value: "Irregular octagon, eight bastions" },
      { label: "Access", value: "Active military base. Closed." },
    ],
    overlooked:
      "The Maidan is the fort's field of fire. The largest open space in any Indian city exists because of a sightline for cannon that were never fired.",
    scene: "victoria",
  },
  {
    slug: "jorasanko-thakurbari",
    name: "Jorasanko Thakurbari",
    alsoKnownAs: "The Tagore House",
    built: "Late 18th century, extended through the 19th",
    builtYear: 1785,
    style: "Bengali courtyard mansion with Palladian additions",
    neighbourhood: "Jorasanko, North Kolkata",
    coords: { lat: 22.5852, lng: 88.3617 },
    era: "renaissance",
    summary:
      "The house where Rabindranath Tagore was born, wrote, painted and died, and where a family more or less invented modern Bengali culture.",
    body: [
      "The Tagores took the house in the late eighteenth century. Prince Dwarkanath made the fortune; his son Debendranath turned the household into the centre of the Brahmo reform movement; and their descendants ran magazines, a theatre, a press and a painting school out of the same courtyard.",
      "Rabindranath was born here in May 1861, the fourteenth child. He was educated largely inside the house, wrote Gitanjali here, composed a substantial share of his two thousand songs here, and died here in August 1941, in the room he was born in.",
      "Abanindranath and Gaganendranath Tagore founded the Bengal School of Art in these rooms, reorienting Indian painting away from Victorian academic realism and towards a deliberately Asian idiom. Jyotirindranath ran the theatre. Swarnakumari Devi was among the first women novelists in Bengali.",
      "It is now Rabindra Bharati University and a museum. Rooms are preserved as they were, including the bed, the palanquin, and the manuscripts whose crossings-out he later turned into drawings.",
      "There are galleries on his Japanese, Hungarian and Chinese connections that almost nobody visits, and they are the most interesting part.",
    ],
    detail: [
      { label: "Tagore born", value: "7 May 1861" },
      { label: "Tagore died", value: "7 August 1941, in the same room" },
      { label: "Now", value: "Rabindra Bharati University and museum" },
      { label: "Closed", value: "Mondays" },
    ],
    overlooked:
      "The Hungarian gallery, on Tagore's friendship with the Balatonfüred sanatorium that treated him in 1926. There is a Tagore promenade in Hungary because of it.",
    scene: "rooftops",
  },
  {
    slug: "armenian-church",
    name: "Armenian Church of the Holy Nazareth",
    built: "1724",
    builtYear: 1724,
    style: "Armenian Apostolic, with a later spire",
    neighbourhood: "Armenian Street, Burrabazar",
    coords: { lat: 22.5766, lng: 88.355 },
    era: "pre-colonial",
    summary:
      "The oldest church in Kolkata, built by a community that was trading here before the East India Company arrived.",
    body: [
      "Armenian merchants were established in Bengal well before the Company. There is a gravestone in the churchyard dated 1630, sixty years before Job Charnock landed, and it is the single strongest piece of evidence against the idea that Charnock founded the city.",
      "The present church was built in 1724 on the site of an earlier wooden chapel that burned down. Agha Nazar funded it. The spire was added in 1734 and carries a clock donated in 1790 that still works.",
      "The community was large, wealthy and philanthropic: it built the Armenian College in 1821, which still operates and still draws students from Armenia and Iran. The congregation in Kolkata is now very small.",
      "Services are held in Armenian. The interior is plain, whitewashed and cool, with a marble floor made of gravestones, and it is one of the quietest rooms in Burrabazar.",
    ],
    detail: [
      { label: "Built", value: "1724, on an earlier chapel site" },
      { label: "Oldest gravestone", value: "1630, predating Charnock" },
      { label: "Spire and clock", value: "1734; clock donated 1790" },
      { label: "Armenian College", value: "Founded 1821, still operating" },
    ],
    overlooked:
      "The 1630 gravestone of Rezabeebeh. It is the physical evidence that there was a settled trading community here two generations before the Company.",
    scene: "rooftops",
  },
  {
    slug: "beth-el-synagogue",
    name: "Beth El Synagogue",
    built: "1856",
    builtYear: 1856,
    style: "Neoclassical, with Baghdadi Jewish detail",
    neighbourhood: "Pollock Street, Burrabazar",
    coords: { lat: 22.5747, lng: 88.3529 },
    era: "raj",
    summary:
      "One of three surviving synagogues of a Baghdadi Jewish community that once numbered thousands and now numbers a few dozen, maintained by Muslim caretakers.",
    body: [
      "Baghdadi Jews came to Calcutta from Iraq, Syria and Persia from the late eighteenth century, trading in indigo, opium, jute and later real estate. The community reached perhaps five or six thousand by the 1940s and built synagogues, schools, a hospital and a cemetery.",
      "Beth El was built in 1856 on Pollock Street. Magen David, larger and more elaborate, followed in 1884 around the corner. Neveh Shalome, the oldest, dates from 1826 and was rebuilt in 1911.",
      "Almost the entire community left after 1947 and 1948, for Israel, Britain and Australia. Fewer than twenty Jews now live in Kolkata, and there has not been a regular minyan for decades.",
      "The buildings survive because they are looked after. The caretakers of all three synagogues are Muslim, several from families who have held the job for generations, and they hold the keys and show visitors round. It is one of the better facts about this city.",
    ],
    detail: [
      { label: "Built", value: "1856" },
      { label: "Community peak", value: "Around 5,000–6,000 in the 1940s" },
      { label: "Now", value: "Fewer than 20 Jews in Kolkata" },
      { label: "Access", value: "Ask the caretaker; carry photo ID" },
    ],
    overlooked:
      "Nahoum & Sons in New Market, founded 1902, is the last of the community's businesses. The plum cake at Christmas is not a tourist thing; the queue is real.",
    scene: "rooftops",
  },
  {
    slug: "kumartuli-workshops",
    name: "The Kumartuli Workshops",
    built: "Early 18th century onwards",
    builtYear: 1720,
    style: "Working craft quarter",
    neighbourhood: "Kumartuli, North Kolkata",
    coords: { lat: 22.6006, lng: 88.3616 },
    era: "company",
    summary:
      "Not a monument but a living one: three hundred years of potters in a few lanes, and the reason Durga Puja looks the way it does.",
    body: [
      "The Company's settlement plan put trades into their own quarters, and the potters went here. The lanes have been in continuous use ever since, which makes Kumartuli one of the oldest continuously functioning craft districts in India.",
      "The work is seasonal and enormous. Several thousand idols leave these lanes each autumn for Pujas across the city, the state and, increasingly, the diaspora. A mid-sized figure takes four to six weeks; a major pandal commission takes months and a team.",
      "The technique is specific: a bamboo frame, rice straw bound with jute rope, entel mati clay from the riverbed, then a finer bele mati mixed with husk, then paint, then the eyes last of all on Mahalaya.",
      "It is under pressure. Clay costs rise as riverbank extraction is restricted, the lanes flood, and younger family members leave for salaried work. The number of workshops has been broadly flat for two decades while the number of Pujas has grown.",
      "There is nothing to buy and no ticket. Go early, ask before photographing, and do not touch a finished face.",
    ],
    detail: [
      { label: "In use since", value: "Early eighteenth century" },
      { label: "Idols each autumn", value: "Several thousand" },
      { label: "A mid-sized idol", value: "Four to six weeks" },
      { label: "Best time", value: "August to Mahalaya" },
    ],
    overlooked:
      "The armature makers. The people who bind the straw are usually not the people whose names are on the studio, and they are the ones who decide whether the figure will stand.",
    scene: "kumartuli",
  },
];
