import type { Coords } from "./types";

export type HiddenKind =
  | "building"
  | "mansion"
  | "temple"
  | "cemetery"
  | "detail"
  | "sign"
  | "theatre"
  | "market"
  | "street"
  | "courtyard"
  | "press"
  | "bakery";

export interface HiddenPlace {
  /** Stable catalogue number. Do not renumber; append. */
  n: number;
  slug: string;
  name: string;
  kind: HiddenKind;
  where: string;
  coords: Coords;
  /** The hook. Why you did not know this existed. */
  line: string;
  note: string;
  access: string;
}

export const hiddenKinds: { id: HiddenKind; label: string }[] = [
  { id: "building", label: "Forgotten buildings" },
  { id: "mansion", label: "Old mansions" },
  { id: "temple", label: "Hidden temples" },
  { id: "cemetery", label: "Old cemeteries" },
  { id: "detail", label: "Heritage doors & details" },
  { id: "sign", label: "Old signs" },
  { id: "theatre", label: "Forgotten theatres" },
  { id: "market", label: "Old markets" },
  { id: "street", label: "Unusual streets" },
  { id: "courtyard", label: "Hidden courtyards" },
  { id: "press", label: "Old printing presses" },
  { id: "bakery", label: "Old bakeries" },
];

export const hiddenPlaces: HiddenPlace[] = [
  {
    n: 1,
    slug: "rezabeebeh-gravestone",
    name: "The 1630 gravestone",
    kind: "cemetery",
    where: "Armenian Church of the Holy Nazareth, Armenian Street",
    coords: { lat: 22.5766, lng: 88.355 },
    line: "There is a grave in this city sixty years older than the city.",
    note: "Rezabeebeh's stone is dated 1630, six decades before Job Charnock tied up at Sutanuti. It is the strongest physical argument that a settled trading community was already here.",
    access: "Ask the caretaker. The churchyard is usually open in the morning.",
  },
  {
    n: 2,
    slug: "black-hole-brass-lines",
    name: "The brass lines outside the GPO",
    kind: "detail",
    where: "General Post Office, BBD Bagh",
    coords: { lat: 22.5751, lng: 88.3465 },
    line: "Thousands of people walk over the outline of the Black Hole every day.",
    note: "Brass strips set into the pavement on the north-east side mark the surveyed outline of the guardroom. There is no sign explaining them.",
    access: "Public pavement. Look down, on the Koilaghat Street side.",
  },
  {
    n: 3,
    slug: "chinese-kali-temple",
    name: "The Chinese Kali Temple",
    kind: "temple",
    where: "Matheswartala Road, Tangra",
    coords: { lat: 22.5544, lng: 88.3946 },
    line: "A Kali temple where the prasad is noodles.",
    note: "Run by the Hakka Chinese community of Tangra, with Chinese paper offerings burned alongside Bengali ritual. Chow mein and chop suey are offered at the shrine.",
    access: "Open daily. Shoes off, and be quiet if a service is running.",
  },
  {
    n: 4,
    slug: "nahoums",
    name: "Nahoum & Sons",
    kind: "bakery",
    where: "F-20 New Market",
    coords: { lat: 22.5629, lng: 88.3517 },
    line: "The last Jewish bakery in a city that once had thousands of Jews.",
    note: "Founded 1902 by Nahoum Israel Mordecai. The teak counters and glass cases are original. The Christmas plum cake queue is real and starts in November.",
    access: "Open daily except Sunday. Cash preferred.",
  },
  {
    n: 5,
    slug: "beth-el-caretakers",
    name: "Three synagogues, Muslim caretakers",
    kind: "building",
    where: "Pollock Street and Canning Street, Burrabazar",
    coords: { lat: 22.5747, lng: 88.3529 },
    line: "Fewer than twenty Jews remain, and the buildings are immaculate.",
    note: "Beth El, Magen David and Neveh Shalome are maintained by Muslim caretakers, several from families who have held the job for generations. They hold the keys.",
    access: "Ask at Magen David's gate; carry photo ID.",
  },
  {
    n: 6,
    slug: "sovabazar-thakur-dalan",
    name: "The 1757 thakur dalan",
    kind: "courtyard",
    where: "Sovabazar Rajbari",
    coords: { lat: 22.5989, lng: 88.3667 },
    line: "A Durga Puja that has not missed a year since the year of Plassey.",
    note: "Raja Nabakrishna Deb's pillared courtyard shrine, unrebuilt since the eighteenth century, and still used for the household Puja every autumn.",
    access: "Visitors are generally welcome during Puja. Ask at the gate.",
  },
  {
    n: 7,
    slug: "chitpur-jatra-posters",
    name: "The jatra poster walls",
    kind: "sign",
    where: "Beadon Street, off Rabindra Sarani",
    coords: { lat: 22.5903, lng: 88.3641 },
    line: "Hand-painted theatre posters, on the same walls, for a century.",
    note: "The jatra companies cast in early autumn and dispatch troupes across rural Bengal for the winter season. The posters go up on walls the trade has used since the 1920s.",
    access: "Public street. Best in September and October.",
  },
  {
    n: 8,
    slug: "sign-painters-chitpur",
    name: "The sign painters",
    kind: "sign",
    where: "Rabindra Sarani, north of Nakhoda Masjid",
    coords: { lat: 22.5822, lng: 88.3572 },
    line: "Shopfronts still hand-lettered on tin, to order, in three scripts.",
    note: "A handful of workshops still cut and letter enamel boards in Bengali, Hindi and English. Vinyl printing has taken most of the trade and they know it.",
    access: "Shutters up from about ten. Ask before photographing the work.",
  },
  {
    n: 9,
    slug: "metcalfe-hall-river-front",
    name: "Metcalfe Hall faces the wrong way",
    kind: "building",
    where: "Strand Road at Hare Street",
    coords: { lat: 22.5766, lng: 88.3448 },
    line: "Thirty Corinthian columns, pointed at the river rather than the road.",
    note: "Built in 1844 for a public library and designed to be arrived at by boat, which is why the grand front addresses the water and the road gets the side.",
    access: "ASI exhibition space. Hours are unreliable; the exterior always works.",
  },
  {
    n: 10,
    slug: "pareshnath-jain-temple",
    name: "Pareshnath Jain Temple",
    kind: "temple",
    where: "Badridas Temple Street, Maniktala",
    coords: { lat: 22.5871, lng: 88.3778 },
    line: "The most extravagant interior in Kolkata, and almost no visitors.",
    note: "Built in 1867 by the jeweller Rai Badridas Bahadur. Mirror mosaic, Belgian coloured glass, Venetian chandeliers, and a lamp said to have burned continuously since it opened.",
    access: "Open daily, roughly 6am–noon and 3–7pm. Shoes and leather off.",
  },
  {
    n: 11,
    slug: "kalighat-pat-lanes",
    name: "Where Kalighat pat was painted",
    kind: "street",
    where: "The lanes east of Kalighat temple",
    coords: { lat: 22.5209, lng: 88.3432 },
    line: "An entire school of modern Indian art started in these alleys, selling to pilgrims.",
    note: "From the 1830s, painters here produced fast, flat, brush-drawn watercolours for pilgrims, which turned satirical and mocked the westernised babu. Jamini Roy built a career on it.",
    access: "Public lanes. The paintings themselves are in the Victoria Memorial and Indian Museum.",
  },
  {
    n: 12,
    slug: "tiretta-bazar-breakfast",
    name: "Territi Bazar, 6am",
    kind: "market",
    where: "Off Bowbazar, central Kolkata",
    coords: { lat: 22.5745, lng: 88.3564 },
    line: "A Chinese breakfast market that exists for ninety minutes a day.",
    note: "Pork buns, fish ball soup, momos and sausages sold from baskets on the pavement by the last families of the old Chinatown. Finished by half past seven.",
    access: "Get there by 6:30. Cash only.",
  },
  {
    n: 13,
    slug: "old-china-bazar-street",
    name: "Old China Bazar Street",
    kind: "street",
    where: "Burrabazar",
    coords: { lat: 22.5772, lng: 88.3502 },
    line: "Named for a trade that moved out two centuries ago and never got renamed.",
    note: "The Chinese traders left for Tiretta Bazar and then Tangra. The street kept the name and became wholesale hardware and paper.",
    access: "Public street. Impassable to vehicles on a weekday.",
  },
  {
    n: 14,
    slug: "star-theatre-facade",
    name: "The Star Theatre facade",
    kind: "theatre",
    where: "Bidhan Sarani, Hatibagan",
    coords: { lat: 22.5951, lng: 88.3699 },
    line: "Built in 1883 on an actress's earnings, and named after somebody else.",
    note: "Binodini Dasi funded the theatre and was promised it would carry her name. It did not. She left the stage at twenty-three.",
    access: "Restored after the 1991 fire. Working cinema and stage.",
  },
  {
    n: 15,
    slug: "minerva-theatre",
    name: "Minerva Theatre",
    kind: "theatre",
    where: "Beadon Street",
    coords: { lat: 22.5921, lng: 88.3672 },
    line: "1893, nearly lost, and now staging again.",
    note: "One of the great houses of the Bengali commercial stage, closed and derelict for years, restored by the state and given to the Minerva Repertory.",
    access: "Check the repertory's programme.",
  },
  {
    n: 16,
    slug: "marble-palace-menagerie",
    name: "The Marble Palace menagerie",
    kind: "mansion",
    where: "Muktaram Babu Street, Chorbagan",
    coords: { lat: 22.5836, lng: 88.3617 },
    line: "A private zoo, in a north Kolkata house, since the 1850s.",
    note: "Peacocks in the garden and an aviary that has been kept by the same family for six generations, alongside 126 kinds of marble and two canvases attributed to Rubens.",
    access: "Free, but you need a permit from the West Bengal tourism office. Closed Monday and Thursday.",
  },
  {
    n: 17,
    slug: "rani-rashmoni-bari",
    name: "Rani Rashmoni's house",
    kind: "mansion",
    where: "Janbazar",
    coords: { lat: 22.5613, lng: 88.3572 },
    line: "The widow who built Dakshineswar lived here, and blockaded the river once.",
    note: "Rani Rashmoni ran a business empire, fought the Company in court, and once paid the fishing tax on the whole Hooghly and blocked shipping with her boats until the tax was withdrawn.",
    access: "Private, and partly a Puja house. The courtyard opens in October.",
  },
  {
    n: 18,
    slug: "lower-circular-road-cemetery",
    name: "Michael Madhusudan's grave",
    kind: "cemetery",
    where: "Lower Circular Road Cemetery",
    coords: { lat: 22.5459, lng: 88.3653 },
    line: "The poet wrote his own epitaph, and it asks you to stop.",
    note: "Madhusudan Dutt invented Bengali blank verse and the Bengali sonnet, died at forty-nine three days after his wife, and is buried under words he chose himself.",
    access: "Open daily. Ask at the gate for the plot.",
  },
  {
    n: 19,
    slug: "scottish-cemetery",
    name: "The Scottish Cemetery",
    kind: "cemetery",
    where: "Karaya Road",
    coords: { lat: 22.5397, lng: 88.3672 },
    line: "Ninety percent of the people buried in the Scottish cemetery are Indian.",
    note: "Opened 1820 for the Presbyterian community, and its later burials are overwhelmingly Bengali converts and their families. Restored by a Scottish–Indian project from 2008.",
    access: "Open weekdays. Ring the bell at the gate.",
  },
  {
    n: 20,
    slug: "greek-orthodox-church",
    name: "The Greek Orthodox Church",
    kind: "building",
    where: "Kalighat, near Rashbehari Avenue",
    coords: { lat: 22.5188, lng: 88.3494 },
    line: "There was a Greek community here, and this is what is left of it.",
    note: "The Church of the Transfiguration, moved from Amratala Street in the 1920s. Greek merchants traded in Bengal from the eighteenth century; the congregation is now tiny.",
    access: "Occasional services. Ask locally.",
  },
  {
    n: 21,
    slug: "portuguese-church-murgihata",
    name: "The Portuguese Church at Murgihata",
    kind: "building",
    where: "Brabourne Road",
    coords: { lat: 22.5757, lng: 88.3512 },
    line: "Called the chicken market church, and older than most of the city.",
    note: "The Cathedral of the Most Holy Rosary, built 1799 on an earlier chapel site, serving a Portuguese and Luso-Indian community that predates the Company's factory.",
    access: "Open for services and generally in the morning.",
  },
  {
    n: 22,
    slug: "bow-barracks",
    name: "Bow Barracks",
    kind: "street",
    where: "Bow Street, central Kolkata",
    coords: { lat: 22.5673, lng: 88.3574 },
    line: "Red-brick blocks built for First World War troops, and an Anglo-Indian Christmas that outclasses Park Street.",
    note: "Built around 1918 as barracks and never used as such. The Anglo-Indian community has lived here since, and makes its own wine for Christmas.",
    access: "A residential street. Go at Christmas, and be polite.",
  },
  {
    n: 23,
    slug: "college-street-binderies",
    name: "The binderies behind the stalls",
    kind: "press",
    where: "The lanes off College Street",
    coords: { lat: 22.5751, lng: 88.3661 },
    line: "The whole trade is on one street, from typesetting to resale.",
    note: "Publishers, printers, paper wholesalers and hand binderies occupy the buildings behind the book stalls. Some still sew signatures by hand.",
    access: "Working premises. Ask before entering or photographing.",
  },
  {
    n: 24,
    slug: "letterpress-shops",
    name: "The last letterpress shops",
    kind: "press",
    where: "Around Bowbazar and College Street",
    coords: { lat: 22.5701, lng: 88.3629 },
    line: "Bengali type, set by hand, in cases nobody makes any more.",
    note: "A handful of jobbing printers still keep Bengali metal type for wedding cards and invitations. The founts cannot be replaced when a sort wears out.",
    access: "Small shops with the shutters half up. Ask.",
  },
  {
    n: 25,
    slug: "putiram",
    name: "Putiram's morning",
    kind: "bakery",
    where: "Surya Sen Street, College Street",
    coords: { lat: 22.5757, lng: 88.3646 },
    line: "Since 1868, and finished by ten in the morning.",
    note: "Kochuri, radhaballavi and cholar dal, made and sold in a few hours. Generations of Presidency students have been late to lectures because of the queue.",
    access: "Before ten, or there is nothing left.",
  },
  {
    n: 26,
    slug: "paramount-sherbets",
    name: "Paramount's marble counter",
    kind: "bakery",
    where: "Bankim Chatterjee Street",
    coords: { lat: 22.5757, lng: 88.3639 },
    line: "A sherbet shop opened in 1918 that was a meeting point for revolutionaries.",
    note: "The daab sherbet recipe is said to have come from the scientist Prafulla Chandra Ray. Netaji drank here. The counter has not been changed.",
    access: "Open through the day. Cash.",
  },
  {
    n: 27,
    slug: "ahiritola-ghat",
    name: "Ahiritola Ghat at dawn",
    kind: "street",
    where: "North Kolkata riverfront",
    coords: { lat: 22.5934, lng: 88.3567 },
    line: "The best light on the river, and almost nobody there.",
    note: "A working ghat with swimmers, wrestlers at the akhara nearby, and a boat crossing. It is a fraction as busy as Mullick Ghat and photographs better.",
    access: "Public. Before seven in the morning.",
  },
  {
    n: 28,
    slug: "akharas",
    name: "The riverside akharas",
    kind: "courtyard",
    where: "Along the north Kolkata ghats",
    coords: { lat: 22.5951, lng: 88.3554 },
    line: "Mud-pit wrestling gyms, on the riverbank, at five in the morning.",
    note: "Kushti akharas have operated along these ghats for well over a century, mostly run by families originally from Bihar and Uttar Pradesh. The pits are earth, not mat.",
    access: "Early morning. Ask the ustad before watching.",
  },
  {
    n: 29,
    slug: "heritage-doors-north",
    name: "The doors of north Kolkata",
    kind: "detail",
    where: "The lanes of Jorasanko, Sovabazar and Bagbazar",
    coords: { lat: 22.5892, lng: 88.3641 },
    line: "Teak, brass, and a hundred and fifty years of nobody replacing them.",
    note: "Louvred shutters, brass knockers shaped as hands and lions, fanlights with coloured glass, and doorframes carved to a pattern the lane's carpenter used on every house.",
    access: "Public lanes. Photograph the door, not through it.",
  },
  {
    n: 30,
    slug: "rowaks",
    name: "The rowak",
    kind: "detail",
    where: "Every old house in the north",
    coords: { lat: 22.5964, lng: 88.3702 },
    line: "A raised front stoop that functioned as the neighbourhood's parliament.",
    note: "The rowak is a low platform at the front of a north Kolkata house. Generations of adda happened on them. Municipal rules and street widening have removed most.",
    access: "Look at the base of any older house on a north Kolkata lane.",
  },
  {
    n: 31,
    slug: "chhatu-babu-latu-babu-bari",
    name: "Chhatu Babu Latu Babur Bari",
    kind: "mansion",
    where: "Beadon Street",
    coords: { lat: 22.5903, lng: 88.3653 },
    line: "A bonedi bari Puja running since 1770, in a house most people walk past.",
    note: "The Deb family house. The Durga here is worshipped in the Harigouri form, and the rituals differ from the standard in ways the family will explain if you ask.",
    access: "The courtyard opens to visitors during Puja.",
  },
  {
    n: 32,
    slug: "jorasanko-hungarian-gallery",
    name: "The Hungarian gallery at Jorasanko",
    kind: "mansion",
    where: "Jorasanko Thakurbari",
    coords: { lat: 22.5852, lng: 88.3617 },
    line: "There is a Tagore promenade in Hungary, and this room explains why.",
    note: "Tagore was treated at the Balatonfüred sanatorium in 1926 and planted a tree there. The gallery on his Hungarian, Japanese and Chinese connections is almost always empty.",
    access: "Inside the museum. Closed Mondays.",
  },
  {
    n: 33,
    slug: "town-hall-basement-statues",
    name: "The statues in the Town Hall",
    kind: "building",
    where: "Esplanade Row West",
    coords: { lat: 22.5709, lng: 88.3446 },
    line: "Viceroys nobody wanted on a plinth, kept indoors.",
    note: "Statuary removed from public sites after independence was gathered here rather than destroyed, alongside the hall where J. C. Bose demonstrated radio in 1895.",
    access: "Kolkata history museum. Open most days.",
  },
  {
    n: 34,
    slug: "sealdah-first-tram",
    name: "Where the first tram started",
    kind: "street",
    where: "Sealdah to Armenian Ghat",
    coords: { lat: 22.5675, lng: 88.3705 },
    line: "24 February 1873, horse-drawn, and it failed within nine months.",
    note: "The first line ran three and a half kilometres to Armenian Ghat. A second attempt in 1880 stuck, and electrification in 1902 made it the first electric tramway in Asia.",
    access: "The route is now ordinary road. The Esplanade depot museum car is the closest you get.",
  },
  {
    n: 35,
    slug: "gwalior-monument",
    name: "The Gwalior Monument",
    kind: "building",
    where: "Near Prinsep Ghat, the Maidan",
    coords: { lat: 22.5586, lng: 88.3339 },
    line: "A bronze-clad cupola on the Maidan that almost nobody looks at.",
    note: "Built in 1847 for the British dead of the 1843 Gwalior campaign, and cast partly from captured guns. Locals call it the Pepper Pot.",
    access: "Public. Best at sunset, with Prinsep Ghat.",
  },
  {
    n: 36,
    slug: "kidderpore-fancy-market",
    name: "Fancy Market",
    kind: "market",
    where: "Kidderpore",
    coords: { lat: 22.5386, lng: 88.3221 },
    line: "A market that grew out of what came off the ships, and still does.",
    note: "Imported clothing, electronics, cosmetics and food arriving by routes nobody explains. It predates the customs regime it operates around.",
    access: "Late afternoon. Bargain hard.",
  },
  {
    n: 37,
    slug: "metiabruz-imambara",
    name: "The second Lucknow",
    kind: "building",
    where: "Metiabruz, south-west Kolkata",
    coords: { lat: 22.5262, lng: 88.2947 },
    line: "An exiled king built a small copy of his capital here, and the biryani is what survived.",
    note: "Wajid Ali Shah was moved to Metiabruz in 1856 with his court, musicians and kite-flyers. The Shahi Imambara and a distinctive Urdu culture remain.",
    access: "The Imambara is open; ask locally for directions.",
  },
  {
    n: 38,
    slug: "eau-chew",
    name: "Eau Chew",
    kind: "bakery",
    where: "Ganesh Chandra Avenue",
    coords: { lat: 22.5679, lng: 88.3559 },
    line: "A first-floor Chinese restaurant run by the same family since 1927.",
    note: "The Huang family, four generations in. Josephine noodles are named after a family member. There is no signage worth the name.",
    access: "Lunch and dinner. Find the staircase.",
  },
  {
    n: 39,
    slug: "nipponzan-myohoji",
    name: "The Japanese temple at the lake",
    kind: "temple",
    where: "Rabindra Sarobar, southern bank",
    coords: { lat: 22.5063, lng: 88.3618 },
    line: "A Nichiren Buddhist temple on a Kolkata lake, with drums at dawn.",
    note: "Founded in 1935 by the Nipponzan-Myohoji order. Almost always empty, and the quietest place in south Kolkata.",
    access: "Open daily. Shoes off. Drumming at dawn and dusk.",
  },
  {
    n: 40,
    slug: "kumartuli-armature-makers",
    name: "The armature makers",
    kind: "courtyard",
    where: "Kumartuli, north Kolkata",
    coords: { lat: 22.6006, lng: 88.3616 },
    line: "The people who decide whether the goddess will stand are not the ones whose names are on the studio.",
    note: "Bamboo and rice straw, bound with jute rope, months before any clay goes on. It is the least photographed and most structural stage of the whole thing.",
    access: "July and August, in the workshop lanes. Ask before photographing.",
  },
];

export function getHidden(slug: string) {
  return hiddenPlaces.find((h) => h.slug === slug);
}
