import type { Person } from "./types";

/** The second half of the portrait wall. */
export const peopleExtra: Person[] = [
  {
    slug: "bankim-chandra-chattopadhyay",
    photo: "person-bankim-chandra-chattopadhyay",
    name: "Bankim Chandra Chattopadhyay",
    bengali: "বঙ্কিমচন্দ্র চট্টোপাধ্যায়",
    born: 1838,
    died: 1894,
    field: "Novelist, essayist, civil servant",
    group: "literature",
    address: "Presidency College, then a district magistracy",
    coords: { lat: 22.5747, lng: 88.3634 },
    bornAt: "Kanthalpara, Naihati, north of Calcutta",
    kolkataConnection:
      "One of the first two graduates of the University of Calcutta in 1858, and editor of Bangadarshan, the magazine that professionalised Bengali prose.",
    contribution:
      "Wrote the first major Bengali novel, and inside one of them the song that became India's national song.",
    summary:
      "Wrote the first modern Bengali novel, spent thirty-three years as a colonial magistrate, and slipped Vande Mataram into a book about a famine.",
    body: [
      "He was one of the first two graduates the University of Calcutta produced, in 1858, and went straight into the Indian Civil Service as a deputy magistrate, where he stayed for thirty-three years. He disliked it and it constrained everything he wrote.",
      "Durgeshnandini in 1865 is usually called the first proper novel in Bengali. Kapalkundala, Bishabriksha and Krishnakanter Will followed, and with them a prose register that later writers could actually use. Before Bankim, Bengali prose was largely translation and tract.",
      "In 1872 he founded Bangadarshan, a monthly that carried his own serials, criticism and essays, and effectively created a Bengali literary public. Tagore, who was eleven when it started, said later that the whole family waited for it.",
      "Anandamath, in 1882, is a novel about the sannyasi rebellion during the Bengal famine of 1770, and it contains Vande Mataram. The song was adopted by the Swadeshi movement after 1905, became the anthem of the nationalist agitation, and was made the national song of India in 1950. The novel's politics are considerably more complicated than the song's use suggests, and have been argued about ever since.",
    ],
    quote: {
      text: "Vande Mataram.",
      source: "Anandamath, 1882",
    },
    works: [
      { title: "Durgeshnandini", year: "1865", note: "Usually called the first modern Bengali novel" },
      { title: "Bangadarshan", year: "1872", note: "The monthly that created a Bengali literary public" },
      { title: "Anandamath", year: "1882", note: "Contains Vande Mataram" },
      { title: "Krishnakanter Will", year: "1878", note: "The one critics rate highest" },
    ],
    locations: [
      { name: "Presidency University", note: "Where he studied, before Calcutta University examined him.", coords: { lat: 22.5747, lng: 88.3634 }, href: "/neighbourhoods/college-street" },
      { name: "Bankim Chatterjee Street", note: "Named for him, and the Indian Coffee House is on it.", coords: { lat: 22.5757, lng: 88.3639 } },
    ],
    life: [
      { year: "1838", what: "Born at Kanthalpara, Naihati." },
      { year: "1858", what: "Among the first graduates of the University of Calcutta." },
      { year: "1865", what: "Durgeshnandini." },
      { year: "1872", what: "Founds Bangadarshan." },
      { year: "1882", what: "Anandamath, and Vande Mataram." },
      { year: "1894", what: "Dies at Calcutta." },
    ],
  },
  {
    slug: "sarat-chandra-chattopadhyay",
    photo: "person-sarat-chandra-chattopadhyay",
    name: "Sarat Chandra Chattopadhyay",
    bengali: "শরৎচন্দ্র চট্টোপাধ্যায়",
    born: 1876,
    died: 1938,
    field: "Novelist",
    group: "literature",
    address: "Bhagalpur, Rangoon, then Howrah",
    coords: { lat: 22.5839, lng: 88.3425 },
    bornAt: "Debanandapur, Hooghly district",
    kolkataConnection:
      "Published almost everything through Calcutta houses, and became the most widely read Bengali novelist of the twentieth century from a house across the river at Samta, Howrah.",
    contribution:
      "Made the Bengali novel popular and put widows, prostitutes and the rural poor at the centre of it.",
    summary:
      "The most read Bengali novelist of the century, who wrote Devdas at twenty-one and refused to publish it for another dozen years.",
    body: [
      "He grew up poor, dropped out of college for want of fees, and spent thirteen years as a clerk in Rangoon. Almost all the work that made him famous was written or drafted in that period and published later, from Calcutta.",
      "Devdas was written in 1900, when he was twenty-four, and he sat on it until 1917. It has since been filmed at least twenty times in a dozen languages, which makes it probably the most adapted Indian novel there is.",
      "What distinguishes him from Bankim and Tagore is subject and register. He wrote about widows, about women who could not remarry, about prostitution, about village debt and caste, in a plain conversational Bengali that anyone literate could read. Srikanta, Palli Samaj, Pather Dabi.",
      "Pather Dabi, a novel about a revolutionary organisation, was banned by the government of Bengal in 1927. Tagore, who had reservations about the book, still argued publicly against the ban.",
      "He is the writer Bengali households actually owned. Tagore was admired; Sarat Chandra was read.",
    ],
    works: [
      { title: "Devdas", year: "1917", note: "Written 1900. Filmed more than twenty times." },
      { title: "Srikanta", year: "1917–1933", note: "Four parts, and the one he is judged on" },
      { title: "Pather Dabi", year: "1926", note: "Banned by the Bengal government in 1927" },
      { title: "Parineeta", year: "1914", note: "Filmed repeatedly, most recently in 2005" },
    ],
    locations: [
      { name: "Samta, Howrah", note: "His house across the river, now a museum.", coords: { lat: 22.4506, lng: 88.0464 } },
      { name: "College Street publishers", note: "Where almost everything of his was printed.", coords: { lat: 22.5747, lng: 88.365 }, href: "/neighbourhoods/college-street" },
    ],
    life: [
      { year: "1876", what: "Born at Debanandapur, Hooghly." },
      { year: "1900", what: "Writes Devdas, and shelves it." },
      { year: "1903", what: "Leaves for Rangoon as a clerk." },
      { year: "1917", what: "Devdas published. Srikanta begins." },
      { year: "1927", what: "Pather Dabi banned in Bengal." },
      { year: "1938", what: "Dies in Calcutta." },
    ],
  },
  {
    slug: "michael-madhusudan-dutt",
    photo: "person-michael-madhusudan-dutt",
    name: "Michael Madhusudan Dutt",
    bengali: "মাইকেল মধুসূদন দত্ত",
    born: 1824,
    died: 1873,
    field: "Poet, playwright",
    group: "literature",
    address: "Hindu College, then Kidderpore",
    coords: { lat: 22.5747, lng: 88.3634 },
    bornAt: "Sagardari, Jessore, now in Bangladesh",
    kolkataConnection:
      "Educated at Hindu College, converted at the Old Mission Church in 1843, and buried in the Lower Circular Road cemetery under an epitaph he wrote himself.",
    contribution:
      "Invented Bengali blank verse and the Bengali sonnet, and dragged the language into modern European form.",
    summary:
      "Tried to be an English poet, failed, came back to Bengali at thirty-four, and reinvented it in nine years.",
    body: [
      "At Hindu College he decided he would be an English poet, converted to Christianity in 1843 partly to that end, took the name Michael, and left for Madras. He published two volumes in English. They were ignored.",
      "He came back to Calcutta in 1856 and, at thirty-four, started writing in Bengali. What followed in nine years changed the language: Tilottama Sambhava, then Meghnad Badh Kavya in 1861, an epic in blank verse that had never existed in Bengali before, and the first Bengali sonnets.",
      "Meghnad Badh Kavya retells the Ramayana with Ravana's son as the tragic hero and Rama as something considerably less than heroic, which was a deliberate provocation and is still argued about.",
      "He lived expensively, went to Europe, ran out of money in Versailles, was rescued by Vidyasagar sending funds, qualified as a barrister and practised badly. He died at forty-nine in a Calcutta hospital, three days after his wife.",
      "The epitaph on his grave is his own, and it asks the passer-by to spare a tear for a poet lying in his mother's lap.",
    ],
    quote: {
      text: "Stop a while, traveller, if Mother Bengal claims thee for her son.",
      source: "His own epitaph, Lower Circular Road Cemetery",
    },
    works: [
      { title: "The Captive Ladie", year: "1849", note: "The English attempt, in Madras. Ignored." },
      { title: "Sharmistha", year: "1859", note: "The first original Bengali play on the Western model" },
      { title: "Meghnad Badh Kavya", year: "1861", note: "Bengali blank verse epic; Ravana's son as hero" },
      { title: "Chaturdashpadi Kabitabali", year: "1866", note: "The first Bengali sonnets" },
    ],
    locations: [
      { name: "Presidency University", note: "Hindu College, where he decided to be an English poet.", coords: { lat: 22.5747, lng: 88.3634 }, href: "/neighbourhoods/college-street" },
      { name: "Lower Circular Road Cemetery", note: "His grave, with the epitaph he wrote.", coords: { lat: 22.5459, lng: 88.3653 } },
    ],
    life: [
      { year: "1824", what: "Born at Sagardari, Jessore." },
      { year: "1843", what: "Converts at the Old Mission Church, takes the name Michael." },
      { year: "1856", what: "Returns to Calcutta and starts writing in Bengali." },
      { year: "1861", what: "Meghnad Badh Kavya." },
      { year: "1866", what: "The first Bengali sonnets." },
      { year: "1873", what: "Dies at forty-nine, three days after his wife." },
    ],
  },
  {
    slug: "prafulla-chandra-ray",
    photo: "person-prafulla-chandra-ray",
    name: "Prafulla Chandra Ray",
    bengali: "প্রফুল্ল চন্দ্র রায়",
    born: 1861,
    died: 1944,
    field: "Chemist, industrialist, teacher",
    group: "science",
    address: "Presidency College, and 91 Upper Circular Road",
    coords: { lat: 22.5747, lng: 88.3634 },
    bornAt: "Raruli-Katipara, Khulna, now in Bangladesh",
    kolkataConnection:
      "Taught chemistry at Presidency for a quarter of a century, and founded India's first pharmaceutical company in a Calcutta house with eight hundred rupees.",
    contribution:
      "Proved that Indian science could be industrial, and gave away most of what he earned doing it.",
    summary:
      "Discovered a stable mercurous nitrite, founded India's first pharmaceutical works, and lived in a college room on a fraction of his salary.",
    body: [
      "He took a doctorate at Edinburgh and came back to teach at Presidency College in 1889, where he stayed for twenty-seven years and taught, among others, Satyendra Nath Bose and Meghnad Saha.",
      "In 1896 he prepared a stable mercurous nitrite, which had been thought impossible, and published it in the Journal of the Asiatic Society. It made his international reputation.",
      "In 1901 he started Bengal Chemical and Pharmaceutical Works in a house on Upper Circular Road with eight hundred rupees of his own money. It was the first pharmaceutical company in India and it still exists. His argument was that a colony that could not manufacture would stay a colony.",
      "He wrote A History of Hindu Chemistry, arguing that Indian chemical practice had a documented tradition long predating European contact, and he wrote it partly as an act of nationalism.",
      "He lived in a room at the college, gave most of his salary to students and to famine relief, and died in 1944 in the middle of the Bengal famine, having spent his last years on relief work.",
    ],
    quote: {
      text: "Science can wait, swaraj cannot.",
      source: "Attributed, on why he spent so much time on famine relief",
    },
    works: [
      { title: "Mercurous nitrite", year: "1896", note: "A stable compound that was thought not to exist" },
      { title: "Bengal Chemical", year: "1901", note: "India's first pharmaceutical works, founded with ₹800" },
      { title: "A History of Hindu Chemistry", year: "1902", note: "Two volumes, and a nationalist argument" },
      { title: "Taught", year: "1889–1916", note: "S. N. Bose, Meghnad Saha, and a generation at Presidency" },
    ],
    locations: [
      { name: "Presidency University", note: "The Baker Laboratory, where he taught for twenty-seven years.", coords: { lat: 22.5747, lng: 88.3634 }, href: "/neighbourhoods/college-street" },
      { name: "Bengal Chemical, Maniktala", note: "Founded 1901, and still operating.", coords: { lat: 22.5871, lng: 88.3778 } },
    ],
    life: [
      { year: "1861", what: "Born in Khulna district." },
      { year: "1887", what: "Doctorate at Edinburgh." },
      { year: "1889", what: "Joins Presidency College." },
      { year: "1896", what: "Mercurous nitrite." },
      { year: "1901", what: "Founds Bengal Chemical with ₹800." },
      { year: "1944", what: "Dies during the Bengal famine, after years of relief work." },
    ],
  },
  {
    slug: "satyendra-nath-bose",
    photo: "person-satyendra-nath-bose",
    name: "Satyendra Nath Bose",
    bengali: "সত্যেন্দ্রনাথ বসু",
    born: 1894,
    died: 1974,
    field: "Physicist",
    group: "science",
    address: "Presidency College, then Calcutta University",
    coords: { lat: 22.5747, lng: 88.3634 },
    bornAt: "Goabagan Street, north Calcutta",
    kolkataConnection:
      "Born, schooled, taught and died in this city. He was writing the paper that made his name while teaching at Dhaka, and he spent the second half of his career back at Calcutta University.",
    contribution:
      "Derived Planck's law without classical assumptions, and half of quantum statistics is named after him.",
    summary:
      "Sent Einstein a paper in 1924 that had been rejected by a journal. Einstein translated it himself, and the boson is named for him.",
    body: [
      "He was born on Goabagan Street, topped his class at Hindu School and Presidency College, and was taught by Jagadish Chandra Bose and Prafulla Chandra Ray. Meghnad Saha was a classmate.",
      "In 1924, teaching at Dhaka, he wrote a short paper deriving Planck's radiation law purely by counting indistinguishable quantum states, without borrowing anything from classical electrodynamics. It was rejected by the Philosophical Magazine.",
      "He sent it to Einstein directly. Einstein recognised what it was, translated it into German himself, submitted it to the Zeitschrift für Physik with a note of endorsement, and then extended the method to matter. The result is Bose–Einstein statistics, and later the prediction of the Bose–Einstein condensate, achieved experimentally in 1995.",
      "Paul Dirac coined the word boson. Every particle that obeys those statistics, from the photon to the Higgs, carries the name of a Bengali physicist who never won a Nobel Prize.",
      "He came back to Calcutta University in 1945 as Khaira Professor. He was also a serious esraj player, wrote science in Bengali on principle, and served as president of the Bangiya Bijnan Parishad.",
    ],
    quote: {
      text: "Respected Sir, I have ventured to send you the accompanying article for your perusal.",
      source: "His letter to Einstein, June 1924",
    },
    works: [
      { title: "Planck's Law and the Hypothesis of Light Quanta", year: "1924", note: "Rejected, then translated by Einstein" },
      { title: "Bose–Einstein statistics", year: "1924–25", note: "One of the two fundamental statistics of quantum mechanics" },
      { title: "The boson", year: "1945", note: "Named by Dirac, after him" },
      { title: "Bangiya Bijnan Parishad", year: "1948", note: "Founded to publish science in Bengali" },
    ],
    locations: [
      { name: "Presidency University", note: "Where he studied under J. C. Bose and P. C. Ray.", coords: { lat: 22.5747, lng: 88.3634 }, href: "/neighbourhoods/college-street" },
      { name: "University of Calcutta, Rajabazar", note: "Khaira Professor of Physics from 1945.", coords: { lat: 22.5834, lng: 88.3736 } },
      { name: "Goabagan Street", note: "Where he was born, in north Calcutta.", coords: { lat: 22.5893, lng: 88.3661 } },
    ],
    life: [
      { year: "1894", what: "Born on Goabagan Street." },
      { year: "1915", what: "Tops the MSc at Calcutta University." },
      { year: "1924", what: "Sends the paper to Einstein, who translates it." },
      { year: "1945", what: "Khaira Professor at Calcutta University." },
      { year: "1974", what: "Dies in Calcutta." },
    ],
  },
  {
    slug: "mrinal-sen",
    photo: "person-mrinal-sen",
    name: "Mrinal Sen",
    bengali: "মৃণাল সেন",
    born: 1923,
    died: 2018,
    field: "Filmmaker",
    group: "cinema",
    address: "Bhowanipore, and the Coffee House",
    coords: { lat: 22.5273, lng: 88.3436 },
    bornAt: "Faridpur, now in Bangladesh",
    kolkataConnection:
      "Came to Calcutta in 1940 to study physics, joined the Indian People's Theatre Association, and made the city itself the subject of the Calcutta trilogy.",
    contribution:
      "Turned the camera on the audience, and made Calcutta's unemployment and anger the subject of Indian art cinema.",
    summary:
      "The third of the three: where Ray observed and Ghatak declaimed, Sen argued, and broke the fourth wall to do it.",
    body: [
      "He came from Faridpur to study physics, spent more time in the Imperial Library reading about cinema than in the laboratory, and joined the Communist Party's cultural wing. He worked as a medical representative and a sound technician before directing.",
      "Bhuvan Shome in 1969 is usually credited with starting the Indian New Wave. It was made cheaply, in Hindi, with Utpal Dutt, and it won the national award and made money, which changed what the Film Finance Corporation was willing to back.",
      "The Calcutta trilogy, Interview, Calcutta 71 and Padatik, is the work he is argued over. Interview has its lead address the camera and the audience directly; Calcutta 71 runs four stories across four decades of the same poverty. They are angry films made during the Naxalite period, in a city under curfew.",
      "Ek Din Pratidin in 1979 is the quieter masterpiece: a working daughter does not come home one night, and the family's respectability disintegrates over the hours of waiting.",
      "He and Ray argued in print, at length, in the Statesman, over what political cinema owed its audience. Both of them enjoyed it enormously.",
    ],
    quote: {
      text: "I am a private film-maker who makes public films.",
      source: "Attributed",
    },
    works: [
      { title: "Bhuvan Shome", year: "1969", note: "Usually credited with starting the Indian New Wave" },
      { title: "Interview", year: "1971", note: "Breaks the fourth wall; the lead addresses the audience" },
      { title: "Calcutta 71", year: "1972", note: "Four stories, four decades, one poverty" },
      { title: "Ek Din Pratidin", year: "1979", note: "A daughter does not come home. The quiet one." },
    ],
    locations: [
      { name: "Indian Coffee House", note: "Where the arguments with Ray were rehearsed.", coords: { lat: 22.5757, lng: 88.3639 }, href: "/neighbourhoods/college-street" },
      { name: "Nandan", note: "The state film centre he helped shape.", coords: { lat: 22.5399, lng: 88.3444 } },
    ],
    life: [
      { year: "1923", what: "Born at Faridpur." },
      { year: "1940", what: "Comes to Calcutta to study physics." },
      { year: "1969", what: "Bhuvan Shome." },
      { year: "1971", what: "Interview begins the Calcutta trilogy." },
      { year: "1979", what: "Ek Din Pratidin." },
      { year: "2018", what: "Dies in Kolkata, aged ninety-five." },
    ],
  },
  {
    slug: "subhas-chandra-bose",
    photo: "person-subhas-chandra-bose",
    name: "Subhas Chandra Bose",
    bengali: "সুভাষচন্দ্র বসু",
    born: 1897,
    died: 1945,
    field: "Nationalist leader",
    group: "freedom",
    address: "38/2 Elgin Road, Bhowanipore",
    coords: { lat: 22.5341, lng: 88.3474 },
    bornAt: "Cuttack, Odisha",
    kolkataConnection:
      "Studied at Presidency, was expelled for a fight with a professor, became Mayor of Calcutta in 1930, and escaped house arrest from his Elgin Road house in January 1941.",
    contribution:
      "Argued that independence would be taken rather than granted, and raised an army abroad to prove it.",
    summary:
      "Came fourth in the Indian Civil Service exam, resigned before taking up the post, and spent the rest of his life trying to remove the government he had qualified to serve.",
    body: [
      "He was expelled from Presidency College in 1916 after an incident involving a professor who had been abusing Indian students. He finished at Scottish Church College, went to Cambridge, placed fourth in the Indian Civil Service examination in 1920, and resigned in 1921 without taking up the appointment.",
      "He worked under C. R. Das, became Mayor of Calcutta in 1930, and was imprisoned repeatedly. He was elected Congress president in 1938 and again in 1939, the second time defeating Gandhi's candidate, and then resigned when the working committee made his position impossible.",
      "On the night of 16 January 1941, under police surveillance at 38/2 Elgin Road, he left the house in disguise in a German car driven by his nephew, and travelled by rail and on foot through Peshawar and Kabul to Moscow and then Berlin. The house is now a museum and the car is in it.",
      "In Southeast Asia he took command of the Indian National Army, formed from Indian prisoners of war, and declared a provisional government of free India. The INA fought alongside the Japanese at Imphal and Kohima and was defeated.",
      "He is believed to have died in an air crash at Taipei on 18 August 1945. Multiple commissions of inquiry have examined it and the belief has never been universally accepted in Bengal.",
    ],
    quote: {
      text: "Give me blood, and I shall give you freedom.",
      source: "Speech at Burma, July 1944",
    },
    works: [
      { title: "Mayor of Calcutta", year: "1930", note: "Elected while the nationalist movement was at its height" },
      { title: "Congress President", year: "1938, 1939", note: "Re-elected against Gandhi's candidate, then forced out" },
      { title: "The Great Escape", year: "1941", note: "Out of Elgin Road under surveillance, to Berlin via Kabul" },
      { title: "Indian National Army", year: "1943", note: "Commanded, with a women's regiment named for the Rani of Jhansi" },
    ],
    locations: [
      { name: "Netaji Bhawan, 38/2 Elgin Road", note: "The family house and the escape. Now a museum, with the car.", coords: { lat: 22.5341, lng: 88.3474 } },
      { name: "Presidency University", note: "Expelled in 1916 over a professor's treatment of Indian students.", coords: { lat: 22.5747, lng: 88.3634 }, href: "/neighbourhoods/college-street" },
      { name: "Shyambazar five-point crossing", note: "The equestrian statue, put up in 1969.", coords: { lat: 22.5993, lng: 88.3742 }, href: "/neighbourhoods/shyambazar" },
    ],
    life: [
      { year: "1897", what: "Born at Cuttack." },
      { year: "1916", what: "Expelled from Presidency College." },
      { year: "1921", what: "Resigns from the Indian Civil Service before taking it up." },
      { year: "1930", what: "Mayor of Calcutta." },
      { year: "1941", what: "Escapes Elgin Road in disguise." },
      { year: "1943", what: "Takes command of the Indian National Army." },
      { year: "1945", what: "Reported killed in an air crash at Taipei." },
    ],
  },
  {
    slug: "khudiram-bose",
    photo: "person-khudiram-bose",
    name: "Khudiram Bose",
    bengali: "ক্ষুদিরাম বসু",
    born: 1889,
    died: 1908,
    field: "Revolutionary",
    group: "freedom",
    address: "Jugantar, and the Muzaffarpur bombing",
    coords: { lat: 22.5747, lng: 88.365 },
    bornAt: "Habibpur, Midnapore",
    kolkataConnection:
      "Recruited through the Jugantar network run out of Calcutta, and the city's schools and student bodies made him the first mass martyr of the Bengali nationalist movement.",
    contribution:
      "Hanged at eighteen, and turned by public grief into the first symbol of armed resistance in Bengal.",
    summary:
      "Threw a bomb at the wrong carriage in Muzaffarpur, killed two English women, and went to the gallows at eighteen with his mouth reportedly shut.",
    body: [
      "He was recruited young into the revolutionary societies that grew out of the Swadeshi agitation after the 1905 partition of Bengal, and distributed the banned Sonar Bangla pamphlet as a schoolboy.",
      "In 1908 he and Prafulla Chaki were sent to Muzaffarpur to assassinate Douglas Kingsford, a Calcutta magistrate who had ordered floggings of young nationalists and had been transferred out of the city for his safety. On the night of 30 April they threw a bomb at a carriage they believed was his.",
      "It was not. Mrs Pringle Kennedy and her daughter were inside, and both were killed. Chaki shot himself when cornered. Khudiram was arrested, tried, and hanged at Muzaffarpur jail on 11 August 1908.",
      "He was eighteen. The Bengali press reported that he walked to the gallows smiling. Whether or not that is exactly true, the effect was enormous: schoolboys in Calcutta took to wearing dhotis with his name woven into the border, and a song about him is still sung.",
      "The killing of two women was and remains the difficult part of the story, and the honest accounts do not leave it out.",
    ],
    works: [
      { title: "Sonar Bangla", year: "1906", note: "Distributed the banned pamphlet as a schoolboy" },
      { title: "Muzaffarpur", year: "30 April 1908", note: "The bombing, and the wrong carriage" },
      { title: "Hanged", year: "11 August 1908", note: "At eighteen years and eight months" },
    ],
    locations: [
      { name: "College Street", note: "Where the student networks that recruited him operated.", coords: { lat: 22.5747, lng: 88.365 }, href: "/neighbourhoods/college-street" },
      { name: "Khudiram Anushilan Kendra", note: "The auditorium in the east of the city named for him.", coords: { lat: 22.4988, lng: 88.3729 } },
    ],
    life: [
      { year: "1889", what: "Born at Habibpur, Midnapore." },
      { year: "1905", what: "Joins the revolutionary societies after the partition of Bengal." },
      { year: "1908", what: "The Muzaffarpur bombing, on 30 April." },
      { year: "1908", what: "Hanged on 11 August, aged eighteen." },
    ],
  },
  {
    slug: "surya-sen",
    photo: "person-surya-sen",
    name: "Surya Sen",
    bengali: "সূর্য সেন",
    born: 1894,
    died: 1934,
    field: "Revolutionary, schoolteacher",
    group: "freedom",
    address: "Chittagong, and the Bengal revolutionary network",
    coords: { lat: 22.5747, lng: 88.365 },
    bornAt: "Noapara, Chittagong, now in Bangladesh",
    kolkataConnection:
      "Radicalised at Behrampore College and inside the Anushilan and Jugantar networks that ran out of Calcutta, and the raid he led was planned on a model those Calcutta societies had argued over for two decades.",
    contribution:
      "Led the Chittagong armoury raid, held a district for four days, and proved that armed action could be organised at scale.",
    summary:
      "A mathematics teacher who planned the Chittagong armoury raid in 1930, declared a provisional government, and held out in the hills for three years.",
    body: [
      "He taught mathematics at a school in Chittagong, which is where the name Masterda comes from, and recruited from his own students. The network he built was young, disciplined and largely teenage.",
      "On 18 April 1930 his group seized the police and auxiliary force armouries at Chittagong, cut the telegraph and rail links, and raised the flag. Sen read out a proclamation of a provisional revolutionary government of India. The raid deliberately echoed the Easter Rising.",
      "They failed to find the ammunition. Four days later the British attacked their position on Jalalabad Hill; twelve of the group were killed. The survivors dispersed into the villages, and the network kept operating for three years.",
      "Pritilata Waddedar, one of his recruits, led the attack on the Pahartali European Club in 1932 and took cyanide rather than be captured. Kalpana Datta was arrested and tried alongside Sen.",
      "He was betrayed, captured in February 1933, tortured, and hanged in January 1934. The official record of the state of his body at execution is not disputed.",
    ],
    works: [
      { title: "Chittagong armoury raid", year: "18 April 1930", note: "Armouries seized; a provisional government declared" },
      { title: "Jalalabad Hill", year: "22 April 1930", note: "Twelve of the group killed in the counter-attack" },
      { title: "The network", year: "1930–1933", note: "Kept operating from the villages for three years" },
      { title: "Executed", year: "12 January 1934", note: "After capture and torture" },
    ],
    locations: [
      { name: "College Street", note: "The Calcutta student networks his organisation grew out of.", coords: { lat: 22.5747, lng: 88.365 }, href: "/neighbourhoods/college-street" },
      { name: "Surya Sen Street", note: "Named for him, off College Street, with Kalika on the corner.", coords: { lat: 22.5751, lng: 88.3639 } },
    ],
    life: [
      { year: "1894", what: "Born at Noapara, Chittagong." },
      { year: "1918", what: "Joins the revolutionary movement while teaching mathematics." },
      { year: "1930", what: "The Chittagong armoury raid." },
      { year: "1933", what: "Betrayed and captured." },
      { year: "1934", what: "Hanged on 12 January." },
    ],
  },
  {
    slug: "raja-ram-mohan-roy",
    photo: "person-raja-ram-mohan-roy",
    name: "Raja Ram Mohan Roy",
    bengali: "রাজা রামমোহন রায়",
    born: 1772,
    died: 1833,
    field: "Reformer, scholar, publisher",
    group: "reform",
    address: "Maniktala, and the Brahmo Samaj",
    coords: { lat: 22.5871, lng: 88.3717 },
    bornAt: "Radhanagar, Hooghly district",
    kolkataConnection:
      "Moved to Calcutta in 1815 and spent the rest of his Indian life here: founding the Brahmo Sabha, co-founding Hindu College, publishing in three languages, and campaigning against sati.",
    contribution:
      "Got sati abolished, founded the Brahmo Samaj, and started the argument that becomes the Bengal Renaissance.",
    summary:
      "Called the father of modern India, largely because he was the first person to argue for reform in the reformers' own languages and win.",
    body: [
      "He read Sanskrit, Persian, Arabic, Bengali, English, Greek, Latin and Hebrew, and used all of them. His method was consistent: go back to the earliest texts of a tradition and show that the practice being defended is not in them.",
      "He applied it to sati. He watched his sister-in-law burn, campaigned for years in print and in petition, argued the scriptural case against it directly, and Bentinck's regulation abolishing it came in 1829. Orthodox opinion appealed to the Privy Council; Roy went to England partly to oppose the appeal, and it failed.",
      "He founded the Brahmo Sabha in 1828, which became the Brahmo Samaj: monotheist, anti-idolatry, anti-caste, and the intellectual home of the Tagores and a large part of the reforming middle class.",
      "He co-founded Hindu College in 1817 with David Hare, published Sambad Kaumudi in Bengali and Mirat-ul-Akhbar in Persian, and campaigned for press freedom, women's property rights and English scientific education.",
      "The Mughal emperor gave him the title Raja and sent him to England as an envoy. He died at Bristol in 1833 and is buried at Arnos Vale.",
    ],
    quote: {
      text: "Just and good government is the birthright of every people.",
      source: "Attributed",
    },
    works: [
      { title: "Hindu College", year: "1817", note: "Co-founded with David Hare. Becomes Presidency." },
      { title: "Sambad Kaumudi", year: "1821", note: "A Bengali weekly, and a press-freedom campaign" },
      { title: "Brahmo Sabha", year: "1828", note: "Becomes the Brahmo Samaj" },
      { title: "Abolition of sati", year: "1829", note: "Bentinck's regulation, after years of his campaigning" },
    ],
    locations: [
      { name: "Raja Ram Mohan Roy Memorial Museum", note: "85A Amherst Street, the house he lived in.", coords: { lat: 22.5806, lng: 88.3689 } },
      { name: "Presidency University", note: "Hindu College, which he co-founded in 1817.", coords: { lat: 22.5747, lng: 88.3634 }, href: "/neighbourhoods/college-street" },
    ],
    life: [
      { year: "1772", what: "Born at Radhanagar, Hooghly." },
      { year: "1815", what: "Settles in Calcutta." },
      { year: "1817", what: "Co-founds Hindu College." },
      { year: "1828", what: "Founds the Brahmo Sabha." },
      { year: "1829", what: "Sati abolished." },
      { year: "1833", what: "Dies at Bristol." },
    ],
  },
  {
    slug: "ishwar-chandra-vidyasagar",
    photo: "person-ishwar-chandra-vidyasagar",
    name: "Ishwar Chandra Vidyasagar",
    bengali: "ঈশ্বরচন্দ্র বিদ্যাসাগর",
    born: 1820,
    died: 1891,
    field: "Reformer, educator, publisher",
    group: "reform",
    address: "Sanskrit College, and Badurbagan",
    coords: { lat: 22.5757, lng: 88.3646 },
    bornAt: "Birsingha, Midnapore",
    kolkataConnection:
      "Principal of Sanskrit College, founder of the Metropolitan Institution, and the man who wrote the Bengali primer every child in the province learned to read from.",
    contribution:
      "Forced widow remarriage into law, opened Sanskrit education beyond brahmins, and fixed the Bengali alphabet.",
    summary:
      "Reformed the Bengali alphabet, legalised widow remarriage, opened Sanskrit College to all castes, and married his own son to a widow to prove the point.",
    body: [
      "Barnaparichay, his two-part Bengali primer of 1855, standardised the alphabet at fifty letters and is still, in revised form, how Bengali children learn to read. Almost nobody in the language has had that kind of reach.",
      "As principal of Sanskrit College he admitted non-brahmin students, which the institution had never done, and introduced English and Western philosophy into the curriculum on the argument that Sanskrit learning without them would fossilise.",
      "He argued the scriptural case for widow remarriage in two long pamphlets in 1855, and the Hindu Widows' Remarriage Act was passed in 1856. He then discovered that legality and practice are different things, spent his own money arranging and funding marriages, and married his son Narayan to a widow in 1870.",
      "He also campaigned against polygamy and child marriage, opened dozens of schools including girls' schools, and ran the Metropolitan Institution, later Vidyasagar College, as a self-funded alternative.",
      "He was formidably stubborn and fell out with almost every institution he worked for. He spent his last years largely among Santhal villagers at Karmatar, away from Calcutta.",
    ],
    quote: {
      text: "The widow's tears are not less bitter for being shed in silence.",
      source: "Adapted from his 1855 pamphlet on widow remarriage",
    },
    works: [
      { title: "Barnaparichay", year: "1855", note: "The Bengali primer. Still how children learn to read." },
      { title: "Widow remarriage pamphlets", year: "1855", note: "The scriptural case, in two parts" },
      { title: "Hindu Widows' Remarriage Act", year: "1856", note: "Passed after his campaign" },
      { title: "Metropolitan Institution", year: "1872", note: "Now Vidyasagar College" },
    ],
    locations: [
      { name: "Sanskrit College", note: "Where he was principal and opened admission beyond brahmins.", coords: { lat: 22.5757, lng: 88.3646 }, href: "/neighbourhoods/college-street" },
      { name: "Vidyasagar Smriti Mandir", note: "His Badurbagan house, now a memorial.", coords: { lat: 22.5789, lng: 88.3665 } },
      { name: "Vidyasagar Setu", note: "The second Hooghly bridge carries his name.", coords: { lat: 22.5566, lng: 88.3283 } },
    ],
    life: [
      { year: "1820", what: "Born at Birsingha, Midnapore." },
      { year: "1851", what: "Principal of Sanskrit College." },
      { year: "1855", what: "Barnaparichay, and the widow remarriage pamphlets." },
      { year: "1856", what: "The Hindu Widows' Remarriage Act passes." },
      { year: "1870", what: "Marries his son to a widow." },
      { year: "1891", what: "Dies in Calcutta." },
    ],
  },
  {
    slug: "ramakrishna-paramahamsa",
    photo: "person-ramakrishna-paramahamsa",
    name: "Ramakrishna Paramahamsa",
    bengali: "রামকৃষ্ণ পরমহংস",
    born: 1836,
    died: 1886,
    field: "Mystic, priest",
    group: "spirituality",
    address: "Dakshineswar Kali Temple",
    coords: { lat: 22.655, lng: 88.3576 },
    bornAt: "Kamarpukur, Hooghly district",
    kolkataConnection:
      "Spent thirty years as a priest in a small room at Dakshineswar, on the northern edge of the city, where the entire Calcutta intelligentsia came to argue with him.",
    contribution:
      "Practised several religions in turn and reported that they arrived at the same place, and through Vivekananda that argument left Bengal.",
    summary:
      "A village priest with almost no formal education who became the teacher of the most educated men in Calcutta, largely by refusing to argue in their terms.",
    body: [
      "Gadadhar Chattopadhyay came to Dakshineswar in 1855 with his elder brother, who had been engaged as priest for Rani Rashmoni's new temple. When his brother died, he took the post, and stayed for thirty years in a room about three metres square in the north-west corner of the courtyard.",
      "What he did there was experimental in a literal sense. He practised Tantric sadhana under Bhairavi Brahmani, Advaita Vedanta under Totapuri, and then, in turn, Islam and Christianity, each as a full discipline, and reported in each case that the destination was the same.",
      "He taught in parables, in village Bengali, using kitchen and fishing and money-lending imagery, and he refused almost every abstraction the Calcutta rationalists brought him. Keshab Chandra Sen of the Brahmo Samaj publicised him, and the educated young began arriving.",
      "One of them was a sceptical Scottish Church College student named Narendranath Datta, who came to test him and asked whether he had seen God. Ramakrishna said yes, as clearly as he saw him, and more intensely. That student became Vivekananda.",
      "Mahendranath Gupta recorded the conversations verbatim in a diary, published as the Kathamrita, which is one of the very few direct records of a religious teacher's daily speech anywhere.",
    ],
    quote: {
      text: "As many faiths, so many paths.",
      source: "Recorded in the Kathamrita",
    },
    works: [
      { title: "Thirty years at Dakshineswar", year: "1855–1886", note: "In a room three metres square" },
      { title: "The Kathamrita", year: "1902–1932", note: "His conversations, recorded verbatim by M." },
      { title: "Taught Vivekananda", year: "1881–1886", note: "Who took the argument to Chicago in 1893" },
      { title: "Sarada Devi", year: "1872 onwards", note: "His wife, and the Holy Mother of the movement" },
    ],
    locations: [
      { name: "Dakshineswar Kali Temple", note: "His room is in the north-west corner of the courtyard.", coords: { lat: 22.655, lng: 88.3576 }, href: "/heritage/dakshineswar-kali-temple" },
      { name: "Belur Math", note: "Where his relics were interred, across the river.", coords: { lat: 22.632, lng: 88.355 }, href: "/heritage/belur-math" },
      { name: "Cossipore garden house", note: "Where he spent his final months.", coords: { lat: 22.6155, lng: 88.3717 } },
    ],
    life: [
      { year: "1836", what: "Born at Kamarpukur." },
      { year: "1855", what: "Comes to Dakshineswar; becomes priest the following year." },
      { year: "1866", what: "Practises Islam as a full discipline." },
      { year: "1881", what: "Narendranath Datta first visits." },
      { year: "1886", what: "Dies at Cossipore." },
    ],
  },
  {
    slug: "uttam-kumar",
    photo: "person-uttam-kumar",
    name: "Uttam Kumar",
    bengali: "উত্তম কুমার",
    born: 1926,
    died: 1980,
    field: "Actor, producer",
    group: "culture",
    address: "Bhowanipore, and the Tollygunge studios",
    coords: { lat: 22.4956, lng: 88.3465 },
    bornAt: "Ahiritola, north Calcutta",
    kolkataConnection:
      "Born in Ahiritola, worked as a clerk at the Port Commissioners' office while auditioning, and became the Mahanayak of an industry entirely based in this city.",
    contribution:
      "Carried Bengali popular cinema for three decades, and made the matinee idol a Bengali institution.",
    summary:
      "Arun Kumar Chatterjee of Ahiritola, who failed in seven straight films, then did not fail again for thirty years.",
    body: [
      "He was born in Ahiritola in north Calcutta and worked as a clerk at the Calcutta Port Commissioners' office, auditioning in his own time. His first seven films flopped so completely that the industry gave him the nickname Flop Master General.",
      "Basu Paribar in 1952 turned it around, and Agnipariksha in 1954, opposite Suchitra Sen, made the pairing that defined Bengali romantic cinema. They made more than thirty films together, and for a generation of Bengalis the two of them simply are the cinema.",
      "He was better than the vehicles. Satyajit Ray cast him twice, in Nayak in 1966, where he plays a film star on a train interrogating his own success, and in Chiriyakhana. Nayak is a performance of real self-exposure and he agreed to it knowingly.",
      "He produced, he sang, he ran a studio, and he tried and failed to break into Hindi cinema, which never suited him.",
      "He collapsed on set and died in 1980, at fifty-three. The Tollygunge metro station is named Mahanayak Uttam Kumar, and the crowd at his funeral shut the city.",
    ],
    works: [
      { title: "Agnipariksha", year: "1954", note: "The film that made the Uttam–Suchitra pairing" },
      { title: "Saptapadi", year: "1961", note: "The most quoted Bengali romance there is" },
      { title: "Nayak", year: "1966", note: "For Ray. A star interrogating his own success, on a train." },
      { title: "Mahanayak", year: "1960s", note: "The title, awarded by the public rather than anyone official" },
    ],
    locations: [
      { name: "Mahanayak Uttam Kumar metro", note: "Tollygunge. The station carries his name.", coords: { lat: 22.4956, lng: 88.3465 }, href: "/neighbourhoods/tollygunge" },
      { name: "Ahiritola", note: "Where he was born, in the north.", coords: { lat: 22.5934, lng: 88.3567 } },
      { name: "Technicians' Studio, Tollygunge", note: "Where most of it was shot.", coords: { lat: 22.4972, lng: 88.3436 } },
    ],
    life: [
      { year: "1926", what: "Born Arun Kumar Chatterjee at Ahiritola." },
      { year: "1948", what: "First film. Six more flops follow." },
      { year: "1954", what: "Agnipariksha, with Suchitra Sen." },
      { year: "1966", what: "Nayak, for Satyajit Ray." },
      { year: "1980", what: "Dies at fifty-three." },
    ],
  },
  {
    slug: "sourav-ganguly",
    photo: "person-sourav-ganguly",
    name: "Sourav Ganguly",
    bengali: "সৌরভ গঙ্গোপাধ্যায়",
    born: 1972,
    field: "Cricketer, captain, administrator",
    group: "culture",
    address: "Behala, and Eden Gardens",
    coords: { lat: 22.5645, lng: 88.3433 },
    bornAt: "Behala, south-west Kolkata",
    kolkataConnection:
      "Born and still living in Behala, and the only Indian captain whose home ground crowd could reliably be heard on television.",
    contribution:
      "Made the Indian cricket team believe it could win away from home, and built the side that later won everything.",
    summary:
      "Scored a hundred on debut at Lord's, captained India out of a match-fixing crisis, and is called Dada by roughly ninety million people.",
    body: [
      "He came from a wealthy Behala family, was left-handed only because he used his brother's kit, and was dropped from the Indian side in 1992 with a reputation for being difficult.",
      "He came back at Lord's in 1996 and scored 131 on Test debut, then 136 in the next match at Trent Bridge. With Sachin Tendulkar he formed an opening partnership in one-day cricket that held records for a decade.",
      "He took the captaincy in 2000, immediately after the match-fixing scandal had gutted the team's credibility. What he did with it is the thing he is actually remembered for: he backed young players, he insisted India compete abroad, and he made a point of not being deferential. Taking his shirt off on the Lord's balcony in 2002 was crude and entirely deliberate.",
      "The side he built, with Dravid, Kumble, Sehwag, Yuvraj, Zaheer and Harbhajan, is the one that went on to win the 2007 and 2011 world titles under other captains.",
      "He later captained and mentored Kolkata Knight Riders, presided over the Cricket Association of Bengal, and served as president of the Board of Control for Cricket in India from 2019 to 2022.",
    ],
    quote: {
      text: "I have always believed that if you back a young player, he will play for you.",
      source: "Attributed",
    },
    works: [
      { title: "131 on Test debut at Lord's", year: "1996", note: "Then 136 at Trent Bridge in the next match" },
      { title: "Captain of India", year: "2000–2005", note: "Took over immediately after the match-fixing crisis" },
      { title: "NatWest final, Lord's", year: "2002", note: "The shirt. Crude, deliberate, and never forgotten." },
      { title: "President, BCCI", year: "2019–2022", note: "After the Cricket Association of Bengal" },
    ],
    locations: [
      { name: "Eden Gardens", note: "His home ground, and the loudest in India.", coords: { lat: 22.5645, lng: 88.3433 }, href: "/neighbourhoods/esplanade" },
      { name: "Behala", note: "Where he was born and still lives.", coords: { lat: 22.4989, lng: 88.3115 } },
    ],
    life: [
      { year: "1972", what: "Born at Behala." },
      { year: "1996", what: "131 on Test debut at Lord's." },
      { year: "2000", what: "Takes the India captaincy after the match-fixing scandal." },
      { year: "2002", what: "The NatWest final at Lord's." },
      { year: "2019", what: "Elected president of the BCCI." },
    ],
  },
];
