import type { Story } from "./types";

/**
 * Stories about people rather than places. The city as the people in it.
 * These are composites drawn from documented practice and reporting, not
 * interviews with named individuals, and they are written as such.
 */
export const peopleStories: Story[] = [
  {
    slug: "forty-years-of-tea",
    title: "The man who has sold tea here for forty years",
    standfirst:
      "Seven rupees, a clay cup you break afterwards, and a bench that has heard everything.",
    author: "Editorial",
    published: "2026-03-14",
    readingMinutes: 6,
    tags: ["people", "adda", "north kolkata"],
    scene: "streetfood",
    body: [
      { kind: "para", text: "The stove is a clay oven with a coal fire in it, and it has been lit at half past four every morning for four decades. The kettle is aluminium and has been replaced twice. The bench outside is the original, and it has been repaired so many times that no part of it is." },
      { kind: "para", text: "The cups come from Kumartuli, or from a potter in Howrah when Kumartuli is busy with the goddess. They are thrown on a wheel, fired once, never glazed. Unglazed clay is porous, which is why the tea tastes faintly of wet earth and why the cup can only be used once." },
      { kind: "heading", text: "The economics" },
      { kind: "para", text: "Seven rupees a cup. The bhaar costs between eighty paise and a rupee twenty depending on the season and how the potters' order book looks. Milk, sugar, tea dust, coal. On a good day, three hundred cups; in the monsoon, more, because everybody stands under the awning." },
      { kind: "para", text: "Nobody in this trade has a lease. The stall occupies a few square feet of pavement under an arrangement with the building behind, the local councillor's office and, historically, whoever was collecting. It has survived four clearance drives." },
      { kind: "heading", text: "What the bench is for" },
      { kind: "para", text: "The tea is not the product. The bench is. Between about four in the afternoon and eight in the evening it holds a rotating group of men, some of whom have been coming since before the shop had a roof, arguing about the derby, the metro extension, a serial nobody admits to watching, and a municipal drainage decision from 1998." },
      { kind: "quote", text: "They come for the tea for the first month. After that they come for the bench." },
      { kind: "para", text: "This is what adda is, at the level it actually operates: not the Coffee House, which is the famous version, but a few square feet of pavement where the same twelve people turn up for forty years." },
      { kind: "heading", text: "The succession problem" },
      { kind: "para", text: "The son has a job in an office in Sector V and will not take it on. This is the ordinary arithmetic of the trade: a salaried job in the IT belt pays several times what a pavement stall does, with a chair and air conditioning." },
      { kind: "para", text: "There are fewer stalls than there were, and the ones that close are not replaced by other stalls. They are replaced by nothing, or by a franchise counter selling the same tea in a paper cup for forty rupees, which is not the same transaction at all." },
      { kind: "para", text: "The clay cup is the part people notice going. What actually goes with it is the bench." },
    ],
  },
  {
    slug: "the-last-hours-before-immersion",
    title: "The last few hours before immersion",
    standfirst:
      "Dashami afternoon at Babughat, when a fortnight of work is queued up on lorries waiting to go into the river.",
    author: "Editorial",
    published: "2026-03-02",
    readingMinutes: 7,
    tags: ["durga puja", "river", "people"],
    scene: "river",
    body: [
      { kind: "para", text: "By two in the afternoon the lorries are backed up along Strand Road. Each carries one idol, lashed upright with rope, surrounded by the twenty or thirty people from the committee who have spent a year raising the money for it." },
      { kind: "para", text: "There is a police pass system, a queue, and a crane. There is also a great deal of standing about, which is the part nobody photographs." },
      { kind: "heading", text: "Sindoor khela, an hour earlier" },
      { kind: "para", text: "Before the lorry, at the pandal, married women mark the idol with vermilion and then each other, and feed her sweets for the journey. It is loud and it is not solemn. By the time the figure is on the truck a good proportion of the crowd is covered in red powder." },
      { kind: "para", text: "The last thing that happens at the pandal is that the priest performs a rite of departure, and somebody unbolts the frame from the platform it has stood on for five days." },
      { kind: "heading", text: "At the ghat" },
      { kind: "para", text: "The crane takes the larger figures. The smaller ones go in by hand, carried out into the water by eight or ten men who then hold on until the clay starts to go." },
      { kind: "para", text: "It goes faster than people expect. Straw and unfired clay in moving water is a matter of minutes. The paint is off first, then the surface, and then the shape is gone and there is a bamboo frame in the current." },
      { kind: "quote", text: "You spend a year on the committee and about ninety seconds on this part." },
      { kind: "heading", text: "What comes out again" },
      { kind: "para", text: "Under the current rules the frames are recovered. Contractors with grappling hooks work through the night pulling bamboo, straw and the metal armatures back out, because a riverbed full of structural steel is a navigation problem as well as a pollution one." },
      { kind: "para", text: "Water-based, lead-free colours are required now. Compliance is uneven and improving, and the argument about it is conducted every year in the same newspapers." },
      { kind: "para", text: "By two in the morning the ghat is mostly empty. There is a lot of marigold in the water, some of it moving downstream, and the road is being swept. In Kumartuli the lanes are silent, and will be until January." },
    ],
  },
  {
    slug: "the-bookshop-that-survived",
    title: "The bookshop that survived three generations",
    standfirst:
      "A stall six feet wide on College Street, opened in 1948 by a man who arrived with nothing, and still trading.",
    author: "Editorial",
    published: "2026-02-20",
    readingMinutes: 6,
    tags: ["books", "college street", "people"],
    scene: "collegestreet",
    body: [
      { kind: "para", text: "The stall is about six feet wide and eleven deep, if you count the part that folds out onto the pavement at eight in the morning and folds back at nine at night. There is no sign. There has never been a sign." },
      { kind: "para", text: "It was opened in 1948 by a man who had crossed from Faridpur the previous year with a trunk and no trade, and who started by selling secondhand school textbooks on a sheet on the ground." },
      { kind: "heading", text: "The index" },
      { kind: "para", text: "There is no catalogue and there never has been. You describe what you want, sometimes badly, and the current owner, who is the founder's grandson, goes into the stack. Eleven minutes is about the average." },
      { kind: "para", text: "The system is spatial and it is entirely in his head: Bengali fiction along the back at chest height, English paperbacks in the front left, academic titles in the plastic crates, and anything unusual in the bundle behind the ladder that only he is allowed to touch." },
      { kind: "quote", text: "My grandfather knew where everything was. My father knew where everything was. I know where everything is. Nobody has written it down." },
      { kind: "heading", text: "Three collapses" },
      { kind: "para", text: "The trade nearly went three times. In the 1970s, when the university closed for long stretches during the Naxalite period and the student customers stopped coming. In the 1990s, when cable television arrived. And from about 2010, when online sellers made new books cheaper than his secondhand ones." },
      { kind: "para", text: "What saved it each time was the same thing: the stock nobody else has. A 1962 Bengali translation of a Russian novel, a mimeographed thesis, a little magazine from 1974 with four poems in it that were never collected." },
      { kind: "heading", text: "The fourth generation" },
      { kind: "para", text: "The daughter is at Presidency, two hundred metres up the road, reading comparative literature. She helps at the stall on Sundays and has started keeping a spreadsheet, which her father regards with visible suspicion." },
      { kind: "para", text: "Whether she takes it on is not settled. What is settled is that when a stall closes on this street it is not replaced by another stall." },
    ],
  },
  {
    slug: "a-tram-drivers-morning",
    title: "A tram driver's morning",
    standfirst:
      "Signing on at five, a compressor that takes four minutes to build pressure, and a route that no longer exists.",
    author: "Editorial",
    published: "2026-01-28",
    readingMinutes: 6,
    tags: ["trams", "people", "loss"],
    scene: "tram",
    body: [
      { kind: "para", text: "You sign on at the depot at five. The car has been standing all night and the first thing is the compressor, which takes about four minutes to build enough air for the brakes, and which you listen to rather than watch, because you can hear when it is unhappy." },
      { kind: "para", text: "Then the pole goes up onto the wire, and you check it seats properly, because a pole that comes off at a junction is twenty minutes of your morning and a queue of traffic behind you." },
      { kind: "heading", text: "What driving one is like" },
      { kind: "para", text: "There is a controller, which is a handle with notches, and a brake. That is essentially it. There is no steering, which sounds easy and is the opposite: you cannot avoid anything. Everything you do, you do with speed, and you do it early." },
      { kind: "para", text: "Fifteen kilometres an hour on a dedicated median. Cars cut across the track at every gap. In the rain the rail is slick and the stopping distance doubles, and the median floods before the road does because it is lower." },
      { kind: "quote", text: "A bus driver can swerve. I can only be slower, earlier." },
      { kind: "heading", text: "The passengers" },
      { kind: "para", text: "Schoolchildren in the afternoon, in the same seats. Office workers in the morning who read the whole way and look up at exactly the right stop without checking. Old men who get on at one end and off at the other and are clearly not going anywhere." },
      { kind: "para", text: "The conductor knew everybody. That is not nostalgia; it is a function of a vehicle that runs the same fixed route at the same slow speed for thirty years." },
      { kind: "heading", text: "Signing off" },
      { kind: "para", text: "Most of the routes went quietly. A road-widening scheme suspends the service, the tracks get tarred over during the works, and the suspension is never lifted. Nobody announces anything. The route simply stops appearing on the board." },
      { kind: "para", text: "The depot has more drivers than cars. Some have been redeployed to buses, some to the depot itself, and some are still signing on, at five, for a service that runs one route." },
      { kind: "para", text: "Melbourne kept its trams. So did Lisbon, Prague, Amsterdam and San Francisco. All of them were told at some point that trams were obsolete." },
    ],
  },
  {
    slug: "the-family-behind-the-sweet-shop",
    title: "The family behind an old sweet shop",
    standfirst:
      "Four generations, one counter, and eight weeks a year when the whole business changes.",
    author: "Editorial",
    published: "2026-01-12",
    readingMinutes: 6,
    tags: ["food", "people", "north kolkata"],
    scene: "streetfood",
    body: [
      { kind: "para", text: "The shop is a counter, a set of steel trays, a marble slab at the back and a room behind that where the actual work happens. There are no tables. There have never been tables. You eat standing up, off a sal leaf, and you leave." },
      { kind: "para", text: "The chhena is made every morning: milk split with whey, drained, and then kneaded on the marble by hand. How long you knead it is the entire craft. Too little and it will not hold; too much and the sweet squeaks when you bite it, which is a fault you will be told about." },
      { kind: "heading", text: "The eight weeks" },
      { kind: "para", text: "From about the middle of December to the middle of February the shop becomes a different shop. Nolen gur, date-palm jaggery, arrives from the tappers, and every sweet on the counter gets a winter version." },
      { kind: "para", text: "The jolbhora is the one people queue for: a sandesh with liquid gur sealed inside it, so it collapses in the mouth. It cannot be made in advance and it cannot be made in March." },
      { kind: "quote", text: "Eleven months we sell sweets. Two months we sell the season." },
      { kind: "heading", text: "The supply problem" },
      { kind: "para", text: "The sap only runs properly when the nights are genuinely cold, which in Bengal means a window of about eight weeks. Tapping is skilled, nocturnal, badly paid work, and the number of shiuli is falling every year." },
      { kind: "para", text: "What is sold as nolen gur outside the season is cane jaggery with a flavouring. Everyone in the trade knows this. Some of them sell it anyway." },
      { kind: "heading", text: "Who takes it on" },
      { kind: "para", text: "The founder's great-grandson runs it now and did an MBA first, which the older customers found funny and which turned out to matter: the shop has a cold chain, a second outlet, and ships nolen gur sweets by air in January." },
      { kind: "para", text: "The kneading is still done by hand on the same slab, by two men who have been doing it for thirty years, because nobody has built a machine that can tell when to stop." },
    ],
  },
  {
    slug: "why-this-street-is-called",
    title: "Why this street is called what it is called",
    standfirst:
      "Bowbazar, Chorbagan, Hatibagan, Sonagachi. The city's street names are a record of trades, gardens, elephants and things nobody will explain.",
    author: "Editorial",
    published: "2025-12-19",
    readingMinutes: 7,
    tags: ["streets", "history", "language"],
    scene: "rooftops",
    body: [
      { kind: "para", text: "Kolkata has two street-name systems running at once. There is the official one, renamed in waves after independence, and there is the one people use, which is older and largely descriptive." },
      { kind: "para", text: "Rabindra Sarani is Chitpur. Mother Teresa Sarani is Park Street. Jawaharlal Nehru Road is Chowringhee. In each case the official name is on the sign and the older one is in the taxi driver's head." },
      { kind: "heading", text: "The trade names" },
      { kind: "para", text: "The Company's settlement plan put trades into their own quarters, and the names are the record of it. Kumartuli is the potters' quarter, from kumor. Sutanuti was the cotton-yarn market. Colootola is where the oil pressers, kolus, worked. Ahiritola was the cowherds', from ahir." },
      { kind: "para", text: "Almost every one of those trades has left except the potters, who are still in Kumartuli, still using river clay, three hundred years on." },
      { kind: "heading", text: "The garden names" },
      { kind: "para", text: "Bagbazar is the garden market. Chorbagan, where Marble Palace stands, is the thieves' garden, and nobody has ever satisfactorily explained why. Hatibagan is the elephant garden, and there were elephants: the Nawab of Bengal's, stabled there before the city closed in around them." },
      { kind: "quote", text: "Half the city is named after a garden that has not existed for two hundred years." },
      { kind: "heading", text: "The awkward ones" },
      { kind: "para", text: "Bowbazar is a corruption of Bahu Bazar, the bride's market, said to be named for a house Bishwanath Motilal gave his daughter-in-law. Sonagachi, the city's largest red-light district, is usually traced to a Sufi saint called Sona Gazi, which may or may not be true and is repeated because the alternative etymologies are worse." },
      { kind: "para", text: "Then there is the city's own name. Kalikata was one of the three villages, and the most durable reading traces it to Kalikshetra, the ground of Kali, after the shrine at Kalighat. Job Charnock did not name it. It was already called that." },
      { kind: "heading", text: "What renaming does and does not do" },
      { kind: "para", text: "Renaming Dalhousie Square to BBD Bagh, for the three men who shot the inspector-general of prisons in the Writers' Building in 1930, worked. People use it." },
      { kind: "para", text: "Renaming Park Street did not. The rule appears to be that a name sticks if the thing it replaces was itself imposed, and does not if the old name was simply what the street was." },
    ],
  },
  {
    slug: "the-artist-who-still-works-by-hand",
    title: "The artist who still makes Durga by hand",
    standfirst:
      "No moulds, no fibreglass, no shortcuts, and a workshop that turns down more commissions than it takes.",
    author: "Editorial",
    published: "2025-11-22",
    readingMinutes: 7,
    tags: ["kumartuli", "craft", "people"],
    scene: "kumartuli",
    body: [
      { kind: "para", text: "There are moulds now. A face can be cast, a torso can be pulled from fibreglass, and a large studio taking forty commissions in a season cannot do it any other way. This workshop takes eleven, and every face is modelled." },
      { kind: "para", text: "The argument for the mould is straightforward: it is faster, it is consistent, and it is what a committee working to a deadline wants. The argument against is that a moulded face is the same face, and it will be the same face next year." },
      { kind: "heading", text: "What hand modelling actually means" },
      { kind: "para", text: "The armature and the two clay coats are the same either way. The difference is the last week. The bele mati surface is worked wet, and the face, the fingers and the fall of the sari are cut and pressed with a handful of bamboo tools and a thumb." },
      { kind: "para", text: "The proportions come from the shilpa texts by way of a family tradition, which is to say approximately. The eyes are set slightly high, the chin is narrow, and the ten arms have to read as arms rather than spokes, which is harder than it sounds and is where most workshops fail." },
      { kind: "quote", text: "A mould gives you last year's goddess. I would rather make a worse one that is this year's." },
      { kind: "heading", text: "Who is still doing it" },
      { kind: "para", text: "A handful of studios in the lanes, and the number is not growing. Fibreglass is lighter, survives transport to Dubai and New Jersey, and does not crack in a wet September." },
      { kind: "para", text: "Clay is also getting harder to obtain. Riverbank extraction is increasingly restricted, prices rise every year, and the entel mati from the right stretch of the Hooghly is a specific commodity, not just mud." },
      { kind: "heading", text: "The eyes" },
      { kind: "para", text: "On Mahalaya he fasts, bathes and does the eyes in one sitting: three strokes each, the third eye on the forehead, and the pupils last. It takes a few minutes. Everything else in the process can be argued about and this cannot." },
      { kind: "para", text: "Ten days later the figure is in the river and there is nothing left of five weeks of work. He has never regarded this as a problem, and finds the question slightly odd." },
      { kind: "para", text: "In January he starts binding straw." },
    ],
  },
];
