import type { TimelineEntry } from "./types";

export const timeline: TimelineEntry[] = [
  {
    year: 1495,
    title: "The villages exist",
    era: "pre-colonial",
    body: "Bipradas Pipilai's Manasa-Vijaya names Kalikata on the Hooghly. Sutanuti is a cotton-yarn market and Gobindapur a fishing settlement. There is no city, but there are three villages and a temple.",
  },
  {
    year: 1690,
    title: "Job Charnock lands at Sutanuti",
    era: "company",
    body: "An East India Company agent establishes a trading post on the east bank, on a bend deep enough for ships and defensible from three sides by water and marsh. Kolkata's High Court ruled in 2003 that he should no longer be called the founder.",
    pivotal: true,
  },
  {
    year: 1698,
    title: "Three villages bought",
    era: "company",
    body: "The Company acquires zamindari rights over Sutanuti, Gobindapur and Kalikata from the Sabarna Roy Choudhury family. Fort William begins going up on the Gobindapur site.",
  },
  {
    year: 1756,
    title: "Siraj-ud-Daulah takes the city",
    era: "company",
    body: "The young Nawab of Bengal storms Fort William over the Company's unauthorised fortifications. The Black Hole episode dates from this night, and its scale has been disputed by historians ever since.",
  },
  {
    year: 1757,
    title: "Plassey",
    era: "company",
    body: "Clive defeats Siraj-ud-Daulah at Palashi, largely through the defection of Mir Jafar. The Company acquires effective control of Bengal's revenue, and the character of the settlement changes from trading post to capital.",
    pivotal: true,
  },
  {
    year: 1772,
    title: "Capital of British India",
    era: "company",
    body: "Warren Hastings moves the administration from Murshidabad. For the next 139 years Calcutta is the capital of British India and the second city of the empire.",
    pivotal: true,
  },
  {
    year: 1784,
    title: "The Asiatic Society",
    era: "company",
    body: "William Jones founds it to study Asia systematically. Three years later he argues publicly that Sanskrit, Greek and Latin share a common ancestor, which founds comparative linguistics.",
  },
  {
    year: 1814,
    title: "The Indian Museum",
    era: "company",
    body: "Established from the Asiatic Society's collection under Nathaniel Wallich. The oldest museum in Asia.",
  },
  {
    year: 1817,
    title: "Hindu College",
    era: "renaissance",
    body: "Founded by Rammohan Roy, David Hare and others to teach European sciences and letters in English. It becomes Presidency College, and its students become the Bengal Renaissance.",
    pivotal: true,
  },
  {
    year: 1829,
    title: "Sati abolished",
    era: "renaissance",
    body: "Bentinck's regulation follows years of campaigning by Rammohan Roy. The reform movement it belongs to also produces the Brahmo Samaj, widow remarriage and the first serious argument for women's education in the province.",
  },
  {
    year: 1861,
    title: "Rabindranath Tagore born at Jorasanko",
    era: "renaissance",
    body: "Into a family already at the centre of the reform movement, in a house that ran its own theatre, magazines and arguments.",
  },
  {
    year: 1873,
    title: "The first tram",
    era: "raj",
    body: "A horse-drawn tramway opens between Sealdah and Armenian Ghat on 24 February. It closes within the year, restarts in 1880, and is electrified in 1902 as the first electric tram network in Asia.",
  },
  {
    year: 1905,
    title: "The Partition of Bengal",
    era: "raj",
    body: "Curzon divides the province along religious lines. The Swadeshi movement that answers it is the first mass nationalist agitation in India. The partition is reversed in 1911, but the method is not forgotten.",
    pivotal: true,
  },
  {
    year: 1911,
    title: "The capital moves to Delhi",
    era: "raj",
    body: "Announced at the Delhi Durbar, partly to escape Bengali nationalism. The same year, Mohun Bagan beats East Yorkshire Regiment 2–1 barefoot in the IFA Shield final, and the two events are discussed together for a century.",
    pivotal: true,
  },
  {
    year: 1913,
    title: "Tagore wins the Nobel",
    era: "raj",
    body: "The first non-European laureate in literature, for Gitanjali. He renounces the resulting knighthood six years later, after Jallianwala Bagh.",
  },
  {
    year: 1943,
    title: "Famine, and a bridge",
    era: "raj",
    body: "The Bengal famine kills between two and three million people in a year when the province's food supply was adequate. In the same February, Howrah Bridge opens without ceremony, and the first thing across it is a tram.",
    pivotal: true,
  },
  {
    year: 1946,
    title: "Direct Action Day",
    era: "independence",
    body: "Communal violence over four days in August kills several thousand people in the city. It hardens the case for partition on both sides.",
  },
  {
    year: 1947,
    title: "Partition",
    era: "independence",
    body: "The Radcliffe Line divides Bengal. Millions cross. Refugee colonies form on the southern and eastern edges of Calcutta over the following decade and permanently reshape the city's geography, politics and cinema.",
    pivotal: true,
  },
  {
    year: 1955,
    title: "Pather Panchali",
    era: "independence",
    body: "Satyajit Ray's first film, shot on weekends over two and a half years, opens in Calcutta and wins at Cannes the following year. Indian cinema acquires an international critical reputation.",
    pivotal: true,
  },
  {
    year: 1967,
    title: "Naxalbari",
    era: "modern",
    body: "A peasant uprising in north Bengal gives its name to a movement that, within three years, has the city's student politics, its universities and its police in open conflict. The period runs to the mid-seventies and marks the generation that lived it.",
  },
  {
    year: 1977,
    title: "The Left Front takes power",
    era: "modern",
    body: "It governs West Bengal continuously for thirty-four years, the longest-serving democratically elected communist government anywhere. Operation Barga redistributes tenancy rights to sharecroppers; industrial investment leaves.",
    pivotal: true,
  },
  {
    year: 1984,
    title: "India's first metro",
    era: "modern",
    body: "The Kolkata Metro opens on 24 October between Esplanade and Bhowanipore, 3.4 kilometres, seventeen years after work began. It is the first underground railway in India.",
  },
  {
    year: 2001,
    title: "Calcutta becomes Kolkata",
    era: "modern",
    body: "The official English spelling is changed to match the Bengali pronunciation the city had always used. Almost nobody speaking Bengali noticed a change, because there had not been one.",
  },
  {
    year: 2011,
    title: "The Left Front falls",
    era: "modern",
    body: "Mamata Banerjee's Trinamool Congress wins, ending thirty-four years. The trigger is a land-acquisition fight at Singur and Nandigram over industrial projects on farmland.",
  },
  {
    year: 2021,
    title: "Durga Puja on the UNESCO list",
    era: "modern",
    body: "Inscribed in December on the Representative List of the Intangible Cultural Heritage of Humanity, the first festival in India to be listed. The citation notes its scale, its public art, and its collapsing of class and religious boundaries.",
    pivotal: true,
  },
  {
    year: 2024,
    title: "The trams stop",
    era: "modern",
    body: "The state announces it will retain a single heritage route of what was once thirty-seven. The case is in the High Court, and 151 years of continuous operation is, for now, effectively over.",
  },
];

export const eras: { id: TimelineEntry["era"]; label: string; span: string }[] = [
  { id: "pre-colonial", label: "Before the city", span: "to 1690" },
  { id: "company", label: "The Company", span: "1690–1857" },
  { id: "renaissance", label: "The Renaissance", span: "1817–1905" },
  { id: "raj", label: "The Raj", span: "1858–1947" },
  { id: "independence", label: "Partition & after", span: "1946–1965" },
  { id: "modern", label: "Modern Kolkata", span: "1966–now" },
];
