import type { Neighbourhood } from "../types";

export const central: Neighbourhood[] = [
  {
    slug: "bbd-bagh",
    name: "BBD Bagh",
    bengali: "বি বা দী বাগ",
    alsoKnownAs: "Dalhousie Square",
    zone: "central",
    tagline: "The square the British ran India from, renamed for three men who shot someone in it.",
    knownFor: "Colonial administration, the Writers' Building, the tank",
    coords: { lat: 22.5726, lng: 88.3487 },
    bestHour: "Sunday morning, when the offices are shut and you can see the buildings",
    summary:
      "Dalhousie Square was the administrative centre of British India. It is now BBD Bagh, named for the three revolutionaries who walked into the Writers' Building in 1930 and shot the inspector-general of prisons.",
    body: [
      "The square is built around Lal Dighi, a tank that predates the city and supplied its drinking water. Around it the East India Company and then the Raj put everything that mattered: the secretariat, the post office, the treasury, the bank, the telegraph office, the church.",
      "The density of nineteenth-century public architecture here is not matched anywhere else in Asia. The Writers' Building runs the whole north side. The General Post Office, with its Corinthian dome, sits on the site of the original Fort William. St. Andrew's Kirk, the Currency Building, the Standard Life building, the Royal Insurance building: it is a catalogue of a century of imperial confidence in brick and stucco.",
      "On 8 December 1930, Benoy Basu, Badal Gupta and Dinesh Gupta walked into the Writers' Building corridors in European dress and shot Colonel N. S. Simpson. The square was renamed for them after independence: Benoy–Badal–Dinesh Bagh.",
      "On a weekday it is a traffic disaster and one of the densest office districts in India. On a Sunday it is nearly silent, and you can stand at the tank and see the whole thing.",
    ],
    buildings: [
      { name: "Writers' Building", note: "1777, refaced 1889. The seat of Bengal's government for two centuries.", href: "/heritage/writers-building" },
      { name: "General Post Office", note: "1868. Built on the site of the original Fort William.", href: "/heritage/general-post-office" },
      { name: "St. John's Church", note: "1787. The city's second-oldest church, with Job Charnock's mausoleum.", href: "/heritage/st-johns-church" },
      { name: "Currency Building", note: "1833. Restored and now an exhibition space." },
      { name: "St. Andrew's Kirk", note: "1818. The Scots put a spire on it taller than St. John's, deliberately." },
      { name: "Lal Dighi", note: "The tank at the centre. Older than the city around it." },
    ],
    eats: [
      { name: "Anadi Cabin", where: "Esplanade, ten minutes south", note: "Mughlai paratha since 1925." },
      { name: "K.C. Das", where: "Esplanade", note: "Nobin Chandra's descendants. Rosogolla at the counter." },
      { name: "The Dalhousie office lunch stalls", where: "Lanes off the square, 1–3pm", note: "Rice, dal, fish, on a steel plate, for very little." },
    ],
    figures: [
      { name: "Benoy, Badal and Dinesh", note: "The three who raided the Writers' Building in 1930. The square carries their names." },
      { name: "Warren Hastings", note: "Moved the capital here from Murshidabad in 1772." },
      { name: "Job Charnock", note: "His mausoleum is in St. John's churchyard, made of Pallavaram gneiss." },
    ],
    thingsToSee: [
      { name: "The Writers' reflection in Lal Dighi", note: "From the south side of the tank. The shot everyone misses by standing too close." },
      { name: "Job Charnock's mausoleum", note: "St. John's churchyard. The stone is now called charnockite, after him." },
      { name: "The GPO dome", note: "Corinthian, on the footprint of the original fort. Brass markers show the Black Hole site." },
      { name: "Sunday morning", note: "The offices shut and the square becomes legible." },
    ],
    plates: ["rooftops", "victoria", "collegestreet"],
    photos: ["writers-building", "gpo", "st-johns-church"],
    walk: [
      { stop: "Mahakaran metro", minutes: 0, note: "Come up into the square." },
      { stop: "Writers' Building", minutes: 4, note: "Exterior only. Walk the length of it." },
      { stop: "Lal Dighi", minutes: 8, note: "The tank. Stand on the south side." },
      { stop: "General Post Office", minutes: 14, note: "The dome, and the Black Hole markers." },
      { stop: "St. John's Church", minutes: 20, note: "Charnock's mausoleum in the yard." },
      { stop: "Currency Building", minutes: 28, note: "Restored. Check what is on." },
    ],
    sounds: [
      "Typewriters, until surprisingly recently",
      "Crows over the tank",
      "A tram bell on the Esplanade loop",
      "Absolute quiet, on a Sunday",
    ],
    scene: "rooftops",
    photo: "bbd-bagh",
  },
  {
    slug: "esplanade",
    name: "Esplanade & the Maidan",
    bengali: "ময়দান",
    zone: "central",
    tagline: "A thousand acres of grass, cleared in 1758 to give the guns a clear shot.",
    knownFor: "The Maidan, trams, Eden Gardens, everything meeting everything",
    coords: { lat: 22.5645, lng: 88.3512 },
    bestHour: "6am, or an hour before sunset",
    summary:
      "The lung: an enormous field cleared for artillery fields of fire, now holding cricket, football, horses and the entire city's exercise.",
    body: [
      "After 1757 the East India Company built a new Fort William and cleared the jungle and villages around it so the guns would have a clear field. The clearing was never built on, and it is now roughly a thousand acres of open ground in the centre of a city of fifteen million.",
      "It holds the Eden Gardens cricket ground, the Royal Calcutta Turf Club, Mohun Bagan and East Bengal, dozens of informal cricket pitches, grazing goats and horses, and at six in the morning several thousand people walking in circles.",
      "Mohun Bagan beat East Yorkshire Regiment 2–1 barefoot in the 1911 IFA Shield final on this ground, and the political weight of that result is still being discussed.",
      "Esplanade at the north end is the transport knot: the tram depot, the bus terminus, the metro interchange, and New Market a few minutes east. Fort William itself is a working army installation and closed; the star-shaped plan is visible from the air and from nowhere else.",
      "In the evening the whole eastern edge fills with jhalmuri, phuchka and tea, and the Victoria Memorial floodlights come on behind it.",
    ],
    buildings: [
      { name: "Shaheed Minar", note: "1828, built for David Ochterlony. Renamed for the martyrs in 1969." },
      { name: "Eden Gardens", note: "1864. The largest cricket ground in India and the loudest." },
      { name: "Fort William", note: "1781. A working army base; the star plan is not visible from the ground." },
      { name: "New Market", note: "1874. Sir Stuart Hogg Market, and still called Hogg Market by everyone." },
      { name: "Esplanade tram depot", note: "The last of the network, and the Tram World museum car." },
    ],
    eats: [
      { name: "Nizam's", where: "Hogg Street, New Market", note: "The claimed birthplace of the kathi roll, 1932." },
      { name: "Anadi Cabin", where: "Esplanade", note: "Mughlai paratha since 1925." },
      { name: "K.C. Das", where: "Esplanade", note: "Rosogolla, from the family that invented it." },
      { name: "Jhalmuri on the Maidan", where: "Anywhere along the eastern edge", note: "Shaken in a tin, in a paper cone." },
    ],
    figures: [
      { name: "Shibdas Bhaduri", note: "Captained Mohun Bagan, barefoot, in the 1911 IFA Shield final." },
      { name: "David Ochterlony", note: "The Shaheed Minar was his column before it was anybody else's." },
    ],
    thingsToSee: [
      { name: "The Maidan at six in the morning", note: "Several thousand people walking, and nine cricket matches at once." },
      { name: "The heritage tram", note: "From Esplanade depot. Check it is running before you go." },
      { name: "A derby at Eden or Salt Lake", note: "Mohun Bagan against East Bengal. Nothing prepares you." },
      { name: "Horse carriages on Queens Way", note: "Manes dyed pink. A genuinely strange survival." },
    ],
    storySlugs: ["the-last-tram"],
    plates: ["victoria", "tram", "streetfood"],
    photos: ["shaheed-minar", "tram-esplanade", "maidan"],
    walk: [
      { stop: "Esplanade", minutes: 0, note: "Tram depot, bus terminus, and the top of the Maidan." },
      { stop: "Shaheed Minar", minutes: 6, note: "1828, and older than the Nelson Column reference suggests." },
      { stop: "Eden Gardens", minutes: 15, note: "From the outside unless there is a match." },
      { stop: "Prinsep Ghat", minutes: 30, note: "1841 Palladian portico on the river. Sunset spot." },
      { stop: "Victoria Memorial", minutes: 45, note: "Walk back east across the grass." },
    ],
    sounds: [
      "Nine or ten cricket matches at once, all overlapping",
      "Horse hooves on Queens Way",
      "A whistle from a football coaching camp at dawn",
      "The last tram out of Esplanade depot",
    ],
    scene: "victoria",
    photo: "esplanade",
  },
  {
    slug: "park-street",
    name: "Park Street",
    bengali: "পার্ক স্ট্রিট",
    alsoKnownAs: "Mother Teresa Sarani",
    zone: "central",
    tagline: "The street that taught Kolkata how to dine after dark.",
    knownFor: "Restaurants, jazz history, Christmas",
    coords: { lat: 22.5527, lng: 88.352 },
    bestHour: "December evenings",
    summary:
      "Once the street where Calcutta went out. Still the street where Kolkata goes out, with roughly the same restaurants and considerably less jazz.",
    body: [
      "It was Burial Ground Road in the eighteenth century, which tells you where the cemetery came first. By the 1960s and 70s it was the centre of the city's nightlife, and the live music was serious: Trincas, Blue Fox, Moulin Rouge, and a circuit that produced Usha Uthup and Pam Crain.",
      "Most of the bands went in the 1980s. The restaurants stayed, and several of them are almost unchanged: Peter Cat since 1975, Mocambo since 1956, Trincas since 1959, Flurys since 1927, Oly Pub since 1947.",
      "This is deliberate rather than lazy. The menus, the waiters' uniforms and the lighting have been held still on purpose, and a large part of the appeal is that a Kolkata family can order the same thing their grandparents ordered at the same table.",
      "Officially it is Mother Teresa Sarani. Nobody has ever called it that.",
      "At Christmas the whole street is arched with lights, closed to traffic for stretches, and Bow Barracks nearby holds the older Anglo-Indian celebration. It is the most crowded and the best week of the year here.",
    ],
    buildings: [
      { name: "South Park Street Cemetery", note: "1767. Eight acres of enormous tombs.", href: "/heritage/south-park-street-cemetery" },
      { name: "Asiatic Society", note: "1784. William Jones founded it, and it holds manuscripts nobody else has." },
      { name: "Park Mansions", note: "1910. Art Nouveau brick, and the best facade on the street." },
      { name: "Bow Barracks", note: "Anglo-Indian housing from the First World War. Homemade wine at Christmas." },
    ],
    eats: [
      { name: "Peter Cat", where: "18 Park Street", note: "Chelo kebab since 1975. Queue on the pavement." },
      { name: "Mocambo", where: "Park Street", note: "Since 1956. Devilled crab and the prawn cocktail." },
      { name: "Trincas", where: "Park Street", note: "Since 1959. Live music most nights, still." },
      { name: "Flurys", where: "Park Street", note: "Since 1927. Breakfast, and the rum ball in December." },
      { name: "Oly Pub", where: "Park Street", note: "Since 1947. Beef steak upstairs, and nothing has changed." },
      { name: "Kusum Rolls", where: "Park Street", note: "The consensus best kathi roll in the city." },
    ],
    figures: [
      { name: "Usha Uthup", note: "Started at Trincas in the 1960s in a Kanjeevaram sari and never left the city." },
      { name: "Pam Crain", note: "The voice of Park Street jazz for three decades." },
      { name: "Sir William Jones", note: "Founded the Asiatic Society, and is buried a few hundred metres away." },
    ],
    thingsToSee: [
      { name: "The lights, third week of December", note: "End to end, and the street closed to traffic in stretches." },
      { name: "South Park Street Cemetery", note: "Silent ten metres inside the gate. Read the ages on the stones." },
      { name: "Trincas on a weeknight", note: "The last of the live circuit, and cheaper than the weekend." },
      { name: "Bow Barracks at Christmas", note: "The older, quieter, better celebration." },
    ],
    plates: ["streetfood", "victoria", "rooftops"],
    photos: ["park-street-night", "south-park-street-cemetery", "chelo-kebab"],
    walk: [
      { stop: "Park Street metro", minutes: 0, note: "Come up on the north side." },
      { stop: "Flurys", minutes: 3, note: "Breakfast, since 1927." },
      { stop: "Oxford Bookstore", minutes: 5, note: "Cha Bar upstairs." },
      { stop: "Peter Cat", minutes: 8, note: "Queue on the pavement. Chelo kebab." },
      { stop: "Trincas", minutes: 10, note: "Live music most nights, still." },
      { stop: "South Park Street Cemetery", minutes: 18, note: "Cross Rawdon Street. Completely silent inside." },
    ],
    sounds: [
      "A brass band outside a wedding at the Park Hotel",
      "Waiters calling orders through a service hatch",
      "Carols from a school choir in the third week of December",
      "Taxi horns at the Camac Street crossing",
    ],
    scene: "streetfood",
    photo: "park-street",
  },
  {
    slug: "bowbazar",
    name: "Bowbazar",
    bengali: "বউবাজার",
    zone: "central",
    tagline: "Gold, teeth and the Chinese breakfast market, on one road.",
    knownFor: "Jewellers, dentists, Tiretta Bazar, kochuri at dawn",
    coords: { lat: 22.5686, lng: 88.3617 },
    bestHour: "Six in the morning, at Tiretta Bazar",
    summary:
      "A road of goldsmiths and dentists that also holds the last of the old Chinese quarter and one of the best breakfasts in India.",
    body: [
      "Bow Barracks is not here; Bowbazar is a corruption of Bahu Bazar, the bride's market, said to be named for a house Bishwanath Motilal gave his daughter-in-law. The road runs east from BBD Bagh towards Sealdah and is one of the oldest commercial streets in the city.",
      "Two trades dominate. Goldsmiths, mostly from Bengal's Sekra caste, work in tiny first-floor workshops making to order, and the jewellery trade here supplies a large part of eastern India. And dentists, dozens of them, in a concentration nobody has ever satisfactorily explained.",
      "Tiretta Bazar, at the western end, is what remains of the original Chinatown, before the community moved east to Tangra in the twentieth century. The breakfast market runs from about six in the morning: pork buns, fish ball soup, momos, sausages, sold from baskets on the pavement. It is finished by half past seven.",
      "The quarter has also been the site of repeated Metro tunnelling subsidence since 2019, which has damaged and demolished houses and remains a live and bitter civic dispute.",
    ],
    buildings: [
      { name: "Tiretta Bazar", note: "The old Chinese quarter. Sea Ip and Toong On temples are nearby." },
      { name: "Bowbazar goldsmiths' lanes", note: "First-floor workshops, working to order, with the shutters half up." },
      { name: "Sealdah Station", note: "East along the road. Where the first tram line started in 1873." },
    ],
    eats: [
      { name: "Tiretta Bazar breakfast market", where: "Off Bowbazar, 6–7:30am", note: "Pork buns, fish ball soup, momos. Gone by eight." },
      { name: "Sharma Tea House", where: "Bowbazar", note: "Kochuri and cholar dal at dawn." },
      { name: "Chacha's Hotel", where: "Bowbazar", note: "Mughlai paratha and mutton curry, at a shared table." },
    ],
    figures: [
      { name: "Tong Achew", note: "The first recorded Chinese settler in Bengal, who set up a sugar mill in the 1780s." },
    ],
    thingsToSee: [
      { name: "Tiretta Bazar at six", note: "Twenty minutes of it, then it is over for the day." },
      { name: "A goldsmith at work", note: "Blowpipe, charcoal, and a bench that has not changed in a century." },
      { name: "Sea Ip Church", note: "One of the surviving Chinese temples in the old quarter." },
    ],
    plates: ["streetfood", "rooftops", "collegestreet"],
    photos: ["bowbazar", "sweet-shop", "hand-rickshaw"],
    walk: [
      { stop: "Central metro", minutes: 0, note: "Come up onto Bowbazar." },
      { stop: "Tiretta Bazar", minutes: 6, note: "Before 7:30am or there is nothing to see." },
      { stop: "The goldsmiths' lanes", minutes: 14, note: "Look up. The work is on the first floor." },
      { stop: "Sharma Tea House", minutes: 20, note: "Kochuri." },
      { stop: "College Street", minutes: 30, note: "North. The books start at Colootola." },
    ],
    sounds: [
      "Blowpipes and small hammers on the first floor",
      "Hakka and Bengali across a pavement basket",
      "Dentists' drills, with the door open",
    ],
    scene: "streetfood",
    photo: "bowbazar",
  },
  {
    slug: "burrabazar",
    name: "Burrabazar",
    bengali: "বড়বাজার",
    zone: "central",
    tagline: "The largest wholesale market in eastern India, and the loudest.",
    knownFor: "Wholesale everything, Marwari trade, Posta",
    coords: { lat: 22.5786, lng: 88.3543 },
    bestHour: "Weekday mornings, and brace yourself",
    summary:
      "Not a bazaar but a district of them: textiles, spices, paper, hardware, chemicals, sold wholesale from buildings that have been trading since the eighteenth century.",
    body: [
      "Burra Bazar means the big market, and it is: several square kilometres of wholesale trade north-west of BBD Bagh, running down to the river at Posta. It began as a yarn market in the seventeenth century, before the Company arrived, and it has never stopped.",
      "The trade is largely Marwari, from Rajasthan, along with Gujarati, Bihari and Bengali houses, and much of it operates on credit and reputation rather than paperwork. Streets specialise: Cotton Street, Canning Street, Old China Bazar Street, Posta for potatoes and onions, Mullick Street for perfume.",
      "It is exceptionally dense. Handcarts and porters move most of the goods because vehicles cannot get through, and a labourer carrying two hundred kilos on his head is an ordinary sight.",
      "The quarter also holds a set of remarkable Jain and Rajasthani temples, almost invisible from the street. The Pareshnath Jain Temple at Maniktala, a little north, is the most extravagant building in the city and almost nobody outside the community visits it.",
    ],
    buildings: [
      { name: "Pareshnath Jain Temple", note: "1867. Mirror mosaic, Belgian glass, and a lamp that has burned since it opened." },
      { name: "Satyanarayan Park", note: "The market's one open space, and the wholesale flower trade's overflow." },
      { name: "Posta", note: "The riverside wholesale market for potatoes, onions and grain." },
      { name: "Mullick Ghat Flower Market", note: "Under Howrah Bridge. Two thousand traders from four in the morning." },
    ],
    eats: [
      { name: "Ganesh Dhaba", where: "Burrabazar", note: "Rajasthani thali, eaten fast, standing if necessary." },
      { name: "Tewari Brothers", where: "Chittaranjan Avenue", note: "Kochuri, and the best cholar dal in the district." },
      { name: "Kachori and jalebi stalls", where: "Canning Street, before ten", note: "The trade's breakfast." },
    ],
    figures: [
      { name: "Rai Badridas Bahadur", note: "The jeweller who built the Pareshnath Jain Temple in 1867." },
    ],
    thingsToSee: [
      { name: "Pareshnath Jain Temple", note: "Mirror work, Belgian glass and a garden. Utterly unlike anything else here." },
      { name: "Mullick Ghat at 4am", note: "Marigold by the sack, by torchlight, under the bridge." },
      { name: "A porter on Cotton Street", note: "Two hundred kilos, on the head, through a crowd." },
    ],
    plates: ["streetfood", "rooftops", "howrah"],
    photos: ["burrabazar", "nakhoda-masjid", "burrabazar-old"],
    walk: [
      { stop: "Mahatma Gandhi Road metro", minutes: 0, note: "West towards the river." },
      { stop: "Canning Street", minutes: 10, note: "Paper, hardware, and the breakfast stalls." },
      { stop: "Pareshnath Jain Temple", minutes: 25, note: "North at Maniktala. Shoes off." },
      { stop: "Posta", minutes: 40, note: "The wholesale riverside. Chaotic." },
      { stop: "Mullick Ghat Flower Market", minutes: 50, note: "Best at dawn, but worth it any time." },
    ],
    sounds: [
      "Handcart wheels on stone, continuously",
      "Marwari, Bhojpuri, Bengali and Gujarati within one metre",
      "Twine, tape and cardboard, all day",
    ],
    scene: "streetfood",
    photo: "burrabazar",
  },
];
