import type { Neighbourhood } from "../types";

export const north: Neighbourhood[] = [
  {
    slug: "kumartuli",
    name: "Kumartuli",
    bengali: "কুমোরটুলি",
    zone: "north",
    tagline: "Where the goddess is built, every autumn, out of river mud.",
    knownFor: "Clay idol makers",
    coords: { lat: 22.6006, lng: 88.3616 },
    bestHour: "September mornings, 7–10am",
    summary:
      "Three hundred years of potters in a few narrow lanes, building the goddess out of river clay and straw every autumn.",
    body: [
      "The Company's settlement plan of the early eighteenth century put trades into their own quarters: Sutanuti for weavers, Kumartuli for potters. Almost everything else about that plan has dissolved. This has not.",
      "The material is specific. The clay comes from the Hooghly, and tradition requires that a portion, punya mati, be collected from outside a brothel in Sonagachi, on the argument that visitors leave their virtue at the door and the earth there holds it. The straw armature is bound first, then two layers of clay, then the fingers and the face.",
      "The eyes go on last. Chokkhu daan, the giving of the eyes, is done on Mahalaya, and until it happens the idol is not the goddess. Watching a bishwakarma paint them in three strokes is the single best thing you can see in this city.",
      "The lanes are barely two metres wide, hung with bare bulbs, and in September there are hundreds of half-finished ten-armed figures standing in them in the dark. Idols from here ship to Durga Pujas in New Jersey, London and Sydney.",
      "It is a working quarter and not a spectacle. Ask before photographing an artisan, and do not touch a finished face.",
    ],
    buildings: [
      { name: "Kumartuli Ghat", note: "Where the clay comes ashore and the idols go back into the river." },
      { name: "Kumartuli Park pandal ground", note: "Empty for eleven months, then one of the north's better theme pandals." },
      { name: "Banamali Sarkar Street", note: "The oldest run of workshops, some in the same family for six generations." },
    ],
    eats: [
      { name: "Cha and telebhaja", where: "Any stall on Rabindra Sarani", note: "The workshop diet, more or less exclusively." },
      { name: "Kochuri", where: "Sovabazar corner shops", note: "Before nine in the morning or not at all." },
    ],
    figures: [
      { name: "Gopeshwar Pal", note: "Brought naturalistic modelling to the trade in the 1930s after training in Britain." },
      { name: "China Pal", note: "One of the first women to run a Kumartuli studio in her own name." },
    ],
    thingsToSee: [
      { name: "Chokkhu daan on Mahalaya", note: "The eyes painted in three strokes. Arrive before dawn." },
      { name: "The straw armatures in July", note: "Nothing but bamboo and rope. The whole thing before it is anything." },
      { name: "Immersion from the ghat", note: "Dashami afternoon into the night, from the same steps the clay arrived at." },
    ],
    storySlugs: ["nine-days-in-kumartuli"],
    plates: ["kumartuli", "pujo", "rooftops"],
    photos: ["kumartuli-artisan", "kumartuli-clay", "chokkhu-daan"],
    walk: [
      { stop: "Sovabazar Sutanuti metro", minutes: 0, note: "Start here. Exit and walk west towards the river." },
      { stop: "Banamali Sarkar Street", minutes: 8, note: "The first of the workshop lanes." },
      { stop: "Kumartuli Park", minutes: 15, note: "Larger studios, bigger commissions." },
      { stop: "Kumartuli Ghat", minutes: 22, note: "Where the clay comes ashore and the idols go back in." },
      { stop: "Sovabazar Rajbari", minutes: 35, note: "The 1757 Puja courtyard. Ten minutes' walk east." },
    ],
    scene: "kumartuli",
    photo: "kumartuli-lane",
  },
  {
    slug: "jorasanko",
    name: "Jorasanko",
    bengali: "জোড়াসাঁকো",
    zone: "north",
    tagline: "Where Rabindranath Tagore was born.",
    knownFor: "The Tagore house, and the Bengal Renaissance",
    coords: { lat: 22.5852, lng: 88.3617 },
    bestHour: "Weekday mornings, before the school groups",
    summary:
      "A mansion in a north Kolkata lane that produced a Nobel laureate, two national anthems, a school of painting and most of modern Bengali culture.",
    body: [
      "Prince Dwarkanath Tagore's family took the house in the late eighteenth century, and by the middle of the nineteenth it was less a residence than an institution. The Tagores were Brahmos, reformers and patrons. They ran their own magazines, staged their own plays in their own hall, published their own music, and argued continuously.",
      "Rabindranath was born here in May 1861, the fourteenth child, and was largely educated inside the house because he hated school and left it. He wrote Gitanjali here. He set two thousand songs here. He died here, in August 1941, in the room he was born in.",
      "The house also produced Abanindranath and Gaganendranath Tagore, who founded the Bengal School of Art and reoriented Indian painting away from Victorian academic realism. Jyotirindranath ran the theatre. Swarnakumari Devi was among the first Bengali women novelists.",
      "It is now Rabindra Bharati University and a museum. The rooms are preserved: the bed he died in, the palanquin, the manuscripts with the crossings-out he later turned into drawings. There is a gallery on the Japanese and Hungarian connections that almost nobody visits.",
      "The lane outside is ordinary north Kolkata, which is the point. Nothing about the street announces what is behind the gate.",
    ],
    buildings: [
      { name: "Jorasanko Thakurbari", note: "The house itself. Museum and university, open daily except Monday." },
      { name: "Maharshi Bhavan", note: "Debendranath Tagore's wing, and the room Rabindranath died in." },
      { name: "Bichitra Bhavan", note: "The gallery wing, with the Bengal School canvases." },
      { name: "Nakhoda Masjid", note: "Fifteen minutes' walk south down Rabindra Sarani.", href: "/heritage/nakhoda-masjid" },
    ],
    eats: [
      { name: "Girish Chandra Dey & Nakur Chandra Nandy", where: "Ramdulal Sarkar Street", note: "Since 1844. The jolbhora sandesh with gur inside." },
      { name: "Tewari Brothers", where: "Chittaranjan Avenue", note: "Kochuri and cholar dal, from six in the morning." },
      { name: "Chittaranjan Mistanna Bhandar", where: "Shyampukur", note: "Mishti doi in a clay pot." },
    ],
    figures: [
      { name: "Rabindranath Tagore", note: "Born and died in this house. Nobel Prize, 1913." },
      { name: "Abanindranath Tagore", note: "Founded the Bengal School of Art. Bharat Mata, 1905." },
      { name: "Dwarkanath Tagore", note: "The merchant prince who bought the house and financed the Renaissance." },
      { name: "Swarnakumari Devi", note: "Novelist and editor, and Rabindranath's elder sister." },
    ],
    thingsToSee: [
      { name: "The room where he was born and died", note: "Preserved. The same room, eighty years apart." },
      { name: "The manuscript doodles", note: "Crossings-out turned into faces and animals. He began painting from these at sixty-three." },
      { name: "The Bengal School gallery", note: "Abanindranath, Nandalal Bose, Gaganendranath's cubist experiments." },
      { name: "Rabindra Jayanti, 25 Boishakh", note: "The courtyard fills and the songs are sung where they were written." },
    ],
    storySlugs: ["the-coffee-house-table"],
    plates: ["rooftops", "collegestreet", "kumartuli"],
    photos: ["marble-palace", "old-door", "chitpur-road"],
    walk: [
      { stop: "Girish Park metro", minutes: 0, note: "Come up and walk north-west." },
      { stop: "Jorasanko Thakurbari", minutes: 7, note: "Two hours minimum. Closed Mondays." },
      { stop: "Nakur Nandy", minutes: 18, note: "Sandesh, standing up, since 1844." },
      { stop: "Marble Palace", minutes: 26, note: "Permit needed. Closed Mondays and Thursdays." },
      { stop: "Chitpur Road", minutes: 34, note: "The oldest road in the city, running south." },
    ],
    scene: "rooftops",
    photo: "jorasanko-thakurbari",
  },
  {
    slug: "bagbazar",
    name: "Bagbazar",
    bengali: "বাগবাজার",
    zone: "north",
    tagline: "The northern edge, where the theatre and the politics started.",
    knownFor: "Community Durga Puja, Bengali theatre, the ghat",
    coords: { lat: 22.6006, lng: 88.3684 },
    bestHour: "Six in the morning, at the ghat",
    summary:
      "Less aristocratic than its neighbours and more literary: the birthplace of the community Puja, of modern Bengali theatre, and of a lot of arguments.",
    body: [
      "Bagbazar was a garden district that became, in the nineteenth century, the address of the Bengali professional and intellectual class rather than the landowning one. That distinction shaped everything about it.",
      "Bagbazar Sarbojanin, founded in 1919, was among the first sarbojanin or community Durga Pujas, as opposed to the household ones held in the rich families' courtyards. It opened the festival to anybody who could contribute a subscription, and within twenty years the form it invented was the form the whole city used.",
      "Girish Chandra Ghosh lived and worked here and effectively founded modern Bengali theatre: the professional stage, the paid company, the adapted repertoire. Sister Nivedita's house on Bosepara Lane is preserved. Ramakrishna's circle came and went constantly.",
      "Bagbazar Ghat is a working ghat. At six in the morning there are swimmers, priests, laundry, a ferry to Howrah, and the best view of the second bridge in the city.",
    ],
    buildings: [
      { name: "Bagbazar Sarbojanin ground", note: "Empty eleven months of the year. In October it holds the oldest community Puja in the city." },
      { name: "Sister Nivedita's House", note: "16 Bosepara Lane. Restored, and open to visitors." },
      { name: "Girish Mancha", note: "The theatre named for Girish Chandra Ghosh, still programming." },
      { name: "Bagbazar Ghat", note: "Ferry, bathing steps, and the Vivekananda Setu view." },
    ],
    eats: [
      { name: "Nobin Chandra Das", where: "Bagbazar Street", note: "The address where the rosogolla was invented in 1868." },
      { name: "Bagbazar's telebhaja stalls", where: "Along the main road at 5pm", note: "Beguni and phuluri, in newspaper." },
    ],
    figures: [
      { name: "Girish Chandra Ghosh", note: "Playwright, actor, and the founder of the professional Bengali stage." },
      { name: "Sister Nivedita", note: "Margaret Noble of Dungannon, who came for Vivekananda and stayed to run a girls' school." },
      { name: "Nobin Chandra Das", note: "Worked out how to boil chhena in syrup without it falling apart." },
    ],
    thingsToSee: [
      { name: "Bagbazar Sarbojanin at Ashtami", note: "The classical ekchala idol, no theme, no gimmick. The opposite of south Kolkata." },
      { name: "The ghat at dawn", note: "Before six. Swimmers, priests, and the ferry starting up." },
      { name: "Nivedita's house", note: "Small, restored, and almost empty of visitors." },
    ],
    plates: ["kumartuli", "river", "rooftops"],
    photos: ["hooghly-ferry", "immersion", "north-kolkata-lane"],
    walk: [
      { stop: "Shyambazar metro", minutes: 0, note: "Come up at the five-point crossing." },
      { stop: "Bagbazar Street", minutes: 10, note: "Presses, sweet shops, and the old theatre addresses." },
      { stop: "Sister Nivedita's House", minutes: 16, note: "Bosepara Lane. Ring the bell." },
      { stop: "Bagbazar Sarbojanin ground", minutes: 22, note: "In October, allow an hour." },
      { stop: "Bagbazar Ghat", minutes: 28, note: "Ferry across, or just sit." },
    ],
    scene: "river",
    photo: "bagbazar-ghat",
  },
  {
    slug: "sovabazar",
    name: "Sovabazar",
    bengali: "শোভাবাজার",
    zone: "north",
    tagline: "The courtyard where Kolkata's Durga Puja began, in 1757.",
    knownFor: "The Rajbari, and bonedi bari Pujas",
    coords: { lat: 22.5989, lng: 88.3667 },
    bestHour: "Ashtami evening, or any quiet weekday morning",
    summary:
      "Raja Nabakrishna Deb's mansion has held a Durga Puja every year since the year of Plassey, in a courtyard that has not been rebuilt.",
    body: [
      "Nabakrishna Deb was Clive's Persian tutor and interpreter, and he did extremely well out of 1757. The house he built at Sovabazar held its first Durga Puja that same autumn, in a thakur dalan, a pillared courtyard shrine, that is still standing and still used.",
      "The Puja has run every year since, which makes it the longest continuously observed Durga Puja in the city. The idol is ekchala, all five figures on a single backdrop, in the old style, and the rituals follow the household form rather than the community one.",
      "The bonedi bari tradition, the household Puja of an old family, is a completely different experience from the street pandals. There is no crowd, no sound system, no theme. There is a courtyard, a family, a priest, and a great deal of protocol.",
      "Several of these houses open to visitors in October. Sovabazar Rajbari is the most accessible and the most historically loaded.",
    ],
    buildings: [
      { name: "Sovabazar Rajbari", note: "Two houses, actually: the Boro Bari and the Chhoto Bari, both with their own Pujas." },
      { name: "The thakur dalan", note: "The pillared courtyard shrine. Unchanged since the eighteenth century." },
      { name: "Sovabazar Sutanuti metro", note: "The station has a small display on the three villages the city grew from." },
    ],
    eats: [
      { name: "Putiram", where: "College Street, twenty minutes south", note: "Since 1868. Kochuri before ten." },
      { name: "Bhojohori Manna", where: "Multiple", note: "The reliable sit-down Bengali meal nearby." },
    ],
    figures: [
      { name: "Raja Nabakrishna Deb", note: "Clive's interpreter, and the founder of the 1757 Puja." },
      { name: "Radhakanta Deb", note: "His grandson, the conservative scholar who opposed Rammohan Roy on almost everything." },
    ],
    thingsToSee: [
      { name: "The 1757 Puja", note: "Saptami to Dashami. Ask at the gate; visitors are generally welcome." },
      { name: "The ekchala idol", note: "All five figures on one backdrop, painted in the old style. Nothing like a pandal idol." },
      { name: "Dhunuchi naach on Ashtami", note: "The incense-burner dance, in a courtyard rather than a street." },
    ],
    plates: ["pujo", "rooftops", "kumartuli"],
    photos: ["hero-pujo", "dhunuchi-naach", "sovabazar-rajbari"],
    walk: [
      { stop: "Sovabazar Sutanuti metro", minutes: 0, note: "The heritage display is inside the station." },
      { stop: "Sovabazar Rajbari", minutes: 6, note: "The courtyard. Ask before photographing." },
      { stop: "Kumartuli", minutes: 18, note: "Ten minutes west, towards the river." },
      { stop: "Bagbazar Ghat", minutes: 30, note: "North along the river." },
    ],
    scene: "pujo",
    photo: "sovabazar-rajbari",
  },
  {
    slug: "shyambazar",
    name: "Shyambazar",
    bengali: "শ্যামবাজার",
    zone: "north",
    tagline: "Five roads, one statue, and the best kosha mangsho in the city.",
    knownFor: "The five-point crossing, Golbari, north Kolkata street life",
    coords: { lat: 22.5993, lng: 88.3742 },
    bestHour: "Evening, when the crossing is at full volume",
    summary:
      "A five-way junction with Subhas Chandra Bose on a horse in the middle of it, and a mutton shop on the corner that has been there for a century.",
    body: [
      "Shyambazar Panchmathar Mor, the five-point crossing, is the functional centre of north Kolkata. Five roads meet under an equestrian statue of Subhas Chandra Bose, put up in 1969, and the traffic negotiates it by consensus rather than by signal.",
      "The quarter is named for a Shyam Rai temple and grew as one of the original three villages' northern extension. It is dense, commercial, entirely unbeautiful and completely alive.",
      "Golbari, on the corner, has been selling kosha mangsho since the 1920s. The mutton is cooked down until it is almost black, and the recipe has never been written down or given out. There are no tables worth the name.",
      "Hatibagan market, ten minutes south, is where north Kolkata buys everything, and the theatre district around it kept the Bengali commercial stage alive through the twentieth century.",
    ],
    buildings: [
      { name: "Netaji statue, Panchmathar Mor", note: "Subhas Chandra Bose on horseback, 1969, at the centre of the five roads." },
      { name: "Star Theatre", note: "1883, moved and rebuilt. Girish Ghosh's stage, and now a restored auditorium and cinema." },
      { name: "Shyambazar tram depot", note: "Largely idle. It was one of the network's northern anchors." },
    ],
    eats: [
      { name: "Golbari", where: "Shyambazar five-point crossing", note: "Kosha mangsho, nearly black, since the 1920s. Take it away." },
      { name: "Mitra Cafe", where: "Sovabazar", note: "Since 1920. The kobiraji cutlet and the brain chop." },
      { name: "Allen Kitchen", where: "Jatindra Mohan Avenue", note: "Since 1900. Prawn cutlet, and nothing else matters." },
    ],
    figures: [
      { name: "Subhas Chandra Bose", note: "Lived on Elgin Road, but the north claims him. The statue is here." },
      { name: "Girish Chandra Ghosh", note: "Ran the Star Theatre and wrote for it." },
    ],
    thingsToSee: [
      { name: "The crossing at seven in the evening", note: "Five roads, no signal, and it works. Stand at the edge and watch." },
      { name: "Star Theatre", note: "Restored, and screening. The 1883 facade is intact." },
      { name: "Hatibagan market", note: "Ten minutes south. Everything north Kolkata buys." },
    ],
    plates: ["tram", "streetfood", "rooftops"],
    photos: ["tram-shyambazar", "yellow-taxi", "hand-rickshaw"],
    walk: [
      { stop: "Shyambazar metro", minutes: 0, note: "Come up into the crossing." },
      { stop: "Golbari", minutes: 3, note: "Kosha mangsho. Standing." },
      { stop: "Star Theatre", minutes: 9, note: "The 1883 building, on Bidhan Sarani." },
      { stop: "Hatibagan market", minutes: 16, note: "South. Fabric, fish, and everything else." },
      { stop: "Mitra Cafe", minutes: 24, note: "Kobiraji cutlet, since 1920." },
    ],
    scene: "tram",
    photo: "shyambazar",
  },
  {
    slug: "hatibagan",
    name: "Hatibagan",
    bengali: "হাতিবাগান",
    zone: "north",
    tagline: "The elephant garden that became north Kolkata's market and its theatre.",
    knownFor: "The market, the sweet shops, the old cinemas",
    coords: { lat: 22.5951, lng: 88.3699 },
    bestHour: "Late afternoon, especially in the fortnight before Puja",
    summary:
      "Named for a garden where the Nawab's elephants were kept. Now the market north Kolkata shops at, and the theatre district that outlived the theatres.",
    body: [
      "Hatibagan means elephant garden, and there were elephants: the Nawab of Bengal's, stabled here before the city closed in around them. What grew instead was a market and, from the 1870s, a theatre district.",
      "The Bengali commercial stage lived here. Minerva, Rangmahal, Star, Bishwaroopa: a run of theatres within a few hundred metres, staging melodrama, mythology and political allegory to full houses, six nights a week. Most are gone, converted, or burnt. Star survives, restored.",
      "The market is the reason to come now. In the fortnight before Durga Puja it becomes something close to impassable, because this is where north Kolkata buys its Puja clothes, and buying new clothes for Puja is not optional.",
      "Nakur Nandy is around the corner and has been making sandesh since 1844. The jolbhora, a sandesh with liquid nolen gur sealed inside it, is the single best sweet in the city between December and February.",
    ],
    buildings: [
      { name: "Star Theatre", note: "1883, restored in 2005 after a fire. Cinema and stage." },
      { name: "Minerva Theatre", note: "1893. Now the Minerva Repertory's home, after decades of decline." },
      { name: "Hatibagan market", note: "Sprawling, informal, and the trade the quarter runs on." },
    ],
    eats: [
      { name: "Girish Ch. Dey & Nakur Ch. Nandy", where: "Ramdulal Sarkar Street", note: "Since 1844. Jolbhora sandesh in winter." },
      { name: "Mitra Cafe", where: "Sovabazar", note: "Kobiraji cutlet and mutton afghani, since 1920." },
      { name: "Hatibagan phuchka stalls", where: "Along the market edge", note: "High turnover, therefore fresh." },
    ],
    figures: [
      { name: "Sisir Kumar Bhaduri", note: "The actor who brought naturalism to the Bengali stage in the 1920s." },
      { name: "Binodini Dasi", note: "Nati Binodini. Star Theatre was built on her earnings and named without her." },
    ],
    thingsToSee: [
      { name: "The market before Puja", note: "The last fortnight of Ashwin. Chaotic, and the best crowd-watching in the city." },
      { name: "Star Theatre's facade", note: "1883. Restored after the 1991 fire." },
      { name: "Nakur Nandy's counter", note: "Standing room only. Order the jolbhora." },
    ],
    plates: ["streetfood", "rooftops", "collegestreet"],
    photos: ["telebhaja", "north-kolkata-lane", "puja-crowd"],
    walk: [
      { stop: "Shyambazar metro", minutes: 0, note: "South down Bidhan Sarani." },
      { stop: "Star Theatre", minutes: 6, note: "The 1883 building." },
      { stop: "Nakur Nandy", minutes: 12, note: "Sandesh." },
      { stop: "Hatibagan market", minutes: 18, note: "Allow an hour if it is Puja season." },
      { stop: "Minerva Theatre", minutes: 26, note: "Check what the repertory is staging." },
    ],
    scene: "streetfood",
    photo: "hatibagan",
  },
  {
    slug: "college-street",
    name: "College Street",
    bengali: "বইপাড়া",
    alsoKnownAs: "Boi Para",
    zone: "north",
    tagline: "A mile and a half of secondhand books, and the room where the arguments happened.",
    knownFor: "Books, coffee and argument",
    coords: { lat: 22.5747, lng: 88.365 },
    bestHour: "Weekday afternoons",
    summary:
      "Boi Para, the book neighbourhood: the largest secondhand book market in the world, and the coffee house where the twentieth century in Bengal was argued out.",
    body: [
      "It is said to be the largest secondhand book market in the world and the largest book market of any kind in India. Whether or not the superlatives hold, the density does: stalls stacked two and three metres high on both pavements, running past Presidency, Calcutta University, Sanskrit College, Medical College and Hare School.",
      "The trade works on request. You describe what you want, the stallholder disappears into a wall of paper, and eleven minutes later it is in your hand. Nobody knows how the index works and there is not one.",
      "The Indian Coffee House on Bankim Chatterjee Street opened in 1942 as the Albert Hall. Its high ceiling, slow fans and turbaned waiters have hosted Satyajit Ray, Ritwik Ghatak, Amartya Sen, Mrinal Sen, and several generations of student politics. The coffee is not the reason to go.",
      "Publishers, printers, binderies and paper wholesalers occupy the buildings behind the stalls, so the whole trade is on one street from typesetting to resale.",
      "Bargain, but not hard. Margins here are thin and the stallholders are the last people in the city who can find you a 1962 Bengali translation of anything.",
    ],
    buildings: [
      { name: "Presidency University", note: "Founded 1817 as Hindu College. The Baker Laboratory is behind the main gate." },
      { name: "Indian Coffee House", note: "First floor, Bankim Chatterjee Street. Worker-owned since 1958." },
      { name: "University of Calcutta", note: "1857. The Senate House was demolished in 1960 and is still resented." },
      { name: "Sanskrit College", note: "1824. Vidyasagar was its principal and opened it to non-brahmins." },
      { name: "Medical College", note: "1835. The first institution in Asia to teach Western medicine in English." },
    ],
    eats: [
      { name: "Putiram", where: "Surya Sen Street", note: "Since 1868. Kochuri and radhaballavi before ten." },
      { name: "Kalika Mukhorochak", where: "Surya Sen Street", note: "Telebhaja since 1962. Students have kept it alive." },
      { name: "Paramount Sherbets", where: "Bankim Chatterjee Street", note: "Since 1918. The daab sherbet." },
      { name: "Indian Coffee House", where: "Bankim Chatterjee Street", note: "Infusion and a mutton afghani cutlet." },
    ],
    figures: [
      { name: "Ishwar Chandra Vidyasagar", note: "Reformer and principal of Sanskrit College, who forced through widow remarriage." },
      { name: "Amartya Sen", note: "A Presidency undergraduate who argued in the Coffee House." },
      { name: "Satyajit Ray", note: "Came here before Pather Panchali, when he was designing book jackets." },
      { name: "H. L. V. Derozio", note: "Taught at Hindu College, died at twenty-two, and shaped a generation of radicals." },
    ],
    thingsToSee: [
      { name: "The Coffee House at four", note: "High ceiling, slow fans, and a room that sounds like one argument." },
      { name: "The stalls at Colootola", note: "Ask for something obscure. Watch what happens." },
      { name: "Presidency's Baker Laboratory", note: "Where J. C. Bose and P. C. Ray worked." },
      { name: "Paramount's marble counter", note: "Unchanged since 1918. Order the daab." },
    ],
    storySlugs: ["the-coffee-house-table", "a-city-that-reads-at-midnight"],
    plates: ["collegestreet", "streetfood", "rooftops"],
    photos: ["hero-collegestreet", "coffee-house", "tram-college-street"],
    walk: [
      { stop: "Mahatma Gandhi Road metro", minutes: 0, note: "Come up and turn south." },
      { stop: "The stalls at Colootola crossing", minutes: 5, note: "Textbooks and exam guides. Keep going." },
      { stop: "Presidency University gate", minutes: 12, note: "The Baker Laboratory building is behind it." },
      { stop: "Indian Coffee House", minutes: 15, note: "First floor. Infusion and a cutlet." },
      { stop: "Putiram", minutes: 20, note: "Since 1868. Kochuri, or a radhaballavi if it is early." },
      { stop: "Kalika Mukhorochak", minutes: 25, note: "Telebhaja. The end of the walk by design." },
    ],
    scene: "collegestreet",
    photo: "college-street",
  },
  {
    slug: "chitpur",
    name: "Chitpur",
    bengali: "চিতপুর",
    zone: "north",
    tagline: "The road that was here before the city was.",
    knownFor: "The oldest road, jatra companies, sign painters",
    coords: { lat: 22.5892, lng: 88.3596 },
    bestHour: "Morning, before the traffic wins",
    summary:
      "Chitpur Road predates Calcutta. It was the pilgrim route to Kalighat, and it still runs the trades that grew along it.",
    body: [
      "Before the Company arrived there was a track through the jungle from the north down to the Kali temple at Kalighat. That track became Chitpur Road, now Rabindra Sarani, and it is the oldest continuously used route in the city.",
      "The trades along it are specific and old: the jatra companies that supply travelling folk theatre across Bengal, the sign painters, the brass and bell-metal workers, the sehnai and dhol makers, and the shops that supply the Puja trade.",
      "Nakhoda Masjid sits on it, and Zakaria Street runs off it. So does the old Chinese quarter at Tiretta Bazar. The road is a cross-section of every community that arrived by river.",
      "The jatra offices around Beadon Street still cast, rehearse and dispatch companies to village performances through the winter season. Posters go up on the same walls they have used for a century.",
      "It is congested, unlovely in places, and the single most historically dense street in Kolkata.",
    ],
    buildings: [
      { name: "Nakhoda Masjid", note: "1926, red sandstone, modelled on Akbar's tomb.", href: "/heritage/nakhoda-masjid" },
      { name: "Tiretta Bazar", note: "The original Chinese quarter, with a breakfast market that starts at six." },
      { name: "The jatra para, Beadon Street", note: "Company offices, poster walls, and casting in early autumn." },
      { name: "Armenian Church of Nazareth", note: "1724, and the oldest church in the city.", href: "/heritage/armenian-church" },
    ],
    eats: [
      { name: "Royal India Hotel", where: "Rabindra Sarani", note: "Since 1905. Mutton biryani, and it is not a hotel." },
      { name: "Zakaria Street, in Ramadan", where: "Below Nakhoda Masjid", note: "Haleem, suta kebab, phirni in clay bowls." },
      { name: "Tiretta Bazar breakfast", where: "Central, 6–8am", note: "Pork buns and fish ball soup. Over by seven." },
    ],
    figures: [
      { name: "Utpal Dutt", note: "Wrote for jatra as seriously as he wrote for the proscenium stage." },
      { name: "Abdur Rahim Osman", note: "The Kutchi Memon shipping merchant who funded Nakhoda Masjid." },
    ],
    thingsToSee: [
      { name: "A dhol being tuned in a workshop doorway", note: "The instrument makers work with the shutters up." },
      { name: "Jatra posters going up", note: "September and October. Hand-painted, on the same walls for a century." },
      { name: "Zakaria Street at iftar", note: "The best month to eat in this city, by some distance." },
    ],
    plates: ["rooftops", "streetfood", "collegestreet"],
    photos: ["nakhoda-masjid", "north-kolkata-lane", "burrabazar"],
    walk: [
      { stop: "Nakhoda Masjid", minutes: 0, note: "Start at the mosque, on Rabindra Sarani." },
      { stop: "Zakaria Street", minutes: 5, note: "Food. Especially in Ramadan." },
      { stop: "Tiretta Bazar", minutes: 15, note: "The old Chinese quarter. Breakfast market at dawn." },
      { stop: "The jatra para, Beadon Street", minutes: 30, note: "Theatre company offices and poster walls." },
      { stop: "Sign painters' shops", minutes: 35, note: "Hand-lettered boards, still made to order." },
    ],
    scene: "rooftops",
    photo: "chitpur-road",
  },
];
