import type { Neighbourhood } from "../types";

export const riverside: Neighbourhood[] = [
  {
    slug: "hooghly-river",
    name: "The Hooghly",
    bengali: "হুগলি নদী",
    zone: "riverside",
    tagline: "The reason the city is here, and the thing it keeps its back to.",
    knownFor: "The river itself, ferries, ghats, hilsa",
    coords: { lat: 22.5673, lng: 88.3374 },
    bestHour: "Six in the morning, on a ferry, in December",
    summary:
      "A western distributary of the Ganga that made the city, has been trying to silt itself shut for two centuries, and is dredged and flushed daily to prevent it.",
    body: [
      "The Ganga splits in Bengal. The main flow goes east into Bangladesh as the Padma; a western distributary comes down past Murshidabad and Nabadwip and becomes the Hooghly. Job Charnock's factory of 1690 was placed on a bend of it deep enough to float a ship and far enough upriver to be defensible.",
      "The problem started almost immediately. The Hooghly is a silting river, and as its share of the Ganga's flow declined the channel shallowed. By the nineteenth century the approach from the sea, particularly the James and Mary shoal, had killed more ships than any comparable stretch of water in India.",
      "The engineering answer was the Farakka barrage, built in 1975, 280 kilometres upstream, which diverts water into a feeder canal to flush the channel. It has partly worked and has cost a great deal, diplomatically and environmentally.",
      "What is in it now: sewage from a metropolitan area of fifteen million, much of it untreated; several thousand immersed idols a year; Gangetic dolphins in small and declining numbers; and hilsa, running upriver to spawn between June and September, which the entire Bengali culinary year is organised around.",
      "And the ferries. Twenty-odd crossings a day, five rupees, ten minutes, and the only way to see the bridge properly.",
    ],
    buildings: [
      { name: "Howrah Bridge", note: "1943, cantilever, riveted. 705 metres.", href: "/heritage/howrah-bridge" },
      { name: "Vidyasagar Setu", note: "1992. Cable-stayed, 823 metres, and the second bridge." },
      { name: "Vivekananda Setu", note: "1932. The Bally bridge, road and rail, in the north." },
      { name: "Kolkata Port, Kidderpore Docks", note: "1780s onwards. Still working, though the big ships go to Haldia." },
    ],
    eats: [
      { name: "Jhalmuri on the ferry", where: "Any crossing", note: "Sold on board, in a paper cone." },
      { name: "Hilsa, June to September", where: "Any Bengali kitchen", note: "Shorshe ilish. Watch for bones." },
      { name: "Tea at the ghat", where: "Babughat, Bagbazar, Ahiritola", note: "Clay cup, before six." },
    ],
    figures: [
      { name: "Job Charnock", note: "Tied up on the east bank in 1690 because the water was deep and the marsh defensible." },
      { name: "James Prinsep", note: "Scholar and Mint assay master. The ghat is named for him." },
    ],
    thingsToSee: [
      { name: "The Howrah–Kolkata ferry at dawn", note: "Ten minutes, five rupees, and the best commute in India." },
      { name: "Immersion on Dashami", note: "Babughat and Bagbazar Ghat. Thousands of idols, all night." },
      { name: "Mullick Ghat Flower Market", note: "From four in the morning, under the bridge." },
      { name: "A Gangetic dolphin", note: "Rare, and getting rarer. Look near Prinsep Ghat at dusk." },
    ],
    storySlugs: ["what-the-hooghly-carries"],
    plates: ["river", "howrah", "rooftops"],
    photos: ["hooghly-ferry", "vidyasagar-setu", "kolkata-port"],
    walk: [
      { stop: "Babughat", minutes: 0, note: "Ferries, and the main Dashami immersion point." },
      { stop: "Prinsep Ghat", minutes: 14, note: "1841 Palladian portico. Sunset." },
      { stop: "Millennium Park", minutes: 30, note: "North along the Strand." },
      { stop: "Mullick Ghat Flower Market", minutes: 45, note: "Under the bridge. Best before six." },
      { stop: "Howrah Bridge, on foot", minutes: 55, note: "Cross it and come back." },
    ],
    sounds: [
      "A ferry horn, carrying a long way over water",
      "Oars and a diesel engine at the same time",
      "The bridge, from underneath, continuously",
    ],
    scene: "river",
    photo: "hooghly-sunset",
  },
  {
    slug: "howrah-bridge-strand",
    name: "Strand Road & Howrah Bridge",
    bengali: "স্ট্র্যান্ড রোড",
    zone: "riverside",
    tagline: "705 metres of riveted steel, and two thousand flower traders underneath it.",
    knownFor: "The bridge, Mullick Ghat, Howrah Station",
    coords: { lat: 22.5851, lng: 88.3468 },
    bestHour: "Between four and six in the morning",
    summary:
      "The bridge is the city's signature, and the flower market beneath it is the best hour of the day anywhere in Kolkata.",
    body: [
      "Howrah Bridge opened in February 1943 without ceremony, because a lit ribbon-cutting on the Hooghly during a Japanese bombing campaign seemed unwise. The first thing across was a tram.",
      "It is a cantilever, riveted rather than bolted, 705 metres long, hanging from two 82-metre towers and touching the water nowhere in between. Roughly 26,500 tonnes of steel, most of it Tata's. What it carries now is the point: cars and buses matter less than the river of people who walk it, and the pavement has been worn into shallow troughs.",
      "Mullick Ghat Flower Market sits directly beneath the eastern approach. From about four in the morning, two thousand traders sort marigold, tuberose, jasmine and lotus by torchlight, on the steps, in sacks. It supplies the temples, the weddings and the Pujas of the whole metropolitan area.",
      "Howrah Station is on the far bank: twenty-three platforms and among the busiest railway stations in the world.",
      "Photography from the bridge deck is restricted. Everyone shoots it from the flower market instead, which is the better frame anyway.",
    ],
    buildings: [
      { name: "Howrah Bridge", note: "1943. Rendel, Palmer & Tritton. Renamed Rabindra Setu in 1965.", href: "/heritage/howrah-bridge" },
      { name: "Mullick Ghat Flower Market", note: "Two thousand traders, from four in the morning." },
      { name: "Howrah Station", note: "1854 and 1905. Twenty-three platforms." },
      { name: "Armenian Ghat", note: "Where the first tram line terminated in 1873." },
    ],
    eats: [
      { name: "Tea at Mullick Ghat", where: "On the steps, before dawn", note: "Clay cup, and whatever the traders are eating." },
      { name: "Kochuri at Howrah Station", where: "The Howrah side", note: "Fast, cheap, and better than it needs to be." },
      { name: "Puti Ram's rivals on Strand Road", where: "Morning", note: "Kochuri and jalebi for the market trade." },
    ],
    figures: [
      { name: "Rendel, Palmer & Tritton", note: "Designed the cantilever. Cleveland Bridge built it." },
      { name: "The flower traders of Mullick Ghat", note: "Two thousand of them, mostly from Howrah and Hooghly districts." },
    ],
    thingsToSee: [
      { name: "The flower market at 4:30am", note: "Marigold by the sack, by torchlight. The best hour in the city." },
      { name: "The bridge on foot", note: "Cross it at seven. Look at the wear in the pavement." },
      { name: "Sunrise from Armenian Ghat", note: "The bridge silhouetted, with the ferries starting." },
    ],
    plates: ["howrah", "river", "streetfood"],
    photos: ["howrah-bridge-girders", "mullick-ghat-flower-market", "howrah-bridge-night"],
    walk: [
      { stop: "Mullick Ghat Flower Market", minutes: 0, note: "Arrive by five. Taxi; nothing else runs." },
      { stop: "Armenian Ghat", minutes: 12, note: "The 1873 tram terminus." },
      { stop: "Howrah Bridge, walking east to west", minutes: 20, note: "Fifteen minutes across." },
      { stop: "Howrah Station", minutes: 40, note: "Twenty-three platforms, and worth ten minutes." },
      { stop: "Ferry back to Babughat", minutes: 55, note: "Five rupees. The view is the point." },
    ],
    sounds: [
      "Sacks of marigold hitting stone",
      "The bridge expansion joints under a bus",
      "Ferry engines idling at Armenian Ghat",
    ],
    scene: "howrah",
    photo: "howrah-bridge",
  },
  {
    slug: "prinsep-ghat",
    name: "Prinsep Ghat",
    bengali: "প্রিন্সেপ ঘাট",
    zone: "riverside",
    tagline: "A Palladian portico on the river, and the city's sunset.",
    knownFor: "The 1841 memorial, sunset, boat rides",
    coords: { lat: 22.557, lng: 88.332 },
    bestHour: "The hour before sunset",
    summary:
      "Built in 1841 for the scholar who deciphered Brahmi, and now the place the whole city goes to watch the light go.",
    body: [
      "James Prinsep was an assay master at the Calcutta Mint, a scholar, an architect and the man who deciphered the Brahmi and Kharosthi scripts, which unlocked the Ashokan edicts and with them a large part of ancient Indian history. He died in 1840, at forty, and the portico was raised the next year.",
      "It is Greek Revival, Palladian in feel, with a run of Doric columns facing the water. Restored in the 2000s along with the promenade, it is now the most photographed stretch of the riverfront after the bridge.",
      "Vidyasagar Setu, the second Hooghly bridge, rises immediately behind it, and the combination of the 1841 portico and the 1992 cable-stays in one frame is the shot everyone comes for.",
      "There are boat rides from the steps, an evening food market along the promenade, and on a Sunday it is completely full of families. Go on a weekday if you want the light without the crowd.",
      "The old Calcutta Circular Railway runs behind it, and a train going past at dusk is part of the experience.",
    ],
    buildings: [
      { name: "Prinsep Ghat memorial", note: "1841, Greek Revival, W. Fitzgerald. Restored in the 2000s." },
      { name: "Vidyasagar Setu", note: "1992. Cable-stayed, and lit at night." },
      { name: "Gwalior Monument", note: "1847, nearby. A bronze-clad cupola for the dead of the Gwalior campaign." },
      { name: "St. Paul's Cathedral", note: "Fifteen minutes east across the Maidan.", href: "/heritage/st-pauls-cathedral" },
    ],
    eats: [
      { name: "The promenade food stalls", where: "Along the ghat, evenings", note: "Momos, rolls, phuchka, and tea." },
      { name: "Jhalmuri on the steps", where: "Sunset", note: "Shaken in a tin while you wait for the light." },
    ],
    figures: [
      { name: "James Prinsep", note: "Deciphered Brahmi and Kharosthi. Died at forty; the ghat is his memorial." },
    ],
    thingsToSee: [
      { name: "Sunset behind Vidyasagar Setu", note: "The 1841 columns and the 1992 cables in one frame." },
      { name: "A boat out and back", note: "Half an hour on the water, from the steps." },
      { name: "The circular railway at dusk", note: "A train behind the columns. Photographers wait for it." },
    ],
    storySlugs: ["what-the-hooghly-carries"],
    plates: ["river", "victoria", "howrah"],
    photos: ["vidyasagar-setu", "hooghly-ferry", "maidan"],
    walk: [
      { stop: "Prinsep Ghat", minutes: 0, note: "Arrive an hour before sunset." },
      { stop: "The promenade north", minutes: 15, note: "Towards Babughat, along the water." },
      { stop: "Gwalior Monument", minutes: 25, note: "1847, and usually ignored." },
      { stop: "Victoria Memorial", minutes: 45, note: "East across the Maidan, floodlit by now." },
    ],
    sounds: [
      "The circular railway, every twenty minutes",
      "Boat engines starting at the steps",
      "A flute seller, most evenings",
    ],
    scene: "river",
    photo: "prinsep-ghat",
  },
  {
    slug: "babughat",
    name: "Babughat",
    bengali: "বাবুঘাট",
    zone: "riverside",
    tagline: "Where the idols come back to the river.",
    knownFor: "Ferries, immersion, the bus terminus",
    coords: { lat: 22.5673, lng: 88.3374 },
    bestHour: "Dashami afternoon, or any dawn",
    summary:
      "A working ghat with a Doric portico, a ferry service, a bus terminus and the city's principal Durga Puja immersion point.",
    body: [
      "Babu Ghat was built in 1830 by Rani Rashmoni in memory of her husband Babu Rajchandra Das, and the Doric portico at the top of the steps is the surviving piece of that.",
      "It is the busiest of the central ghats. Ferries run to Howrah and Belur. The bus terminus behind it serves long-distance routes across the state. Pilgrims for Gangasagar assemble here every January in very large numbers.",
      "On Dashami, the last day of Durga Puja, this is where a substantial share of the city's idols come to be immersed. Lorries queue along Strand Road through the afternoon and into the night; cranes lift the larger figures; the frames are pulled out again afterwards under the current rules, and the clay goes back into the water it came from.",
      "It is not a picturesque ghat. It is a functional one, and that is more interesting.",
    ],
    buildings: [
      { name: "Babughat portico", note: "1830, built by Rani Rashmoni. Doric, and the surviving piece of the original." },
      { name: "Babughat bus terminus", note: "Long-distance routes across West Bengal." },
      { name: "Eden Gardens", note: "Five minutes east, behind the ghat." },
      { name: "Millennium Park", note: "North along the Strand." },
    ],
    eats: [
      { name: "Ghat-side tea stalls", where: "Along the steps", note: "Clay cups, from before dawn." },
      { name: "Bus terminus dhabas", where: "Behind the ghat", note: "Rice, dal and fish for very little." },
    ],
    figures: [
      { name: "Rani Rashmoni", note: "Built the ghat in 1830 and Dakshineswar temple twenty-five years later." },
    ],
    thingsToSee: [
      { name: "Immersion on Dashami", note: "From mid-afternoon until deep into the night. Cranes, lorries, and thousands of people." },
      { name: "The Gangasagar transit camp", note: "Early January. Several hundred thousand pilgrims pass through." },
      { name: "A ferry to Howrah", note: "Ten minutes, and the bridge from underneath." },
    ],
    plates: ["river", "howrah", "pujo"],
    photos: ["immersion", "ghat-bathing", "hooghly-ferry"],
    walk: [
      { stop: "Babughat", minutes: 0, note: "The portico, and the ferry jetty." },
      { stop: "Millennium Park", minutes: 12, note: "North along the Strand." },
      { stop: "Eden Gardens", minutes: 20, note: "East, behind the ghat." },
      { stop: "Prinsep Ghat", minutes: 32, note: "South along the water, for sunset." },
    ],
    sounds: [
      "Dhaak arriving with a lorry, on Dashami",
      "Bus conductors calling destinations",
      "Water against stone steps",
    ],
    scene: "river",
    photo: "babughat",
  },
  {
    slug: "millennium-park",
    name: "Millennium Park",
    bengali: "মিলেনিয়াম পার্ক",
    zone: "riverside",
    tagline: "The city turning back to face its river, about two hundred years late.",
    knownFor: "The riverfront promenade, evening crowds, the bridge view",
    coords: { lat: 22.5747, lng: 88.3402 },
    bestHour: "Evening, with the bridge lit",
    summary:
      "A strip of landscaped riverfront opened in 1999 along the Strand, and the first serious attempt to make the Hooghly something the city looks at rather than dumps into.",
    body: [
      "For two centuries Kolkata treated the Hooghly as working infrastructure: docks, warehouses, jetties, outfalls. The riverfront was not somewhere you went. Millennium Park, opened in 1999 and extended since, was the first attempt to change that.",
      "It is about two and a half kilometres of landscaped promenade along Strand Road, with lawns, benches, a musical fountain and a view straight up to Howrah Bridge. In the evening it fills with families, couples and photographers.",
      "The Kolkata Port Trust's older waterfront lies immediately behind it, and the contrast between the manicured strip and the working jetties a few hundred metres north is the whole argument about the river in one view.",
      "Further improvements have followed along the Strand, and there is a slow, contested plan to open more of the bank to the public.",
    ],
    buildings: [
      { name: "Millennium Park promenade", note: "Opened 1999, extended since. Lawns and river views." },
      { name: "Howrah Bridge", note: "Directly north, and the reason to be here at dusk.", href: "/heritage/howrah-bridge" },
      { name: "Fairlie Place jetty", note: "Ferries north to Belur and Dakshineswar." },
      { name: "GPO and BBD Bagh", note: "Ten minutes inland, and a different century." },
    ],
    eats: [
      { name: "Promenade stalls", where: "Along the park, evenings", note: "Chow, rolls, phuchka, ice cream." },
      { name: "Dalhousie office lunches", where: "Inland, 1–3pm", note: "Steel plates, no menus, very cheap." },
    ],
    figures: [
      { name: "Kolkata Port Trust", note: "Owns most of the bank, and the reason so little of it is public." },
    ],
    thingsToSee: [
      { name: "Howrah Bridge lit, from the lawn", note: "After dark. The classic view without the crowd at Mullick Ghat." },
      { name: "The working jetties north of the park", note: "The other river, a few hundred metres away." },
      { name: "A ferry from Fairlie Place", note: "North to Belur Math and Dakshineswar." },
    ],
    plates: ["howrah", "river", "rooftops"],
    photos: ["howrah-bridge-night", "hooghly-ferry", "high-court"],
    walk: [
      { stop: "Millennium Park", minutes: 0, note: "Enter from Strand Road." },
      { stop: "Fairlie Place jetty", minutes: 10, note: "Ferries north." },
      { stop: "Mullick Ghat Flower Market", minutes: 22, note: "North, under the bridge." },
      { stop: "BBD Bagh", minutes: 35, note: "Inland, for the colonial square." },
    ],
    sounds: [
      "A musical fountain, whether you want it or not",
      "Container cranes, distantly, from the north",
      "The bridge over everything",
    ],
    scene: "howrah",
    photo: "millennium-park",
  },
  {
    slug: "kidderpore",
    name: "Kidderpore",
    bengali: "খিদিরপুর",
    zone: "riverside",
    tagline: "The docks, and everything that came through them.",
    knownFor: "The port, Fancy Market, Metiabruz",
    coords: { lat: 22.538, lng: 88.32 },
    bestHour: "Late afternoon",
    summary:
      "The port quarter: shipbuilding, a bazaar that sells things nowhere else does, and the neighbourhood the last Nawab of Awadh was exiled next to.",
    body: [
      "Colonel Henry Watson set up a shipyard here in 1780. It became the Kidderpore Docks, and for a century and a half this was where jute went out, machinery came in, and the labour of the port lived.",
      "Fancy Market is the reason to come. It grew as a market for goods off the ships, legal and otherwise, and it still sells imported clothing, electronics, cosmetics and food that has arrived by routes nobody explains.",
      "Metiabruz, just south, is where Wajid Ali Shah was moved after the annexation of Awadh in 1856. He built a small second Lucknow: an imambara, a menagerie, a court of musicians and kite makers. Kolkata's biryani, its kite-flying and a good deal of its Urdu culture come from that exile.",
      "The area is largely Muslim and working class, and the food is correspondingly good and correspondingly cheap.",
      "It is not a heritage-trail neighbourhood and does not present itself as one. Go for the market and the biryani.",
    ],
    buildings: [
      { name: "Kidderpore Docks", note: "1780s onwards. Still working, though the deep-draught traffic goes to Haldia." },
      { name: "Metiabruz Shahi Imambara", note: "Built by Wajid Ali Shah's court after 1856." },
      { name: "Fancy Market", note: "Imported goods off the ships, and a trade that predates the customs union." },
      { name: "St. Stephen's Church", note: "1845, and one of the quieter colonial churches." },
    ],
    eats: [
      { name: "India Restaurant", where: "Kidderpore", note: "Mutton biryani, and a queue at eight in the evening." },
      { name: "Metiabruz biryani shops", where: "Iron Gate Road", note: "Ask locally. The answers differ and all of them are good." },
      { name: "Fancy Market's kebab stalls", where: "Late afternoon", note: "Charcoal, on the pavement." },
    ],
    figures: [
      { name: "Wajid Ali Shah", note: "The last Nawab of Awadh, exiled to Metiabruz in 1856 with his entire court." },
      { name: "Colonel Henry Watson", note: "Set up the shipyard in 1780 that became the docks." },
    ],
    thingsToSee: [
      { name: "Fancy Market late afternoon", note: "Bargain hard. Everything is negotiable and some of it is genuine." },
      { name: "The Shahi Imambara", note: "What is left of the second Lucknow." },
      { name: "Kite flying in autumn", note: "A Metiabruz inheritance, and still serious." },
    ],
    plates: ["river", "streetfood", "rooftops"],
    photos: ["kolkata-port", "fort-william", "kolkata-port"],
    walk: [
      { stop: "Khidirpur Fancy Market", minutes: 0, note: "Busiest late afternoon." },
      { stop: "Kidderpore Docks gate", minutes: 12, note: "Exterior. Still a working port." },
      { stop: "Metiabruz Shahi Imambara", minutes: 30, note: "Built by Wajid Ali Shah's court." },
      { stop: "A biryani shop on Iron Gate Road", minutes: 40, note: "Ask locally." },
    ],
    sounds: [
      "Container cranes, distantly, all night",
      "Urdu and Bengali traded across a stall",
      "Kite string being glued on a rooftop in autumn",
    ],
    scene: "river",
    photo: "kidderpore-docks",
  },
];
