import type { Neighbourhood } from "../types";

export const south: Neighbourhood[] = [
  {
    slug: "kalighat",
    name: "Kalighat",
    bengali: "কালীঘাট",
    zone: "south",
    tagline: "The shrine the city is probably named after.",
    knownFor: "The temple, the pat painters, the Adi Ganga",
    coords: { lat: 22.5203, lng: 88.3426 },
    bestHour: "Early morning, before the queue builds",
    summary:
      "A Shakti Peetha on an old channel of the Ganga, older than Calcutta, and the likely source of the city's name.",
    body: [
      "There was a Kali shrine on this creek long before there was a Calcutta, and one durable reading of the city's name traces it to Kalikshetra or Kalikata, the ground of Kali. The present temple building dates from 1809, funded by the Sabarna Roy Choudhury family.",
      "The image is unusual and unmistakable: a black stone face with three enormous gold eyes and a protruding gold tongue, quite unlike the Kali of the Puja pandals. Tradition places it as one of the fifty-one Shakti Peethas, where the toes of Sati's right foot fell.",
      "The lanes around the temple produced the Kalighat pat: fast, flat, brush-drawn watercolours sold to pilgrims from the early nineteenth century. They started as devotional images and turned satirical, mocking the westernised babu and the scandals of the day. Jamini Roy built a career on the style, and it fed directly into modern Indian art.",
      "The Adi Ganga beside the temple was the main channel of the Hooghly until the eighteenth century. It is now a narrow, badly polluted thing, and its condition is a standing civic argument.",
      "Mother Teresa's Nirmal Hriday, the home for the dying, opened in 1952 in a former pilgrim hostel next to the temple and is still running.",
    ],
    buildings: [
      { name: "Kalighat Kali Temple", note: "1809, Bengali ath-chala. One of 51 Shakti Peethas.", href: "/heritage/kalighat-temple" },
      { name: "Nirmal Hriday", note: "1952. Mother Teresa's home for the dying, beside the temple." },
      { name: "Keoratala burning ghat", note: "On the Adi Ganga. Tagore and Vivekananda were both cremated here." },
    ],
    eats: [
      { name: "Kalighat's prasad stalls", where: "The temple lanes", note: "Peda and batasha, sold by the leaf plate." },
      { name: "Balwant Singh's Eating House", where: "Bhowanipore, ten minutes north", note: "Open all night. Doodh cola for the brave." },
      { name: "Sharma Dhaba", where: "Hazra crossing", note: "Late-night parathas, and a lot of Bhowanipore's night traffic." },
    ],
    figures: [
      { name: "Jamini Roy", note: "Took the Kalighat pat style and made a modern Indian painting out of it." },
      { name: "Mother Teresa", note: "Opened Nirmal Hriday next to the temple in 1952." },
    ],
    thingsToSee: [
      { name: "The image itself", note: "Three gold eyes and a gold tongue on black stone. Nothing like a pandal Kali." },
      { name: "Kalighat pat paintings", note: "The originals are in the Victoria Memorial and the Indian Museum." },
      { name: "Kali Puja night", note: "October or November, on the new moon. Enormous, and worth the crush." },
    ],
    plates: ["kumartuli", "pujo", "river"],
    photos: ["kalighat-painting", "nirmal-hriday", "tram-grass-track"],
    walk: [
      { stop: "Kalighat metro", minutes: 0, note: "Line 1. Come up and follow the crowd." },
      { stop: "The temple", minutes: 6, note: "Ignore the touts. The ordinary queue works." },
      { stop: "Nirmal Hriday", minutes: 12, note: "Next door. Visitors are received." },
      { stop: "The Adi Ganga", minutes: 16, note: "The old main channel of the Hooghly, now a drain." },
      { stop: "Keoratala", minutes: 22, note: "The burning ghat, south along the channel." },
    ],
    scene: "kumartuli",
    photo: "kalighat-temple",
  },
  {
    slug: "ballygunge",
    name: "Ballygunge",
    bengali: "বালিগঞ্জ",
    zone: "south",
    tagline: "Tree-lined, apartment-blocked, and the epicentre of pandal-hopping.",
    knownFor: "South Kolkata bhadralok, Puja hopping, good restaurants",
    coords: { lat: 22.5286, lng: 88.3646 },
    bestHour: "Puja evenings",
    summary:
      "Where the Bengali professional middle class settled through the twentieth century, and where the city's idea of itself mostly lives.",
    body: [
      "Ballygunge, Deshapriya Park and Southern Avenue are where the bhadralok, the Bengali professional and cultured class, moved as the north filled up. The tone is set accordingly: bookshops, music schools, sweet shops with three generations of the same family behind the counter.",
      "Southern Avenue has the best tree cover in the city, and Rabindra Sarobar, the lake at its southern end, is where a substantial fraction of south Kolkata walks at six in the morning.",
      "Maddox Square during Puja is a phenomenon of its own. The pandal is unremarkable; the ground around it becomes an all-night open-air social event where most of south Kolkata's under-thirties meet everyone they went to school with.",
      "Deshapriya Park has, at intervals, hosted the tallest Durga idol in the city, which in 2015 drew crowds large enough that the police shut the pandal on the first day.",
      "Off the main roads the lanes are quiet, full of 1950s flats with deep verandahs, and this is the version of Kolkata that Bengali cinema has filmed most often.",
    ],
    buildings: [
      { name: "Rabindra Sarobar", note: "The lake. Rowing clubs, a stadium, and the whole quarter's morning walk." },
      { name: "Birla Mandir", note: "1996. Late, enormous, and cream sandstone." },
      { name: "Maddox Square", note: "A cricket ground for eleven months and the city's biggest social event for four days." },
      { name: "Gariahat flyover", note: "Ugly, useful, and the best view of the market beneath it." },
    ],
    eats: [
      { name: "6 Ballygunge Place", where: "Ballygunge Place", note: "Bengali, sit-down, in a converted house. The daab chingri." },
      { name: "Bhojohori Manna", where: "Ekdalia Road and branches", note: "Consistent, unromantic, good. Kosha mangsho." },
      { name: "Balaram Mullick & Radharaman Mullick", where: "Multiple", note: "Since 1885. Baked mishti doi." },
      { name: "Kasturi", where: "Mirza Ghalib Street and Ballygunge", note: "Bangladeshi Bengali. Kochu pata chingri." },
    ],
    figures: [
      { name: "Satyajit Ray", note: "Lived on Bishop Lefroy Road, and filmed this quarter repeatedly." },
      { name: "Suchitra Sen", note: "Lived here, and after 1978 was never photographed in public again." },
    ],
    thingsToSee: [
      { name: "Maddox Square on Ashtami", note: "Not the pandal. The field around it." },
      { name: "Southern Avenue in the rain", note: "The tree cover, and the light under it." },
      { name: "Rabindra Sarobar at dawn", note: "Rowers, walkers, and a surprising amount of birdlife." },
      { name: "Gariahat market", note: "Saris on the pavement, fish inside, and hawking that has survived every clearance." },
    ],
    plates: ["pujo", "rooftops", "streetfood"],
    photos: ["pandal-night", "sovabazar-rajbari", "sweet-shop"],
    walk: [
      { stop: "Rabindra Sarobar metro", minutes: 0, note: "Or the lake itself at dawn." },
      { stop: "Southern Avenue", minutes: 10, note: "The best tree cover in the city." },
      { stop: "Deshapriya Park", minutes: 18, note: "Puja, or an ordinary park the rest of the year." },
      { stop: "Gariahat crossing", minutes: 28, note: "Market, and the flyover for the view." },
      { stop: "Maddox Square", minutes: 40, note: "During Puja only. Otherwise a cricket ground." },
    ],
    scene: "pujo",
    photo: "ballygunge",
  },
  {
    slug: "gariahat",
    name: "Gariahat",
    bengali: "গড়িয়াহাট",
    zone: "south",
    tagline: "Saris on the pavement, fish inside, and hawking that survived every clearance.",
    knownFor: "The market, the crossing, Puja shopping",
    coords: { lat: 22.5185, lng: 88.3661 },
    bestHour: "Late afternoon, or any evening in the fortnight before Puja",
    summary:
      "South Kolkata's market: a formal one inside, an informal one on every pavement around it, and a crossing that has defeated every traffic plan attempted on it.",
    body: [
      "The Gariahat crossing is where Rashbehari Avenue meets Gariahat Road, and it is the commercial centre of south Kolkata. The formal market building holds fish, meat and vegetables. Everything else happens on the pavement.",
      "The hawker economy here is enormous, decades old, and repeatedly the subject of clearance drives that have never succeeded. Saris, kurtas, luggage, shoes, plastic, books, and in autumn nothing but Puja clothes.",
      "The fish market is the real institution. Bhetki, pabda, parshe, koi, chitol and, from June to September, hilsa, which is priced by the day and argued over with the seriousness of a commodities exchange.",
      "Traditionally, on derby day, the fish market sells prawn and hilsa as proxies for Mohun Bagan and East Bengal, and the price of each moves with the expected result.",
      "Dakshinapan, a state-run crafts complex ten minutes south, is the antidote: quiet, air-conditioned, and full of handloom from every state.",
    ],
    buildings: [
      { name: "Gariahat Market", note: "The formal building. Fish and vegetables downstairs." },
      { name: "Dakshinapan Shopping Centre", note: "Brutalist, state-run, and the best handloom shopping in the city." },
      { name: "Triangular Park", note: "A small green triangle that anchors the crossing." },
    ],
    eats: [
      { name: "Kalika", where: "Gariahat", note: "Not the College Street one. Rolls and cutlets, late." },
      { name: "Gupta Brothers", where: "Gariahat", note: "Kochuri and sweets, from the morning." },
      { name: "Campari", where: "Gariahat", note: "Cabin-style Anglo-Indian. Chops and cutlets since the 1960s." },
      { name: "Phuchka at the Triangular Park corner", where: "Evenings", note: "One of the busiest stalls in the city." },
    ],
    figures: [
      { name: "The Gariahat hawkers' unions", note: "Organised, entrenched, and politically consequential since the 1970s." },
    ],
    thingsToSee: [
      { name: "The fish market at seven in the morning", note: "Hilsa in season, and the pricing argument that goes with it." },
      { name: "Pavement sari shopping before Puja", note: "The single densest crowd in south Kolkata." },
      { name: "Dakshinapan", note: "Handloom from every state, and nobody in a hurry." },
    ],
    plates: ["streetfood", "rooftops", "pujo"],
    photos: ["puja-crowd", "sweet-shop", "yellow-taxis-traffic"],
    walk: [
      { stop: "Gariahat crossing", minutes: 0, note: "Start under the flyover." },
      { stop: "The fish market", minutes: 5, note: "Inside the formal building. Early or not at all." },
      { stop: "The pavement stalls", minutes: 15, note: "Rashbehari Avenue, both sides." },
      { stop: "Triangular Park", minutes: 25, note: "Phuchka." },
      { stop: "Dakshinapan", minutes: 40, note: "South. Quiet, and the handloom." },
    ],
    scene: "streetfood",
    photo: "gariahat",
  },
  {
    slug: "dhakuria",
    name: "Dhakuria",
    bengali: "ঢাকুরিয়া",
    zone: "south",
    tagline: "A lake, a bridge, and the quiet middle of south Kolkata.",
    knownFor: "Rabindra Sarobar, the rail bridge, residential calm",
    coords: { lat: 22.5027, lng: 88.3672 },
    bestHour: "Dawn at the lake",
    summary:
      "Built around the southern lakes dug in the 1920s, and one of the few parts of the city where you can hear birds.",
    body: [
      "The lakes were an improvement scheme: in the 1920s the Calcutta Improvement Trust excavated a large artificial lake in the southern marshes, planted the banks, and created what is now Rabindra Sarobar. Dhakuria grew around it.",
      "It is largely residential and largely calm, which in this city is unusual enough to be the defining feature. The lake has rowing clubs, a stadium, a Japanese Buddhist temple, and several thousand walkers before seven in the morning.",
      "Dhakuria Bridge over the rail line is the local landmark and the local traffic problem. Below it, Selimpur and Jadavpur run south into student territory.",
      "The lake has been the subject of a long environmental fight: over Chhath Puja immersions, over tree felling for a metro alignment, and over the noise and light of the events held on its banks. The National Green Tribunal has been involved repeatedly.",
    ],
    buildings: [
      { name: "Rabindra Sarobar", note: "Dug in the 1920s. Rowing clubs, a lake stadium, and the morning walk." },
      { name: "Nipponzan Myohoji Buddhist Temple", note: "1935, on the lake's southern bank. Japanese, and almost silent." },
      { name: "Dhakuria Bridge", note: "Over the rail line, and the local reference point for everything." },
    ],
    eats: [
      { name: "Bhojohori Manna", where: "Hindustan Park, nearby", note: "The dependable Bengali lunch." },
      { name: "Dhakuria's roll shops", where: "Around the bridge", note: "Student prices, and open late." },
      { name: "Jadavpur's Milanda canteen", where: "Jadavpur, south", note: "Cheap, loud, and a political institution." },
    ],
    figures: [
      { name: "The Calcutta Improvement Trust", note: "Dug the lake in the 1920s and laid out the streets around it." },
    ],
    thingsToSee: [
      { name: "The lake at six in the morning", note: "Rowers, walkers, and birds you will not hear anywhere else in Kolkata." },
      { name: "The Japanese temple", note: "1935, and usually empty. Drums at dawn and dusk." },
      { name: "Rowing on the Sarobar", note: "Several clubs, some over a century old." },
    ],
    plates: ["river", "rooftops", "collegestreet"],
    photos: ["dakshinapan", "dakshinapan", "kolkata-metro"],
    walk: [
      { stop: "Rabindra Sarobar metro", minutes: 0, note: "Come up at the lake's northern edge." },
      { stop: "The lake circuit", minutes: 20, note: "About three kilometres all the way round." },
      { stop: "Nipponzan Myohoji temple", minutes: 30, note: "Southern bank. Shoes off." },
      { stop: "Dhakuria Bridge", minutes: 40, note: "The local landmark, and the roll shops." },
    ],
    scene: "river",
    photo: "dakshinapan",
  },
  {
    slug: "jadavpur",
    name: "Jadavpur",
    bengali: "যাদবপুর",
    zone: "south",
    tagline: "A university, a refugee colony, and sixty years of student politics.",
    knownFor: "Jadavpur University, 8B bus stand, bookshops and argument",
    coords: { lat: 22.4991, lng: 88.3712 },
    bestHour: "Late afternoon, around the 8B stand",
    summary:
      "Built on refugee resettlement after 1947, and now the address of a university that has been at the centre of every political argument in the state.",
    body: [
      "Much of Jadavpur was settled by refugees from East Bengal after Partition, in colonies that were often established by occupation rather than allocation. That history is not incidental: it shaped the politics of the whole southern belt.",
      "Jadavpur University began as the National Council of Education in 1906, founded during the Swadeshi movement as an explicitly nationalist alternative to Calcutta University. It became a university in 1955 and is now among the strongest engineering and humanities institutions in India.",
      "Its student politics are famous, continuous and consequential. The Naxalite period, the 2014 Hokkolorob protests, and repeated confrontations since have made the campus a national reference point for student activism.",
      "The 8B bus stand outside the main gate is the social centre: bookstalls, tea, rolls, and an adda that runs from mid-afternoon until the shops close.",
    ],
    buildings: [
      { name: "Jadavpur University", note: "Founded 1906 as the National Council of Education, a Swadeshi project." },
      { name: "8B bus stand", note: "Bookstalls, tea and argument. The functional centre of the quarter." },
      { name: "Sukanta Setu", note: "The flyover, and the boundary most people use to describe where Jadavpur starts." },
    ],
    eats: [
      { name: "Milanda's canteen", where: "Inside the campus", note: "Cheap, loud, and where a great deal has been decided." },
      { name: "Kasturi", where: "Jadavpur", note: "Bangladeshi Bengali. Kochu pata chingri and shorshe ilish." },
      { name: "8B roll shops", where: "The bus stand", note: "Student prices, open until late." },
      { name: "Tasty Corner", where: "Near the campus", note: "Chowmein and chilli chicken, in enormous portions." },
    ],
    figures: [
      { name: "Aurobindo Ghose", note: "Was the first principal of the Bengal National College, Jadavpur's ancestor." },
      { name: "Buddhadeb Bose", note: "Founded Jadavpur's comparative literature department, the first in Asia." },
    ],
    thingsToSee: [
      { name: "The 8B bookstalls", note: "Political pamphlets, little magazines, and secondhand paperbacks." },
      { name: "Campus in early spring", note: "Basanta Utsav, and the walls repainted with new slogans." },
      { name: "The refugee colony street grid", note: "Narrow, unplanned, and legible if you know what it is." },
    ],
    plates: ["collegestreet", "rooftops", "streetfood"],
    photos: ["book-fair", "kolkata-metro", "tram-grass-track"],
    walk: [
      { stop: "Jadavpur station", minutes: 0, note: "Or the 8B stand, which is the real arrival point." },
      { stop: "The 8B bookstalls", minutes: 5, note: "Little magazines and pamphlets." },
      { stop: "Jadavpur University main gate", minutes: 10, note: "Walk in. Nobody will stop you." },
      { stop: "Milanda's canteen", minutes: 18, note: "Tea, and whatever the argument is today." },
      { stop: "Kasturi", minutes: 30, note: "Lunch, and order the kochu pata chingri." },
    ],
    scene: "collegestreet",
    photo: "jadavpur-university",
  },
  {
    slug: "tollygunge",
    name: "Tollygunge",
    bengali: "টালিগঞ্জ",
    zone: "south",
    tagline: "Bengali cinema's address, and the end of the tram line.",
    knownFor: "Tollywood studios, the club, the last tram terminus",
    coords: { lat: 22.4956, lng: 88.3465 },
    bestHour: "Late afternoon around the studio gates",
    summary:
      "Named for Major William Tolly, who dredged the Adi Ganga in 1775. It gave its first syllable to Tollywood, and the film industry is still here.",
    body: [
      "Major William Tolly cut and dredged a canal through the silted Adi Ganga in the 1770s to reopen a trade route east, and the settlement that grew at its bank took his name.",
      "In the 1930s the New Theatres studio established Bengali cinema here, producing in Bengali and Hindi simultaneously and creating the first Indian studio system worth the name. P. C. Barua's Devdas, in 1935, set the template for Indian melodrama.",
      "The name Tollywood, coined for this district, later travelled and got attached to Telugu cinema. It started here.",
      "The Tollygunge Club, founded in 1895 on an indigo plantation, is one of the last of the great colonial clubs, with a golf course, stables and an enormous banyan. It remains determinedly itself.",
      "Tollygunge was also the southern terminus of the tram network, and the last route out of it ran until the network was effectively wound down.",
    ],
    buildings: [
      { name: "Tollygunge Club", note: "1895, on an indigo plantation. Golf, stables, and a banyan you can walk under." },
      { name: "Technicians' Studio", note: "1958. Still a working film studio." },
      { name: "Mahanayak Uttam Kumar metro", note: "Renamed for the actor. Line 1's southern anchor for decades." },
      { name: "Tolly's Nullah", note: "The canal Major Tolly dredged in the 1770s, along the old Adi Ganga." },
    ],
    eats: [
      { name: "Sonar Tori", where: "Tollygunge", note: "Bengali, and quieter than the Ballygunge equivalents." },
      { name: "Bijoli Grill", where: "Deshapriya Park, nearby", note: "Since 1927. Caterers to half the weddings in south Kolkata." },
      { name: "Tollygunge phuchka stalls", where: "Around the metro", note: "Evening trade, high turnover." },
    ],
    figures: [
      { name: "Uttam Kumar", note: "The Mahanayak. The metro station carries his name." },
      { name: "P. C. Barua", note: "Directed and starred in Devdas, 1935, at New Theatres." },
      { name: "Ritwik Ghatak", note: "Worked in and around these studios, mostly unprofitably." },
    ],
    thingsToSee: [
      { name: "The studio gates in the afternoon", note: "Technicians' Studio still works. Shoots spill onto the road." },
      { name: "The Tollygunge Club banyan", note: "If you can get a guest pass. It is worth the effort." },
      { name: "Tolly's Nullah", note: "What is left of the Adi Ganga, and a live restoration argument." },
    ],
    storySlugs: ["the-last-tram"],
    plates: ["tram", "rooftops", "river"],
    photos: ["nandan", "tram-grass-track", "kolkata-metro"],
    walk: [
      { stop: "Mahanayak Uttam Kumar metro", minutes: 0, note: "Line 1, southern end." },
      { stop: "Tollygunge Club gate", minutes: 8, note: "Members and guests. The exterior is still something." },
      { stop: "Technicians' Studio", minutes: 16, note: "A working studio, not a museum." },
      { stop: "Tolly's Nullah", minutes: 24, note: "The canal, and what has become of it." },
    ],
    scene: "tram",
    photo: "tram-grass-track",
  },
];
